### ISSUE TITLE
example config file doesn't exists

### ISSUE THREAD

**Issue by iman432** [srsran/srsRAN_Project#1]
Hi srsRAN,

Thanks a lot for this project, 
I cannot find configs/ folder in codes, can you please share or update source codes?

**Comment by andrepuschmann** [comment]
Hey, we've just pushed an update that contains two example configs. From your build folder, you should be able to run with:
`./apps/gnb/gnb -c ../configs/gnb_rf_b200_tdd_n78_10mhz.yml`.
Make sure to adopt to your AMF params.

**Comment by alexjiao2021** [comment]
Does srsgNB support LimeSDR? If yes, could you provide example files? Thanks!

**Comment by pricalinat** [comment]
> 

I also want to ask, will it support bladerf? Thanks.

**Comment by iman432** [comment]
> Hey, we've just pushed an update that contains two example configs. From your build folder, you should be able to run with: `./apps/gnb/gnb -c ../configs/gnb_rf_b200_tdd_n78_10mhz.yml`. Make sure to adopt to your AMF params.


Thank you, but seems there is an issue with "cell_cfg", got below error, i think should be "common_cell" :

by cell_cfg:

![1](https://user-images.githubusercontent.com/44318450/220837587-4b115837-82e1-433f-a137-db90a3ffe0ec.PNG)

by common_cell is normal:

![2](https://user-images.githubusercontent.com/44318450/220837799-eedc5a6e-0139-4991-9cb5-95d09f61eb0d.PNG)

config:

![3](https://user-images.githubusercontent.com/44318450/220837982-ae1c1f91-6b5a-4efc-b4d7-fab1775aa148.PNG)

**Comment by andrepuschmann** [comment]
@iman432 Please do a git pull and update to `77be7d3391d45fb606aec4f0c16907390b49b0b0`. The name of that struct has been changed in one of the last commits.

> Does srsgNB support LimeSDR? If yes, could you provide example files? Thanks!
@alexjiao2021 We don't support it currently. Only UHD-based devices. But we might add support to it later on.

> I also want to ask, will it support bladerf? Thanks.
@pricalinat Same as above. We'll add support to it later.

**Comment by jiban-ray** [comment]
![image](https://user-images.githubusercontent.com/74227867/221382948-927011bb-3624-4b41-99e2-692d61fb7a78.png)

Getting this error.|
**INI was not able to parse common_cell.++**
Can anyone suggest solutions, please?
