### ISSUE TITLE
Unable to download the config of srsUE in the tutorial

### ISSUE THREAD

**Issue by 2629788464** [srsran/srsRAN_Project#118]
Hello!
## Issue Description ##
I found that I could not download the config of srsUE in the [tutorial](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#configuration) since the config of gnb was update several days ago.

**Comment by brendan-mcauliffe** [comment]
Hi @2629788464, 

Thanks for flagging, I will push a fix now.
