### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by mikejdoe** [srsran/srsRAN_Project#12]
## Issue Description ##
build fails for commit 0523be699a66d59b7a2f4bf1381917f98d713f44

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
clean build fails, when building tests

## Expected Behavior ##
build should succeed 

## Actual Behaviour ##

Scanning dependencies of target du_high_test
[ 54%] Building CXX object tests/unittests/du_high/CMakeFiles/du_high_test.dir/du_high_test.cpp.o
In file included from /home/srs/srsRAN_Project/tests/unittests/du_high/du_high_test.cpp:27:
/home/srs/srsRAN_Project/tests/unittests/du_high/test_utils/du_high_worker_manager.h: In constructor 'constexpr srsran::du_high_worker_manager::du_high_worker_manager()':
/home/srs/srsRAN_Project/tests/unittests/du_high/test_utils/du_high_worker_manager.h:29:8: error: use of deleted function 'srsran::task_worker::task_worker(srsran::task_worker&&)'
   29 | struct du_high_worker_manager {
      |        ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/srs/srsRAN_Project/lib/du_high/du_high.h:35,
                 from /home/srs/srsRAN_Project/tests/unittests/du_high/du_high_test.cpp:23:
/home/srs/srsRAN_Project/include/srsran/support/executors/task_worker.h:55:3: note: declared here
   55 |   task_worker(task_worker&&)                 = delete;
      |   ^~~~~~~~~~~
In file included from /home/srs/srsRAN_Project/tests/unittests/du_high/du_high_test.cpp:27:
/home/srs/srsRAN_Project/tests/unittests/du_high/test_utils/du_high_worker_manager.h:29:8: error: use of deleted function 'srsran::task_worker::task_worker(srsran::task_worker&&)'
   29 | struct du_high_worker_manager {
      |        ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/srs/srsRAN_Project/lib/du_high/du_high.h:35,
                 from /home/srs/srsRAN_Project/tests/unittests/du_high/du_high_test.cpp:23:
/home/srs/srsRAN_Project/include/srsran/support/executors/task_worker.h:55:3: note: declared here
   55 |   task_worker(task_worker&&)                 = delete;
      |   ^~~~~~~~~~~
/home/srs/srsRAN_Project/tests/unittests/du_high/du_high_test.cpp: In function 'void test_f1_setup_local()':
/home/srs/srsRAN_Project/tests/unittests/du_high/du_high_test.cpp:42:30: note: synthesized method 'constexpr srsran::du_high_worker_manager::du_high_worker_manager()' first required here
   42 |   du_high_worker_manager     workers;
      |                              ^~~~~~~
make[2]: *** [tests/unittests/du_high/CMakeFiles/du_high_test.dir/build.make:82: tests/unittests/du_high/CMakeFiles/du_high_test.dir/du_high_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:9892: tests/unittests/du_high/CMakeFiles/du_high_test.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

**Comment by andrepuschmann** [comment]
Please provide details as requested in the issue template. Closing this until more information is provided.
