### ISSUE TITLE
gnb gets an error while we have 15kHz SCS in band n78

### ISSUE THREAD

**Issue by emadrezz** [srsran/srsRAN_Project#123]
## Issue Description ##
As what we see in the standard 38.101-1 v17.5 - Table 5.3.5-1  and https://www.sharetechnote.com/html/5G/5G_FR_Bandwidth.html#Spectrum_and_Bandwidth the band n78 supports 15KHz subcarrier spacing as well as 30KHz scs in different bandwidths but srsGNB will run perfectly on 30KHz but gets an error with 15KHz. I've tested this exact configuration but on band n3 with 15KHz and it worked fine
screenshot of gnb with band n3 and 15khz scs : 

![Screenshot from 2023-07-11 10-58-57](https://github.com/srsran/srsRAN_Project/assets/88979187/b708d3a0-cae8-4538-810b-b8135f8d2380)
screenshot of gnb with band n78 and 30khz scs : 
![Screenshot from 2023-07-11 11-04-30](https://github.com/srsran/srsRAN_Project/assets/88979187/68451c5e-861a-412a-928d-fdbbcd4649cf)
screenshot of gnb with band n78 and 15khz scs : 
![Screenshot from 2023-07-11 11-00-50](https://github.com/srsran/srsRAN_Project/assets/88979187/bd26271b-ade5-4421-b313-31f45b49bc3c)

gnb log for band 78 and 15 khz scs:
![Screenshot from 2023-07-11 11-08-50](https://github.com/srsran/srsRAN_Project/assets/88979187/e0708031-e957-408e-abf3-2e8f7045ff91)

## Setup Details ##
I'm using usrp x300 with latest version of uhd and ubuntu 22 and my configuration file goes as below:
![Screenshot from 2023-07-11 11-16-35](https://github.com/srsran/srsRAN_Project/assets/88979187/2c82d339-bbc1-4e5d-ac4b-ae3808c71c0f)

## Expected Behavior ##
I supposed that gnb works fine with 15khz scs in band n78 with srate 11.52

## Actual Behaviour ##
I've got the error about SSB SCS must be equal to SCS common jst with 15KHZ scs in band n78

**Comment by ismagom** [comment]
Hi, band n78 with 15 KHz requires mixed numerology, since SSB is still 30 KHz. Unfortunately mixed numerology is not yet supported.

**Comment by emadrezz** [comment]
Thanks for quick responce.
