### ISSUE TITLE
ofh_compression_test_data.tar.gz does not exist

### ISSUE THREAD

**Issue by kevinyuan** [srsran/srsRAN_Project#130]
CMake Error at tests/unittests/CMakeLists.txt:42 (message):
  Vector file
  srsRAN_Project/tests/unittests/ofh/compression/ofh_compression_test_data.tar.gz
  does not exist.
Call Stack (most recent call first):
  tests/unittests/ofh/compression/CMakeLists.txt:27 (add_test_vector)

**Comment by kevinyuan** [comment]
I just found the test vectors in the release folder. THanks.

**Comment by sauka** [comment]
Hi @kevinyuan ,

Could you share the commands you used to compile tests with testvectors?

Do you see the ofh_compression_test_data.tar.gz file in `srsRAN_Project/tests/unittests/ofh/compression/` after extracting the PHY testvector set?
