### ISSUE TITLE
5G NTN RAN support

### ISSUE THREAD

**Issue by zbh888** [srsran/srsRAN_Project#133]
Hello SRS team, I saw the homepage mentioned NTN solution.  https://srs.io/non-terrestrial-networks/

Do you have any open source project for that?

Thank you!

**Comment by pgawlowicz** [comment]
Hi, 

It is currently under development. Please check the code repository for updates on this feature.

Best Regards,
Piotr

**Comment by bhack** [comment]
@yagoda I saw recently that you have added a GEO conf at:
https://github.com/srsran/srsRAN_Project/blob/main/configs/geo_ntn.yml.  
How we could test this? I don't think the UE (still only the 4G repo) is ready for this.

**Comment by yagoda** [comment]
Hi,

There is support for NTN GEO but this requires an NTN-capable UE & a channel emulator, we will be releasing an app note soon on how to set up a GEO scenario with an amarisoft NTN UE & a channel emulator.

Regards,
Justin

**Comment by bhack** [comment]
@yagoda Thank you for the update. Can you ping us here when the doc is available?
