### ISSUE TITLE
Malformed RIC subscription delete response

### ISSUE THREAD

**Issue by yc541** [srsran/srsRAN_Project#190]
## Issue Description ##
When testing SRSRAN with Near-RT RIC and xApp (https://docs.srsran.com/projects/project/en/latest/tutorials/source/flexric/source/index.html) with USRP and COTS UE (rather than zmq in the tutorial), sometimes the RAN sends a malformed RIC subscription delete response when the xApp unsubscribes and causes the RIC to crash. 

There is no such issue when running zmq since the RSRP is always 65. When using a USRP and a COTS UE, the RSRP is 0 when there is no UE traffic and the RSRP is around 20 to 30 when there is UE traffic. In this case and the RAN sometimes sends a malformed RIC subscription delete response with one incorrect byte (sometimes this packet is in the correct form) and crashes the RIC.

## Setup Details ##

SRSRAN is on a Ubuntu 20.04 machine, Open5GS v2.6.1 is on a VM. The USRP is an X300 and the UE is a Oneplus Nord 5G. UHD version is 4.0. The UE attaches correctly and has access to the Internet.

## Expected Behavior ##
RAN sends the correct RIC subscription delete response message

## Actual Behaviour ##
The message sometimes has one incorrect byte

## Additional Information ##
The E2AP pcap, gnb/RIC logs and gnb configuration files are attached.

Any help would be appreciated, thanks!

[SRSRAN_RIC.zip](https://github.com/srsran/srsRAN_Project/files/12463104/SRSRAN_RIC.zip)

**Comment by pgawlowicz** [comment]
Hi, 
Thank you for your report. 
The E2 module is still under development. The malformed RIC subscription delete response has been fixed, and the fix will be available in the next release. 
The currently exposed metrics are only examples, and we are working to support more of them.

Best,
Piotr

**Comment by yc541** [comment]
> 

Many thanks for the quick update! Look forward to testing the next release.

> Hi, Thank you for your report. The E2 module is still under development. The malformed RIC subscription delete response has been fixed, and the fix will be available in the next release. The currently exposed metrics are only examples, and we are working to support more of them.
> 
> Best, Piotr
