### ISSUE TITLE
Open5gs-srsRAN - docker AMF connection refused gNB

### ISSUE THREAD

**Issue by databatt** [srsran/srsRAN_Project#191]
## Issue Description ##
[Describe the issue in detail]

Following documentation for docker compose open5gs+srsran, open5gs container is correctly created but some issue appear with amf conf file.

08/29 09:48:01.370: [amf] INFO: gNB-N2 accepted[10.53.1.3]:51216 in ng-path module (../src/amf/ngap-sctp.c:113)
08/29 09:48:01.380: [amf] INFO: gNB-N2 accepted[10.53.1.3] in master_sm module (../src/amf/amf-sm.c:706)
08/29 09:48:01.401: [amf] INFO: [Added] Number of gNBs is now 1 (../src/amf/context.c:1034)
08/29 09:48:01.427: [amf] INFO: gNB-N2[10.53.1.3] max_num_of_ostreams : 30 (../src/amf/amf-sm.c:745)
08/29 09:48:07.329: [amf] INFO: gNB-N2[10.53.1.3] connection refused!!! (../src/amf/amf-sm.c:758)
08/29 09:48:07.329: [amf] INFO: [Removed] Number of gNBs is now 0 (../src/amf/context.c:1061)

AMF tries to add a gNB and later is removed due to connection refused. The conf file is like is configure in repository. If some issue with the amf.yml it is used, maybe it is needed to change conf files to be used for docker compose.

https://github.com/srsran/srsRAN_Project/tree/main/docker

## Setup Details ##
Problem appear in a server with Ubuntu22 and docker compose execution with open5gs and srsran as documentation.

## Expected Behavior ##
Not to have a connection refused.

## Actual Behaviour ##

Webui and mongo info seems correct but srsran/gnb is not up due to this error could be related:

root@maquina-rodrigo:~/srsran_opensource/srsRAN_Project/docker# docker logs 45f302d4d6c6
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Lower PHY in dual executor mode.

--== srsRAN gNB (commit ) ==--

Connecting to AMF on 10.53.1.2:38412
Available radio types: uhd.
Making USRP object with args 'type=b200,num_recv_frames=64,num_send_frames=64'
Failed to open device with address 'type=b200,num_recv_frames=64,num_send_frames=64': LookupError: KeyError: No devices found for ----->
Device Address:
    type: b200
    num_recv_frames: 64
    num_send_frames: 64

**Comment by andrepuschmann** [comment]
Well, you don't have a USRP connected to the PC it seems. So the gNB quits automatically and therefore also releases the AMF connection.
