### ISSUE TITLE
Handover feature availability

### ISSUE THREAD

**Issue by kunwooch** [srsran/srsRAN_Project#196]
Hello, my team (PAWS lab at Princeton University) is trying to emulate 5G SA Xn handover between different gNodeBs, and I saw the roadmap on your website that the handover feature is coming soon. I was wondering if there is an estimated date for the release of this feature. Also, if it is mostly developed, we can also further contribute to the development of this feature.

Looking forward to hearing from you.

**Comment by ismagom** [comment]
Hi @kunwooch , NG and F1 HO will be released soon (probably end of September/October). Xn HO is not in our roadmap for this year. 

Please use Discussions posts for questions and Issues for problems in the code. Thanks!
