### ISSUE TITLE
Unable to connect gNB and UE, X310 USRP

### ISSUE THREAD

**Issue by NobleK3N8** [srsran/srsRAN_Project#206]
## Issue Description ##
I'm unable to connect two radios x310 (one for gnb and one for ue), when I start the applications in the trace of the UE always appear: Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0x39, tti=9294. 
From the troubleshooting page of the documentation I already use a gps reference for the radios and use the performance script.

## Setup Details ##
- 2 PC Dell Precision 3630 Tower (one as gnb and one as UE)
- Dell Precision 7920 Rack as Core (open5gs)
- USRP connected over fiber
- UHD 4.4
- UE commit fa56836b1
- gnb commit e043e1e40

## Expected Behavior ##
Successfully connection between gNB and UE.

## Actual Behaviour ##
gnb console:
![gnb](https://github.com/srsran/srsRAN_Project/assets/42392300/3f647832-c1cd-4181-9091-9c787b9d5ac0)

ue console:
![ue](https://github.com/srsran/srsRAN_Project/assets/42392300/9e873cf6-ecc5-47d7-a489-d777773a426e)

## Steps to reproduce the problem ##
- The 2 USRP are using a GPS antenna to the reference signal and connected over fiber to the PC, around 500 meters.
- Conf files:
[amf.txt](https://github.com/srsran/srsRAN_Project/files/12561991/amf.txt)
[gnb_x310.txt](https://github.com/srsran/srsRAN_Project/files/12561992/gnb_x310.txt)
[ue.txt](https://github.com/srsran/srsRAN_Project/files/12561993/ue.txt)
[upf.txt](https://github.com/srsran/srsRAN_Project/files/12561994/upf.txt)

## Additional Information ##
Logs:
[gnb-log.txt](https://github.com/srsran/srsRAN_Project/files/12561997/gnb-log.txt)
[ue-log.txt](https://github.com/srsran/srsRAN_Project/files/12561998/ue-log.txt)

Thanks!

**Comment by anilgurses** [comment]
You should enable debug logs on both ends and try it again.  You might have RF gap issue.
