### ISSUE TITLE
Slicing not working

### ISSUE THREAD

**Issue by MKPAUGURS** [srsran/srsRAN_Project#253]
Here is the provided example from the repository
Network slicing example configuration

This is a supplementary configuration to enable slicing support. This file will be passed to the gNB along with the base configuration 
at start-up. The following command may be used to run the gNB with this configuration file: 
sudo ./gnb -c gnb_ru_ran550_tdd_n78_100mhz_2x2.yml -c slicing.yml

I am running like:

user:~/Documents/srsRAN config for mikrotik$ sudo gnb -c gnb_b210_20MHz_mikrotik_chateau.yml -c slicing.yml
-c: At Most 1 required but received 2
Run with --help for more information.

And if I add the following parameters to the main gnb_b210_20MHz_mikrotik_chateau.yml file

slicing:
    sst: 1
    sd: 1

then I got issue:

user:~/Documents/srsRAN config for mikrotik$ sudo gnb -c gnb_b210_20MHz_mikrotik_chateau.yml
INI was not able to parse slicing.++
Run with --help for more information.

-----------------------------------------------------------------------------------------------------------------------------------------------------
I am connecting to Open5GS

amf:
  addr: 127.0.1.100                                             # The address or hostname of the AMF.
  bind_addr: 127.0.0.1                                          # A local IP that the gNB binds to for traffic from the AMF.

rf_driver:
  device_driver: uhd                                            # The RF driver name.
  device_args: type=b200,num_recv_frames=64,num_send_frames=64  # Optionally pass arguments to the selected RF driver.
  clock: internal                                               # Specify the clock source used by the RF.
  sync:                                                         # Specify the sync source used by the RF.
  srate: 23.04                                                  # RF sample rate might need to be adjusted according to selected bandwidth.
  otw_format: sc12
  tx_gain: 60                                                   # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 40                                                   # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 625000                                              # ARFCN of the downlink carrier (center frequency).
  band: 78                                                      # The NR band.
  channel_bandwidth_MHz: 20                                     # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                # Subcarrier spacing in kHz used for data.
  plmn: "00101"                                                 # PLMN broadcasted by the gNB.
  tac: 1                                                        # Tracking area code (needs to match the core configuration).
  pci: 1                                                        # Physical cell ID.

pcap:
  mac_enable: false                                             # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap                               # Path where the MAC PCAP is stored.
  ngap_enable: false                                            # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                             # Path where the NGAP PCAP is stored.
    
slicing:
    sst: 1
    sd: 1

**Comment by andrepuschmann** [comment]
You're likely having a copy paste error in the combined config. Double check spaces and tabs and that they are valid Json. Also make sure to use the most recent version of srsRAN
