### ISSUE TITLE
long duration data test dont work 

### ISSUE THREAD

**Issue by anurag7860** [srsran/srsRAN_Project#26]
## Issue Description ##
I am trying iperf in DL but data session wont last more than 10 -20 seconds , I tried external clock 10 Mhz also but results are same , can someone help 

## Setup Details ##
I am  using USRP 205mini and below is config for clock . 
 
rf_driver:
  device_driver: uhd                # The RF driver name.
  device_args: type=b200            # Optionally pass arguments to the selected RF driver.  
  clock: external                      # Specify the  clock source used by the RF.  
 sync: external

**Comment by mubk00** [comment]
Hi,

I believe it may be difficult for others to troubleshoot without any kind of logs. It is difficult to extrapolate from what you have described, as the issue could be related to connection stability or even other things. Could you please provide some logs?

**Comment by andrepuschmann** [comment]
Closing issue as no further information has been provided by creator.
