### ISSUE TITLE
Phone doesn’t register to home plmn of SIM card 

### ISSUE THREAD

**Issue by arrowtem** [srsran/srsRAN_Project#284]
Hello I have severel 5g Samsung phone’s ( s23 ultra, a52 , a73) 
I also have real 5g SIM card 
1) phone’s doesn’t connect to gNB if i set SIM card plmn . They see station in network selection , but when I press on station nothing happens . So phone sees mib and sib , but doesn’t start registration procedure 
2) if I set test plmn (01001) telephone’s register’s on station ( send setup complete ) , because I don’t know key’s of SIM card registration process is failed on auth request. 

why could be the reason that phone start registration on 00101 , but never start registration process on home’s plmn ? 

When I was running LTE enb my phone was registering on any plmn with no limitations 

does smth really changed in process of cell selection in 5g after 4G ? Maybe some problems with SIB1? Signal quality is very good , thanks for answer !

**Comment by ismagom** [comment]
Yes a few things change, please follow the COTS UE appnote in our documentation
