### ISSUE TITLE
Error starting userland proxy: open5gs docker 

### ISSUE THREAD

**Issue by raul-parada** [srsran/srsRAN_Project#287]
## Issue Description ##

```
Starting open5gs_5gc ... error

ERROR: for open5gs_5gc  Cannot start service 5gc: driver failed programming external connectivity on endpoint open5gs_5gc (9bc68d8a0151157d63a5680509c11fe54f041025bc18e2a2e501e9a6ee510a7a): Error starting userland proxy: listen tcp4 0.0.0.0:3000: bind: address already in use

ERROR: for 5gc  Cannot start service 5gc: driver failed programming external connectivity on endpoint open5gs_5gc (9bc68d8a0151157d63a5680509c11fe54f041025bc18e2a2e501e9a6ee510a7a): Error starting userland proxy: listen tcp4 0.0.0.0:3000: bind: address already in use
```
```
sudo ./gnb -c gnb_zmq.yaml 
Lower PHY in executor blocking mode.

--== srsRAN gNB (commit 5e6f50a20) ==--

Connecting to AMF on 10.53.1.2:38412
Failed to connect SCTP socket to 10.53.1.2:38412. error="Connection timed out" timeout=1392ms
srsGNB ERROR: Failed to create SCTP gateway.

Aborted (core dumped)
```

## Setup Details ##
Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1

I've followed this tutorial: https://docs.srsran.com/projects/project/en/latest/tutorials/source/flexric/source/index.html

## Expected Behavior ##
Running open5gs and gNB

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
Two weeks ago, I could run the whole tutorial succesfully, however, when I run it again, it doesn't work. I've tried to remove the container and build it again. However, I get the same error. I've tried to kill the process listening on port 3000.

```
sudo lsof -i :3000
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    7849 root   29u  IPv4 202231      0t0  TCP localhost:3000 (LISTEN)
rparada@rparada-NUC7i7BNH:~/srsRAN_Project/docker$ sudo kill 7849
```

Nevertheless, when I've tried to build it again. The same port is listening getting the same error. 
## Additional Information ##
Request additional information if required

**Comment by andrepuschmann** [comment]
Hey - yes, you have something else running on port 3000 already. Try to kill with `kill -9 7849`. But it's an issue in your local setup, not the RAN. Closing this ticket therefore.
