### ISSUE TITLE
Is there any specific gcc, g++ version requirement?

### ISSUE THREAD

**Issue by whitecloudy** [srsran/srsRAN_Project#3]
## Issue Description ##
Unable to build the project

## Setup Details ##
Ubuntu 18.04.6 LTS
cmake 3.25.2(I manually installed)
gcc 7.5.0
g++ 7.5.0

## Expected Behavior ##
Build Success

## Actual Behaviour ##
Build Fail
![image](https://user-images.githubusercontent.com/20039949/220870526-ce0a5878-adbe-4191-84a3-ad06e9250131.png)

## Steps to reproduce the problem ##
Just tried build as you told me.

## Additional Information ##
Although I successfully build with manullay installed g++-11 and  gcc-11, it would be nice to have minimum version requirement.

**Comment by andrepuschmann** [comment]
Yes, Ubuntu 18.04 is not supported anymore as the default compile is too old. You could upgrade them of course. Also see [here](https://github.com/srsran/srsRAN_Project/actions/runs/4246746296) for the pipeline with Ubuntu 20.04.

Closing this issue.

**Comment by whitecloudy** [comment]
@andrepuschmann Thanks. At least it would be nice to mention this problem in README or somewhere.
