### ISSUE TITLE
MAC pcap file shows that the radio type is FDD in the uplink when using n41

### ISSUE THREAD

**Issue by kyrlon** [srsran/srsRAN_Project#305]
## Issue Description ##
While monitoring the power headroom report, I noticed that in the uplink of my MAC layer pcap that it reports that the radio type is FDD when I am using n41. Is this a mistake? Attached is the pcap where it reports the radio type as FDD in the uplink, but TDD in the downlink.
[gnb_mac.txt](https://github.com/srsran/srsRAN_Project/files/13324103/gnb_mac.txt)

## Expected Behavior ##
Radio type to show TDD

## Actual Behaviour ##
![gnb_mac_pcap](https://github.com/srsran/srsRAN_Project/assets/25754667/d1759e09-6e2c-45b8-9f28-164e9f7b63f9)

**Comment by kyrlon** [comment]
I found here in this [file](https://github.com/srsran/srsRAN_Project/blob/374200deefd8e1b96fab7328525fd593a808a641/lib/mac/mac_ul/pdu_rx_handler.cpp#L384) that it is hard coded to FDD. Would this be the cause?

**Comment by andrepuschmann** [comment]
It's hard-coded because the duplex type doesn't reach the PCAP writer to set the actual value. It's a bit confusing I agree but I don't think it's causing any problem.
