### ISSUE TITLE
Fuzz testing on F1 and E1 interface

### ISSUE THREAD

**Issue by rajindersin** [srsran/srsRAN_Project#333]
I have a setup of 3VMs on VMware with srsUE, srsRAN and Open5gs, which able to make a NR registration. Now further I am looking to do the Fuzz testing on F1 and E1 interface for this where can I find the ip and configuration files for F1 and E1 interfaces from both CU, DU end and CUCP, CUUP end respectively ?

**Comment by ismagom** [comment]
Thanks for your interest. The F1 and E1 are currently not exposed outside the application.
