### ISSUE TITLE
"Expert Info (Error/Checksum): Illegal checksum value (0)" appears when parsing the PCAPs of the MAC layer data in Wireshark

### ISSUE THREAD

**Issue by MU092** [srsran/srsRAN_Project#341]
Hello, all.

I want to parse the PCAPs of the MAC layer data into the PDCP layer in Wireshark. But "Expert Info (Error/Checksum): Illegal checksum value (0)" appears.

I follow the https://docs.srsran.com/projects/project/en/latest/user_manuals/source/outputs.html where it indicates that
1. Edit->Preferences->Protocols->DLT_USER->Edit and add an entry with DLT=149 and Payload protocol=udp.
2. Analyze->Enabled Protocols->MAC-NR and enable mac_nr_udp

In addition, I make the following setting:
1. Edit->Preferences->Protocols->PDCP-NR->Ciphering algorithm to use if not signalled NEA3 (ZUC) and Integrity algorithm to use if not signalled NEA3 (ZUC)

The image that appears in Wireshark is as follows：

![屏幕截图 2023-11-27 224144](https://github.com/srsran/srsRAN_Project/assets/88261696/9d48f700-0ed9-4934-b692-7b50afe4be50)

**Comment by pgawlowicz** [comment]
@MU092 could you try with the newest version?
