### ISSUE TITLE
Physical QoS is not applied in gNB

### ISSUE THREAD

**Issue by AEncinas19** [srsran/srsRAN_Project#351]
## Issue Description ##
I configure in Open5GS a GBR Flow but the bit rate limitation is not deployed in the srsran gNB.

## Setup Details ##
I am using the last commit from the test branch and the following Open5GS and gNB Qos configurations:
![Screenshot from 2023-12-04 16-42-20](https://github.com/srsran/srsRAN_Project/assets/49205996/d81036e5-6492-4635-8c86-0e685cbf78d3)

>  qos:
>    -
>     five_qi: 5 
>     rlc:
>       mode: am
>       am:
>         tx:
>           sn: 12
>           t-poll-retransmit: 80
>           max-retx-threshold: 4
>           poll-pdu: 64
>           poll-byte: 125
>           queue-size: 4096
>         rx:
>           sn: 12
>           t-reassembly: 80
>           t-status-prohibit: 10
>     pdcp:
>       integrity_required: false
>       tx:
>         sn: 12
>         discard_timer: -1
>         status_report_required: false
>       rx:
>         sn: 12
>         t_reordering: 80
>         out_of_order_delivery: false
>     f1u_du:
>       backoff_timer: 10
>     f1u_cu_up:
>       backoff_timer: 10
>     mac:
>       lc_priority: 5
>       lc_group_id: 2
>       bucket_size_duration_ms: 5
>       prioritized_bit_rate_kBps: 65537
>    -
>      five_qi: 9 # E.g. Buffered video streaming, TCP-based traffic
>      rlc:
>        mode: am
>        am:
>          tx:
>            sn: 12
>            t-poll-retransmit: 80
>            max-retx-threshold: 4
>            poll-pdu: 64
>            poll-byte: 125
>            queue-size: 4096
>          rx:
>            sn: 12
>            t-reassembly: 80
>            t-status-prohibit: 10
>      pdcp:
>        integrity_required: false
>        tx:
>          sn: 12
>          discard_timer: -1
>          status_report_required: false
>        rx:
>          sn: 12
>          t_reordering: 80
>          out_of_order_delivery: false
>      f1u_du:
>        backoff_timer: 10
>      f1u_cu_up:
>        backoff_timer: 10
>      mac:
>        lc_priority: 5
>        lc_group_id: 2
>        bucket_size_duration_ms: 5
>        prioritized_bit_rate_kBps: 65537

## Expected Behavior ##
I expected that when I trigger an iperf3 session with a traffic that matches with the filter, the bit rate will be equal or less than 300 Kbps.

## Actual Behaviour ##
It does not limit the bit rate.
![Screenshot from 2023-12-04 16-57-24](https://github.com/srsran/srsRAN_Project/assets/49205996/9ea6fce1-a071-4c11-9068-db7d34005644)

## Steps to reproduce the problem ##
Connect a COTS UE to the Open5GS via srsran-project gNB (using test branch) with the QoS configuration attached and try to send a traffic flow greater than the MBR set in Open5GS.

**Comment by ismagom** [comment]
Hi, QoS is only applied in the UL, not in the DL. This is a new feature that will come in Q1 2023

**Comment by AEncinas19** [comment]
I want QoS in the UL, I realized the iperf from the UE to the network.
