### ISSUE TITLE
Regarding CU/DU split source code for docker

### ISSUE THREAD

**Issue by Rath1nakumar** [srsran/srsRAN_Project#354]
Hi,

Whether any source code available to run 5G SA with CU/DU split using USRPB210 SDR in docker? Is possible to provide link for the same.

As we saw documentation with DU to connect with phsyical hardware (Falcon switch,SFP optical fibre cable). Without hardware support is possible to run SRSRAN code running du/cu in docker with x86 machine.

Regards,
Rathinakumar

**Comment by ismagom** [comment]
Hi, thanks for your interest. The CU and DU currently run in a single instance only. CU-DU split is not yet supported.
