### ISSUE TITLE
srs UE and gNB cannot maintain a stable connection

### ISSUE THREAD

**Issue by PanterasCy** [srsran/srsRAN_Project#375]
## Issue Description ##
I am following [this guide ](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html) from SRS to deploy  5G SA network by using srsRAN_Project(gNB) project and srsRAN_4G(UE) and Open5Gs(5GC). Everything is done according to the guide, including utilizing the Leo Bodnar GPS for synchronization and executing the SRS performance scripts on both machines. The UE is able to connect to the gNB and authenticate to the 5GC, but the connection between the the gNB and the UE breaks, after some random time (from several seconds up to some minutes).
## Setup Details ##
I'm using : 

- 2 identical machines with:
Ubuntu 22.04.1 LTS 
Intel i7-13700 with 64gb RAM
UDH 4.1.0.5-3

- 2 USRPs B210 connected over USB 3.0

- and the Leo Bodnar GPS for synchronisation 

-Current version of s

## Expected Behavior ##
Connection  between UE and gNB llasting longer/not breaking

## Actual Behaviour ##
Connection loss: 
```
Opening 1 channels in RF device=uhd with args=clock=external
Supported RF device list: UHD file
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args: type=b200,master_clock_rate=23.04e6
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
Setting manual TX/RX offset to 300 samples
Waiting PHY to initialize ... done!
Attaching UE...
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0x39, tti=8654
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0x39, tti=8814
Random Access Complete.     c-rnti=0x4602, ta=4
RRC Connected
PDU Session Establishment successful. IP: 10.45.0.6
RRC NR reconfiguration successful.
RF status: O=1, U=0, L=0
RF status: O=0, U=1, L=0
RF status: O=0, U=1, L=0
Scheduling request failed: releasing RRC connection...
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0x39, tti=9614
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0x39, tti=9774
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0x39, tti=9934
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0x39, tti=10094
[INFO] [UHD RF] Tx while waiting for EOB, timed out... 23.2688 >= 23.2687. Starting new burst...
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0x39, tti=14
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0x39, tti=174
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0x39, tti=334
Received RRC Release
RF status: O=0, U=1, L=0
```

## Configuration and Logs of UE and gNB ##
[logs_and_conf.zip](https://github.com/srsran/srsRAN_Project/files/13714000/logs_and_conf.zip)

## Additional Information ##
The issue seems to be related with #315. I have tried multiple configuration of cell configuration including antenna gains, enabling lte_sample_rates but nothing seems to work.

**Comment by dhiaboujebha** [comment]
@PanterasCy Do you have any news? Is it working for you now? If yes, can you please share your configs.
