### ISSUE TITLE
Error When compiling with DPDK enabled

### ISSUE THREAD

**Issue by IbrahimBabiker87** [srsran/srsRAN_Project#383]
## Issue Description ##
When trying to compile srsran with DPDK enabled -DENABLE_DPDK=ON it gives Error

## Setup Details ##
The setup was already working srsran 23.10 before last built.
## Expected Behavior ##
to work fine

## Actual Behaviour ##
Below error:
CMake Error at lib/hal/dpdk/bbdev/CMakeLists.txt:21 (add_library):
  No SOURCES given to target: hal_bbdev

## Steps to reproduce the problem ##
Using latest Srsran version and try to compile with DPDK

## Additional Information ##
![Screenshot from 2023-12-26 10-05-40](https://github.com/srsran/srsRAN_Project/assets/137053120/15a959f3-9010-47cc-8f66-b99c17287994)

**Comment by andrepuschmann** [comment]
Hey, thanks for the catch. I am afraid we've introduced this bug when transferring the code to the public repo.

Please apply this patch and it should be working again. We update the `main` branch shortly.

```
srsadmin@piptpgm:~/srsRAN_Project/build $ git diff
diff --git a/lib/hal/dpdk/bbdev/CMakeLists.txt b/lib/hal/dpdk/bbdev/CMakeLists.txt
index e7abe7740..c77909281 100644
--- a/lib/hal/dpdk/bbdev/CMakeLists.txt
+++ b/lib/hal/dpdk/bbdev/CMakeLists.txt
@@ -18,6 +18,14 @@
 # and at http://www.gnu.org/licenses/.
 #

+set(SOURCES
+  bbdev_acc.cpp
+  bbdev_acc_factory.cpp
+  bbdev.cpp
+  bbdev_op_pool_factory.cpp
+  ldpc/bbdev_ldpc_decoder.cpp
+)
+
 add_library(hal_bbdev STATIC ${SOURCES})
 target_compile_options(hal_bbdev PRIVATE ${DPDK_CFLAGS})
 target_link_libraries(hal_bbdev srslog ${DPDK_LIBRARIES})
```

Thanks
Andre
