### ISSUE TITLE
Two comment errors in the physical layer source

### ISSUE THREAD

**Issue by orklann** [srsran/srsRAN_Project#384]
From these two lines below, the comment are wrong:

https://github.com/srsran/srsRAN_Project/blob/dcd905cc67c18994a7b9300201dc0ade06287e82/lib/phy/lower/modulation/ofdm_modulator_impl.cpp#L92

https://github.com/srsran/srsRAN_Project/blob/dcd905cc67c18994a7b9300201dc0ade06287e82/lib/phy/lower/modulation/ofdm_demodulator_impl.cpp#L121

They should be ` // Get phase correction (TS 38.211, Section 5.4) ` not ` // Get phase correction (TS 138.211, Section 5.4) `

**Comment by andrepuschmann** [comment]
Thanks for the hint.
