### ISSUE TITLE
Why perform scalling in modulation?

### ISSUE THREAD

**Issue by orklann** [srsran/srsRAN_Project#394]
Hi, from reading the code, I am confused for the following lines, which perform scalling for the modulation, but I can not find any scalling needed in the specs, can anyone tell me why to apply scalling.

https://github.com/srsran/srsRAN_Project/blob/dcd905cc67c18994a7b9300201dc0ade06287e82/lib/phy/upper/channel_modulation/modulation_mapper_impl.cpp#L59-L65

**Comment by ismagom** [comment]
This is not an issue, better to discuss it in the Disucssion board.
