### ISSUE TITLE
nearRT-RIC and the gnb crash after the E42 subscription request from xApp

### ISSUE THREAD

**Issue by hullspokes** [srsran/srsRAN_Project#396]
## Issue Description ##
The nearRT-RIC and the gnb crash after execution of the xApp.
I can run the HelloWorld xApp without any problems, but not all other example xApps. 

## Setup Details ##
Everything was executed like in the documentation (https://docs.srsran.com/projects/project/en/latest/tutorials/source/flexric/source/index.html).
I needed to fix stuff according to https://github.com/srsran/srsRAN_Project/discussions/368#discussioncomment-7909775 but then I was able to connect a UE to the gNB and monitor traffic.

## Expected Behavior ##
Running the xApp like in the documentation.

## Actual Behaviour ##
After executing the xApp the nearRT-RIC and the gnb crash after the E42 subscription request.

xApp:
```
oran@oran-main:~$ ./flexric/build/examples/xApp/c/monitor/xapp_kpm_moni
[UTIL]: Setting the config -c file to /usr/local/etc/flexric/flexric.conf
[UTIL]: Setting path -p for the shared libraries to /usr/local/lib/flexric/
[xAapp]: Initializing ...
[xApp]: nearRT-RIC IP Address = 127.0.0.1, PORT = 36422
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libpdcp_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/librc_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libmac_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/librlc_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libtc_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libkpm_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libgtp_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libslice_sm.so
[NEAR-RIC]: Loading SM ID = 144 with def = PDCP_STATS_V0
[NEAR-RIC]: Loading SM ID = 3 with def = ORAN-E2SM-RC-v01.0
[NEAR-RIC]: Loading SM ID = 142 with def = MAC_STATS_V0
[NEAR-RIC]: Loading SM ID = 143 with def = RLC_STATS_V0
[NEAR-RIC]: Loading SM ID = 146 with def = TC_STATS_V0
[NEAR-RIC]: Loading SM ID = 2 with def = ORAN-E2SM-KPM-v03.00
[NEAR-RIC]: Loading SM ID = 148 with def = GTP_STATS_V0
[NEAR-RIC]: Loading SM ID = 145 with def = SLICE_STATS_V0
[xApp]: DB filename = /tmp/xapp_db_1704798222167452
 [xApp]: E42 SETUP-REQUEST tx
[xApp]: E42 SETUP-RESPONSE rx
[xApp]: xApp ID = 7
[xApp]: Registered E2 Nodes = 1
Connected E2 nodes = 1
Registered node 0 ran func id = 2
 [xApp]: reporting period = 1000 [ms]
[xApp]: Filter UEs by S-NSSAI criteria where SST = 1
[xApp]: E42 RIC SUBSCRIPTION REQUEST tx RAN_FUNC_ID 2 RIC_REQ_ID 1
xapp_kpm_moni: /home/oran/flexric/src/xApp/e42_xapp.c:296: e2_event_loop_xapp: Assertion `*e.p_ev != E42_RIC_SUBSCRIPTION_REQUEST_PENDING_EVENT && "Timeout waiting for Report. Connection lost with the RIC?"' failed.
Aborted (core dumped)
```

nearRT-RIC:
```
[iApp]: Initializing ...
[iApp]: nearRT-RIC IP Address = 127.0.0.1, PORT = 36422
[NEAR-RIC]: Initializing Task Manager with 2 threads
[E2AP]: E2 SETUP-REQUEST rx from PLMN   1. 1 Node ID 411 RAN type ngran_gNB
[NEAR-RIC]: Accepting RAN function ID 2 with def = ORAN-E2SM-KPM-v03.00
[iApp]: E42 SETUP-REQUEST rx
[iApp]: E42 SETUP-RESPONSE tx
[iApp]: SUBSCRIPTION-REQUEST RAN_FUNC_ID 2 RIC_REQ_ID 1 tx
[E2AP]: SCTP_SHUTDOWN_EVENT
[NEAR-RIC]: Removing E2 Node MCC 1 MNC 1 NB_ID 411
Pending event timeout happened. Communication with E2 Node lost?
nearRT-RIC: /home/oran/flexric/src/ric/near_ric.c:274: consume_fd: Assertion `fd > 0' failed.
Aborted (core dumped)
```

srsRAN gNB:
```
The PRACH detector will not meet the performance requirements with the configuration {Format 0, ZCZ 0, SCS 1.25kHz, Rx ports 1}.
Lower PHY in executor blocking mode.

--== srsRAN gNB (commit dcd905cc6) ==--

Connecting to AMF on 10.53.1.2:38412
Available radio types: zmq.
Connecting to NearRT-RIC on 127.0.0.1:36421
Cell pci=1, bw=20 MHz, dl_arfcn=368500 (n3), dl_freq=1842.5 MHz, dl_ssb_arfcn=368410, ul_freq=1747.5 MHz

==== gNodeB started ===
Type <t> to view trace
Failed to unpack E2SM KPM Action Definition
Segmentation fault
```

## Steps to reproduce the problem ##
1. Execute Documentation steps (https://docs.srsran.com/projects/project/en/latest/tutorials/source/flexric/source/index.html)
2. Fix according to https://github.com/srsran/srsRAN_Project/discussions/368#discussioncomment-7909775
3. run flexric + srsRAN + UE and try to start xapp_gtp_mac_rlc_pdcp_moni

**Comment by fklement** [comment]
I encounter exactly the same problem.

I also just checked the tests for srsRAN which all run without problems for me:
```
Start  662: e2_test_subscriber.when_e2_subscription_request_correct_sent_subscription_response
 662/4509 Test  #662: e2_test_subscriber.when_e2_subscription_request_correct_sent_subscription_response ...........................................................................................................................................................................................................................   Passed    0.01 sec
Start  663: e2_test_subscriber.when_e2_subscription_request_received_start_indication_procedure
 663/4509 Test  #663: e2_test_subscriber.when_e2_subscription_request_received_start_indication_procedure ..........................................................................................................................................................................................................................   Passed    0.01 sec
```

I have absolutely no idea what's going wrong here.

**Comment by yagoda** [comment]
hey,

can you share the gnb logs set to info?

**Comment by fklement** [comment]
For me it is the following:
[gnb.log](https://github.com/srsran/srsRAN_Project/files/13873612/gnb.log)

I think the interesting part is:

```
2024-01-09T11:03:44.194092 [E2-ASN1-PCK] [I] Received PDU of 204 bytes
2024-01-09T11:03:44.194116 [E2      ] [I] Handling E2 PDU of type initiatingMessage
2024-01-09T11:03:44.194125 [E2      ] [I] E2AP SDU, "initiatingMessage.RICsubscriptionRequest"
2024-01-09T11:03:44.194126 [E2      ] [I] Received RIC Subscription Request
2024-01-09T11:03:44.194128 [E2      ] [I] E2AP: Received subscription request
2024-01-09T11:03:44.195208 [ASN1    ] [E] The provided enum is not within the range of possible values (38>=2)
2024-01-09T11:03:44.195210 [ASN1    ] [E] Invalid choice id=38 for choice type meas_type_c
2024-01-09T11:03:44.195210 [ASN1    ] [E] Invalid choice id=38 for choice type meas_type_c
2024-01-09T11:03:44.195212 [ASN1    ] [E] [/home/oran/srsRAN_Project/lib/asn1/e2ap/e2sm_kpm.cpp][2962] Decoding failure.
2024-01-09T11:03:44.195220 [ASN1    ] [E] [/home/oran/srsRAN_Project/include/srsran/asn1/e2ap/../asn1_utils.h][1154] Decoding failure.
2024-01-09T11:03:44.195220 [ASN1    ] [E] [/home/oran/srsRAN_Project/lib/asn1/e2ap/e2sm_kpm.cpp][3395] Decoding failure.
2024-01-09T11:03:44.195220 [ASN1    ] [E] [/home/oran/srsRAN_Project/lib/asn1/e2ap/e2sm_kpm.cpp][3450] Decoding failure.
2024-01-09T11:03:44.195221 [ASN1    ] [E] [/home/oran/srsRAN_Project/lib/asn1/e2ap/e2sm_kpm.cpp][3795] Decoding failure.
2024-01-09T11:03:44.195221 [ASN1    ] [E] [/home/oran/srsRAN_Project/lib/asn1/e2ap/e2sm_kpm.cpp][3580] Decoding failure.
2024-01-09T11:03:44.195249 [ASN1    ] [E] Invalid field access for choice type "actionDefinition-formats" ("actionDefinition-Format4"!="actionDefinition-Format2")

```

**Comment by pgawlowicz** [comment]
Hi @hullspokes, 

the `xapp_gtp_mac_rlc_pdcp_moni` cannot work as it uses custom e2sm modules (for PDCP, RLC, MAC) that our E2 agent does not support. It supports only standard e2sm_kpm and e2sm_rc modules. 

We are working on a new tutorial version to remove the Unknown RAN Function ID problem.

**Comment by hullspokes** [comment]
@pgawlowicz Ah ok, I see... Is there already an approximate estimate of when this will work?

Do I currently have any other way of getting this to work with an older version (and if so, is there a manual for this)?

**Comment by pgawlowicz** [comment]
Our Flexric tutorial should work correctly if you change `e2sm_kpm_asn1_packer::ran_func_id = 2 -> 147` [here](https://github.com/srsran/srsRAN_Project/blob/main/lib/e2/e2sm/e2sm_kpm/e2sm_kpm_asn1_packer.cpp#L32) and recompile.

**Comment by hullspokes** [comment]
@pgawlowicz now when I start the gnb I'm getting the following error response in the nearRT-RIC:

```
nearRT-RIC: /home/oran/flexric/src/ric/generate_setup_response.c:71: accept_ran_func: Assertion `0!=0 && "Unknown RAN function ID from the agent received"' failed.
Aborted (core dumped)

```

**Comment by fklement** [comment]
@hullspokes did you build the flexric as described in the docs (also with the applied patch)?

**Comment by hullspokes** [comment]
@fklement My fault. Somehow sth. got messed up. Now the gnb is connecting correctly.
Can anyone explain the sense of those hardcoded ID's?

Now I have the next problem:
When I try to start any xApp it's resulting in a segfault for the xApp...

```
oran@oran-main:~$ ./flexric/build/examples/xApp/c/helloworld/xapp_hw
Setting the config -c file to /usr/local/etc/flexric/flexric.conf
Setting path -p for the shared libraries to /usr/local/lib/flexric/
[xAapp]: Initializing ...
[xApp]: nearRT-RIC IP Address = 127.0.0.1, PORT = 36422
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libpdcp_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/librc_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libmac_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/librlc_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libtc_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libkpm_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libgtp_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libslice_sm.so
[NEAR-RIC]: Loading SM ID = 144 with def = PDCP_STATS_V0
[NEAR-RIC]: Loading SM ID = 57244 with def = j
[NEAR-RIC]: Loading SM ID = 142 with def = MAC_STATS_V0
[NEAR-RIC]: Loading SM ID = 143 with def = RLC_STATS_V0
[NEAR-RIC]: Loading SM ID = 146 with def = TC_STATS_V0
[NEAR-RIC]: Loading SM ID = 147 with def = ORAN-E2SM-KPM
[NEAR-RIC]: Loading SM ID = 148 with def = GTP_STATS_V0
[NEAR-RIC]: Loading SM ID = 145 with def = SLICE_STATS_V0
Filename = /tmp/xapp_db_1704880392989820
Segmentation fault (core dumped)
```

@pgawlowicz Any ideas?

**Comment by pgawlowicz** [comment]
Note that only the patched `xapp_kpm_moni` will work correctly with our E2 agent. 

Not sure why Flexric uses the hardcoded RAN-Function-IDs, as each E2 agent might use different ID generation scheme. The RIC should rather take the E2 Setup Request send by an E2 Agent and use OID that is standardised for the e2sm modules (e.g. OID for e2sm_kpm is "1.3.6.1.4.1.53148.1.2.2.2") to create a mapping between RIC-RAN_FUNC_ID -> OID -> E2-Agent-RAN_FUNC_ID. Probably, it will be provided in the future. 

Anyway, we try to follow the ID scheme of Flexric, and it has changed recently (i.e., e2sm_kpm_asn1_packer::ran_func_id = 147 -> 2). Now, we are working to update our tutorial and xApp to follow this scheme.

**Comment by hullspokes** [comment]
Ok thanks for the clarification.

I'm using the patched `xapp_kpm_moni`. It's not working.
I see that the ORAN-E2SM-KPM ID is 147 (so it should be the right ID).

```
oran@oran-master:~$ ./flexric/build/examples/xApp/c/monitor/xapp_kpm_moni
Setting the config -c file to /usr/local/etc/flexric/flexric.conf
Setting path -p for the shared libraries to /usr/local/lib/flexric/
[xAapp]: Initializing ...
[xApp]: nearRT-RIC IP Address = 127.0.0.1, PORT = 36422
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libpdcp_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/librc_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libmac_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/librlc_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libtc_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libkpm_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libgtp_sm.so
[E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libslice_sm.so
[NEAR-RIC]: Loading SM ID = 144 with def = PDCP_STATS_V0
[NEAR-RIC]: Loading SM ID = 3996 with def = 1LY
[NEAR-RIC]: Loading SM ID = 142 with def = MAC_STATS_V0
[NEAR-RIC]: Loading SM ID = 143 with def = RLC_STATS_V0
[NEAR-RIC]: Loading SM ID = 146 with def = TC_STATS_V0
[NEAR-RIC]: Loading SM ID = 147 with def = ORAN-E2SM-KPM
[NEAR-RIC]: Loading SM ID = 148 with def = GTP_STATS_V0
[NEAR-RIC]: Loading SM ID = 145 with def = SLICE_STATS_V0
Filename = /tmp/xapp_db_1704883227952866
Segmentation fault (core dumped)

```

**Comment by fklement** [comment]
> Ok thanks for the clarification.
> 
> I'm using the patched `xapp_kpm_moni`. It's not working. I see that the ORAN-E2SM-KPM ID is 147 (so it should be the right ID).
> 
> ```
> oran@oran-master:~$ ./flexric/build/examples/xApp/c/monitor/xapp_kpm_moni
> Setting the config -c file to /usr/local/etc/flexric/flexric.conf
> Setting path -p for the shared libraries to /usr/local/lib/flexric/
> [xAapp]: Initializing ...
> [xApp]: nearRT-RIC IP Address = 127.0.0.1, PORT = 36422
> [E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libpdcp_sm.so
> [E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/librc_sm.so
> [E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libmac_sm.so
> [E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/librlc_sm.so
> [E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libtc_sm.so
> [E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libkpm_sm.so
> [E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libgtp_sm.so
> [E2 AGENT]: Opening plugin from path = /usr/local/lib/flexric/libslice_sm.so
> [NEAR-RIC]: Loading SM ID = 144 with def = PDCP_STATS_V0
> [NEAR-RIC]: Loading SM ID = 3996 with def = 1LY
> [NEAR-RIC]: Loading SM ID = 142 with def = MAC_STATS_V0
> [NEAR-RIC]: Loading SM ID = 143 with def = RLC_STATS_V0
> [NEAR-RIC]: Loading SM ID = 146 with def = TC_STATS_V0
> [NEAR-RIC]: Loading SM ID = 147 with def = ORAN-E2SM-KPM
> [NEAR-RIC]: Loading SM ID = 148 with def = GTP_STATS_V0
> [NEAR-RIC]: Loading SM ID = 145 with def = SLICE_STATS_V0
> Filename = /tmp/xapp_db_1704883227952866
> Segmentation fault (core dumped)
> ```

Make sure that in `/usr/local/lib/flexric` there are really the correct shared object from the patched build. 
I had to first manually delete the folder and then build again.
But now everything is working as expected!

**Comment by ankuramistry** [comment]
> Our Flexric tutorial should work correctly if you change `e2sm_kpm_asn1_packer::ran_func_id = 2 -> 147` [here](https://github.com/srsran/srsRAN_Project/blob/main/lib/e2/e2sm/e2sm_kpm/e2sm_kpm_asn1_packer.cpp#L32) and recompile.

I see an issue with Near-RT RIC implementation. I am using the tutorial for E2SM_KPM service module using https://docs.srsran.com/projects/project/en/latest/tutorials/source/flexric/source/index.html. 

Getting the below error on RIC followed by an immediate segmentation fault error on gNB. Can you help to fix the issue?

![Flexric_error](https://github.com/srsran/srsRAN_Project/assets/105061632/6aa1f62b-411a-4dd0-88eb-3795c605d39c)
![gNB error](https://github.com/srsran/srsRAN_Project/assets/105061632/cc9a0994-5532-4d59-8f22-375b32d7a0f0)

**Comment by pgawlowicz** [comment]
Could you provide more details? Like logs. Which metric do you request from the xapp?

**Comment by ankuramistry** [comment]
> Could you provide more details? Like logs. Which metric do you request from the xapp?

I am using the tutorial and the metric requested from xapp is using the xapp_mon_e2sm_kpm.conf config file (i.e., “DRB.UEThpDl” and “DRB.UEThpUl”). 

Attached are the logs. 
[gnb_mac.zip](https://github.com/srsran/srsRAN_Project/files/14271673/gnb_mac.zip)
[gnb.zip](https://github.com/srsran/srsRAN_Project/files/14271676/gnb.zip)
[gnb_rf_n300_tdd_n41_20mhz.zip](https://github.com/srsran/srsRAN_Project/files/14271683/gnb_rf_n300_tdd_n41_20mhz.zip)
[gnb_e2ap.zip](https://github.com/srsran/srsRAN_Project/files/14271684/gnb_e2ap.zip)

**Comment by pgawlowicz** [comment]
You need to add the following parameters in your gnb config file:
```
metrics:
  rlc_json_enable: 1                # Enable RLC metrics reporting
  rlc_report_period: 1000           # Set reporting period to 1s
```

see details [here](https://docs.srsran.com/projects/project/en/latest/tutorials/source/flexric/source/index.html#gnb).

**Comment by ankuramistry** [comment]
@pgawlowicz Thanks. Yes, noticed this missing metric in other discussion and added it and it is working now.

**Comment by peihaoY** [comment]
> Hi @hullspokes,
> 
> the `xapp_gtp_mac_rlc_pdcp_moni` cannot work as it uses custom e2sm modules (for PDCP, RLC, MAC) that our E2 agent does not support. It supports only standard e2sm_kpm and e2sm_rc modules.
> 
> We are working on a new tutorial version to remove the Unknown RAN Function ID problem.

I also followed the Flexric tutorial. For the following configuration (name = "KPM",), I tested and found that it only supports format = 1 and does not support format = 4, right?
`Sub_ORAN_SM_List` = (
    { name = "KPM", time = 1000,
      format = 4,
      ran_type = "ngran_gNB",
      actions = (
            { name = "DRB.UEThpDl" },
            { name = "DRB.UEThpUl" }
            )`
    }

**Comment by pgawlowicz** [comment]
Our E2 agent supports all formats 1-5 as tested with ORAN SC RIC. However, in case of Flexric only format 1 is handled correctly. We will investigate this issue.

**Comment by peihaoY** [comment]
> Our E2 agent supports all formats 1-5 as tested with ORAN SC RIC. However, in case of Flexric only format 1 is handled correctly. We will investigate this issue.

Hi [pgawlowicz](https://github.com/pgawlowicz),
`E2SM_RC service model: Only Control Service Style 2 is supported`  Is it also only tested with ORAN SC RIC? Does the tutorial's FlexRIC support running RC SM?"

**Comment by pgawlowicz** [comment]
no, RC SM was not tested with FlexRIC. We are working on an example showing how to use it with ORAN SC RIC.
