### ISSUE TITLE
The PRACH detector will not meet the performance requirements with the configuration {Format 0, ZCZ 0, SCS 1.25kHz, Rx ports 1}.

### ISSUE THREAD

**Issue by Erick5G** [srsran/srsRAN_Project#450]
## Issue Description ##
Good afternoon, I am starting out in this world of 5G.
And I would like to ask for your support to resolve the following question.

When running through ZMQ, gnb shows the following error:

**The PRACH detector will not meet the performance requirements with the configuration {Format 0, ZCZ 0, SCS 1.25kHz, Rx ports 1}.**
Lower PHY in executor blocking mode.

--== srsRAN gNB (commit 0b2702cca) ==--

Connecting to AMF on 127.0.0.5:38412
Available radio types: uhd and zmq.
Cell pci=1, bw=10 MHz, dl_arfcn=368500 (n3), dl_freq=1842.5 MHz, dl_ssb_arfcn=367930, ul_freq=1747.5 MHz

Reviewing the default script when installing open5gs, I can see that the **SCS has a value of 15 and not 1.25** as shown in the error.
Attached script line : **common_scs: 15                    # Subcarrier spacing in kHz used for data.**

What causes this error is that it cannot make a connection with the UE, because the parameters do not match.

So when the UE runs, it cannot detect a communication medium, therefore it cannot assign an address between GNB and UE.

Active RF plugins: libsrsran_rf_uhd.so libsrsran_rf_zmq.so
Inactive RF plugins: 
Reading configuration file ue_5g_zmq.conf...

Built in Release mode using commit fa56836b1 on branch HEAD.

Opening 1 channels in RF device=zmq with args=tx_port=tcp://127.0.0.1:2001,rx_port=tcp://127.0.0.1:2000,base_srate=11.52e6
Supported RF device list: UHD zmq file
CHx base_srate=11.52e6
Current sample rate is 1.92 MHz with a base rate of 11.52 MHz (x6 decimation)
CH0 rx_port=tcp://127.0.0.1:2000
CH0 tx_port=tcp://127.0.0.1:2001
Current sample rate is 11.52 MHz with a base rate of 11.52 MHz (x1 decimation)
Current sample rate is 11.52 MHz with a base rate of 11.52 MHz (x1 decimation)
Waiting PHY to initialize ... done!
Attaching UE...

The AMF and UPF files have been verified and are fine.
While in the gnb it does not make a communication.
2024-02-03T17:56:46.789134 [GNB     ] [I] Built in Release mode using commit 0b2702cca on branch main
2024-02-03T17:56:46.790226 [ALL     ] [I] Task worker "phy_worker" started...
2024-02-03T17:56:46.790337 [ALL     ] [I] Task worker "radio" started...
2024-02-03T17:56:46.790391 [ALL     ] [I] Task worker "ru_stats_worker" started...
2024-02-03T17:56:46.790560 [GNB     ] [I] Connecting to AMF (127.0.0.5)..
2024-02-03T17:56:46.790668 [GNB     ] [I] AMF connection established
2024-02-03T17:56:46.791095 [GNB     ] [I] Starting CU-CP...
2024-02-03T17:56:46.791214 [NGAP    ] [I] Sending NgSetupRequest
2024-02-03T17:56:46.891370 [GNB     ] [I] CU-CP started successfully
2024-02-03T17:56:46.891385 [UDP-GW  ] [I] UDP GW configured. rx_max_mmsg=256
2024-02-03T17:56:46.892023 [GTPU    ] [I] GTP-U demux. warn_on_drop=false
2024-02-03T17:56:46.892028 [GTPU    ] [I] Tunnel added. teid=0x000000
2024-02-03T17:56:46.892080 [CU-UP   ] [I] CU-UP starting...
2024-02-03T17:56:46.892229 [CU-CP   ] [I] Added CU-UP 0
2024-02-03T17:56:46.892255 [CU-UP-E1] [I] Sending E1SetupRequest
2024-02-03T17:56:46.892271 [CU-UP-E1] [I] "E1AP CU-UP Setup Procedure" finalized
2024-02-03T17:56:46.892277 [CU-UP   ] [I] CU-UP started successfully
2024-02-03T17:56:46.892589 [GNB     ] [I] SSB derived parameters for cell: 1, band: 3, dl_arfcn:368500, crbs: 52 scs:15kHz, ssb_scs:15kHz:
	 - SSB offset pointA:0 
	 - k_SSB:2 
	 - SSB arfcn:367930 
	 - Coreset index:0 
	 - Searchspace index:0
2024-02-03T17:56:46.903436 [zmq:tx:0:0] [I] Binding to address tcp://127.0.0.1:2000.
2024-02-03T17:56:46.913857 [zmq:rx:0:0] [I] Connecting to address tcp://127.0.0.1:2001.
2024-02-03T17:56:46.929382 [GNB     ] [I] Radio Unit created successfully
2024-02-03T17:56:46.954731 [DU      ] [I] DU created successfully
2024-02-03T17:56:46.954749 [DU      ] [I] Starting DU...
2024-02-03T17:56:46.954749 [DU      ] [I] Starting DU-High...
2024-02-03T17:56:46.954750 [DU-MNG  ] [I] DU manager starting...
2024-02-03T17:56:46.954939 [CU-CP   ] [I] Added DU 0
2024-02-03T17:56:46.955039 [DU-MNG  ] [I] SIB1 cell=0: {
  "cellSelectionInfo": {
    "q-RxLevMin": -70,
    "q-QualMin": -20
  },
  "cellAccessRelatedInfo": {
    "plmn-IdentityInfoList": [
      {
        "plmn-IdentityList": [
          {
            "mcc": [
              0,
              0,
              1
            ],
            "mnc": [
              0,
              1
            ]
          }
        ],
        "trackingAreaCode": "000000000000000000000111",
        "cellIdentity": "000000000000000000000001100110110000",
        "cellReservedForOperatorUse": "notReserved"
      }
    ]
  },
  "connEstFailureControl": {
    "connEstFailCount": "n1",
    "connEstFailOffsetValidity": "s30",
    "connEstFailOffset": 1
  },
  "servingCellConfigCommon": {
    "downlinkConfigCommon": {
      "frequencyInfoDL": {
        "frequencyBandList": [
          {
            "freqBandIndicatorNR": 3
          }
        ],
        "offsetToPointA": 0,
        "scs-SpecificCarrierList": [
          {
            "offsetToCarrier": 0,
            "subcarrierSpacing": "kHz15",
            "carrierBandwidth": 52,
            "txDirectCurrentLocation": 312
          }
        ]
      },
      "initialDownlinkBWP": {
        "genericParameters": {
          "locationAndBandwidth": 14025,
          "subcarrierSpacing": "kHz15"
        },
        "pdcch-ConfigCommon": {
          {
            "commonSearchSpaceList": [
              {
                "searchSpaceId": 1,
                "controlResourceSetId": 0,
                "monitoringSlotPeriodicityAndOffset": {
                },
                "monitoringSymbolsWithinSlot": "10000000000000",
                "nrofCandidates": {
                  "aggregationLevel1": "n0",
                  "aggregationLevel2": "n0",
                  "aggregationLevel4": "n1",
                  "aggregationLevel8": "n0",
                  "aggregationLevel16": "n0"
                },
                "searchSpaceType": {
                  "common": {
                    "dci-Format0-0-AndFormat1-0": {
                    }
                  }
                }
              }
            ],
            "searchSpaceSIB1": 0,
            "pagingSearchSpace": 1,
            "ra-SearchSpace": 1
          }
        },
        "pdsch-ConfigCommon": {
          {
            "pdsch-TimeDomainAllocationList": [
              {
                "mappingType": "typeA",
                "startSymbolAndLength": 53
              }
            ]
          }
        }
      },
      "bcch-Config": {
        "modificationPeriodCoeff": "n4"
      },
      "pcch-Config": {
        "defaultPagingCycle": "rf128",
        "nAndPagingFrameOffset": {
        },
        "ns": "one"
      }
    },
    "uplinkConfigCommon": {
      "frequencyInfoUL": {
        "frequencyBandList": [
          {
            "freqBandIndicatorNR": 3
          }
        ],
        "absoluteFrequencyPointA": 348564,
        "scs-SpecificCarrierList": [
          {
            "offsetToCarrier": 0,
            "subcarrierSpacing": "kHz15",
            "carrierBandwidth": 52
          }
        ]
      },
      "initialUplinkBWP": {
        "genericParameters": {
          "locationAndBandwidth": 14025,
          "subcarrierSpacing": "kHz15"
        },
        "rach-ConfigCommon": {
          {
            "rach-ConfigGeneric": {
              "prach-ConfigurationIndex": 16,
              "msg1-FDM": "one",
              "msg1-FrequencyStart": 3,
              "zeroCorrelationZoneConfig": 0,
              "preambleReceivedTargetPower": -100,
              "preambleTransMax": "n7",
              "powerRampingStep": "dB4",
              "ra-ResponseWindow": "sl10"
            },
            "ssb-perRACH-OccasionAndCB-PreamblesPerSSB": {
              "one": "n4"
            },
            "ra-ContentionResolutionTimer": "sf64",
            "prach-RootSequenceIndex": {
              "l839": 1
            },
            "restrictedSetConfig": "unrestrictedSet"
          }
        },
        "pusch-ConfigCommon": {
          {
            "pusch-TimeDomainAllocationList": [
              {
                "k2": 4,
                "mappingType": "typeA",
                "startSymbolAndLength": 27
              }
            ],
            "msg3-DeltaPreamble": 6,
            "p0-NominalWithGrant": -76
          }
        },
        "pucch-ConfigCommon": {
          {
            "pucch-ResourceCommon": 11,
            "pucch-GroupHopping": "neither",
            "p0-nominal": -90
          }
        }
      },
      "timeAlignmentTimerCommon": "infinity"
    },
    "n-TimingAdvanceOffset": "n25600",
    "ssb-PositionsInBurst": {
      "inOneGroup": "10000000"
    },
    "ssb-PeriodicityServingCell": "ms10",
    "ss-PBCH-BlockPower": -16
  },
  "ue-TimersAndConstants": {
    "t300": "ms1000",
    "t301": "ms1000",
    "t310": "ms1000",
    "n310": "n1",
    "t311": "ms3000",
    "n311": "n1",
    "t319": "ms1000"
  }
}
2024-02-03T17:56:46.955080 [DU-F1   ] [I] F1 Setup: Sending F1 Setup Request to CU-CP...
2024-02-03T17:56:46.955139 [DU-F1   ] [I] F1 Setup: Procedure completed successfully.
2024-02-03T17:56:46.955179 [SCHED   ] [I] [     0.0] cell=0: Cell configured successfully.
2024-02-03T17:56:46.961904 [DU-MNG  ] [I] DU manager started successfully.
2024-02-03T17:56:46.961906 [DU      ] [I] DU-High started successfully
2024-02-03T17:56:46.961908 [DU      ] [I] DU started successfully
2024-02-03T17:56:46.961908 [GNB     ] [I] Starting Radio Unit...
2024-02-03T17:56:46.961916 [GNB     ] [I] Radio Unit started successfully
2024-02-03T17:56:47.961916 [zmq:tx:0:0] [I] Waiting for request.
2024-02-03T17:56:47.961941 [zmq:rx:0:0] [I] Waiting for data.
2024-02-03T17:56:47.961944 [zmq:rx:0:0] [I] Waiting for reading samples. Completed 0 of 5760 samples.
2024-02-03T17:56:48.961916 [zmq:tx:0:0] [I] Waiting for request.
2024-02-03T17:56:48.961942 [zmq:rx:0:0] [I] Waiting for data.
2024-02-03T17:56:48.961947 [zmq:rx:0:0] [I] Waiting for reading samples. Completed 0 of 5760 samples.
2024-02-03T17:56:49.961917 [zmq:tx:0:0] [I] Waiting for request.

If someone could help me solve this problem I would appreciate it.

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions
Atached Scrips   **GNB**

 amf:
  addr: 127.0.0.5       #192.168.40.132 #10.10.1.2 #  10.53.1.1              # The address or hostname of the AMF.
  bind_addr: 127.0.0.5  #101.168.40.131 10.53.1.2      # A local IP that the gNB binds to for traffic from the AMF.

ru_sdr:
  device_driver: zmq                # The RF driver name.
  device_args: tx_port=tcp://127.0.0.1:2000,rx_port=tcp://127.0.0.1:2001,base_srate=11.52e6 # Optionally pass arguments to the selected RF driver.
  srate: 11.52                      # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 75                       # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 75                       # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 368500                  # ARFCN of the downlink carrier (center frequency).
  band: 3                           # The NR band.
  channel_bandwidth_MHz: 10         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                    # Subcarrier spacing in kHz used for data.
  plmn: "00101"                     # PLMN broadcasted by the gNB.
  tac: 7 #7                            # Tracking area code (needs to match the core configuration).
  pdcch:
    dedicated:
      ss2_type: common                                            # Set search space to common to match capabilities
      dci_format_0_1_and_1_1: false                               # Use fallback DCI to match srsUE capabilities
  prach:
    prach_config_index: 1                                         # Set PRACH config index to match srsUE expectation 

log:
  filename: /tmp/gnb.log            # Path of the log file.
  all_level: info                   # Logging level applied to all layers.
  hex_max_size: 0

pcap:
  mac_enable: false                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: false                # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.

**AMF SCRIPT**
logger:
  file: /var/log/open5gs/amf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

amf:
  sbi:
    server:
      - address: 127.0.0.5
        port: 7777
    client:
#      nrf:
#        - uri: http://127.0.0.10:7777
      scp:
        - uri: http://127.0.0.200:7777
  ngap:
    server:
      - address: 127.0.0.5  #192.168.40.5 #10.53.1.1 #10.10.0.5  #10.10.1.1  10.53.1.1
        
  metrics:
    server:
      - address: 127.0.0.5
        port: 9090
  guami:
    - plmn_id:
        mcc: 001    #999
        mnc: 01     #70
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: 001   #999
        mnc: 01    #70
      tac: 1  #7
  plmn_support:
    - plmn_id:
        mcc: 001   #999
        mnc: 01    #70
      s_nssai:
        - sst: 1
  security:
    integrity_order : [ NIA2, NIA1, NIA0 ]
    ciphering_order : [ NEA0, NEA1, NEA2 ]
  network_name:
    full: Open5GS
    short: Next
  amf_name: open5gs-amf0
  time:
#    t3502:
#      value: 720   # 12 minutes * 60 = 720 seconds
    t3512:
      value: 540    # 9 minutes * 60 = 540 seconds

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]
1. Run gnb  
2. Check log.gnb
3. Run ue 

[gnb.log](https://github.com/srsran/srsRAN_Project/files/14152628/gnb.log)
[ue.log](https://github.com/srsran/srsRAN_Project/files/14152629/ue.log)

## Additional Information ##
[upf.log](https://github.com/srsran/srsRAN_Project/files/14152640/upf.log)
[amf.log](https://github.com/srsran/srsRAN_Project/files/14152641/amf.log)

**Comment by pgawlowicz** [comment]
See here https://github.com/srsran/srsRAN_Project/discussions/414
