### ISSUE TITLE
COTS UE Cannot find the network

### ISSUE THREAD

**Issue by pricalinat** [srsran/srsRAN_Project#48]
Using the default configuration file, the network can be found in srsRAN_4G, but not in srsRAN_Project. The log is as follows.
[gnb.log](https://github.com/srsran/srsRAN_Project/files/11167569/gnb.log)
[pcap.zip](https://github.com/srsran/srsRAN_Project/files/11167571/pcap.zip)

**Comment by andrepuschmann** [comment]
Please send logs and configs and stdout for both cases

**Comment by pricalinat** [comment]
srsRAN_4G
![image](https://user-images.githubusercontent.com/52783243/230323190-ca88a453-a978-466a-aa47-34282eb0d233.png)
[enb_mac_nr.zip](https://github.com/srsran/srsRAN_Project/files/11168150/enb_mac_nr.zip)
[enb.log](https://github.com/srsran/srsRAN_Project/files/11168152/enb.log)
[conf.zip](https://github.com/srsran/srsRAN_Project/files/11168221/conf.zip)


srsRAN_Project
![image](https://user-images.githubusercontent.com/52783243/230324811-db183b40-9da0-4e4d-ba46-fd211f88af2d.png)
[gnb.log](https://github.com/srsran/srsRAN_Project/files/11168194/gnb.log)
[pcap2.zip](https://github.com/srsran/srsRAN_Project/files/11168199/pcap2.zip)
[gnb_rf_b200_tdd_n78_20mhz.zip](https://github.com/srsran/srsRAN_Project/files/11168219/gnb_rf_b200_tdd_n78_20mhz.zip)
