### ISSUE TITLE
Only ping possible between srsUE and srsGNB

### ISSUE THREAD

**Issue by oliverxsch** [srsran/srsRAN_Project#480]
## Issue Description ##
Hello,
this was my old Issue, but because this problem occured and the old problem did not persist, i opened this new isssue.
https://github.com/srsran/srsRAN_Project/issues/423

## Setup Details ##
Only ping from UE to gnb is possible. 
If i ping the UE from the gnb, the messages like in the screenshots happen.
Im using two X310s connected via SMA cable, both with their own host pc.
Using X410 as the gnb does not change the situation.
![Screenshot_55](https://github.com/srsran/srsRAN_Project/assets/29520143/3b7050f2-eb21-4b0c-99e0-06edc2fcdaa7)

Here are my configs and logs.:
[srsRan Github.zip](https://github.com/srsran/srsRAN_Project/files/14333220/srsRan.Github.zip)

## Additional Information ##
Please check my old issue: https://github.com/srsran/srsRAN_Project/issues/423
There are a lot of suggestions which we already tried.

Thanks in advance

**Comment by pgawlowicz** [comment]
Hi,
could you list all interfaces on your srsUE host?  You can use `ifconfig`

**Comment by oliverxsch** [comment]
> Hi, could you list all interfaces on your srsUE host? You can use `ifconfig`

Here:
![screenshot](https://github.com/srsran/srsRAN_Project/assets/29520143/22f58a3e-ca96-4681-aed5-54d2775607b0)

**Comment by pgawlowicz** [comment]
So there is no `tun_srsue` interface, the interface is created when srsUE attached and gets an IP address. Therefore, I believe it was not connected, or?

**Comment by oliverxsch** [comment]
No, it did not connect. Sorry, i did not start the gnb at the same time.
Here is a screen with the gNB running and connected. the interface is there.
![ue](https://github.com/srsran/srsRAN_Project/assets/29520143/33ea981e-6564-4dd7-99b9-06c466ff1a06)
![gnb](https://github.com/srsran/srsRAN_Project/assets/29520143/02db595b-ad6d-4543-9a91-8b43ee9bf30f)

**Comment by pgawlowicz** [comment]
could you print routing tables on both gnb and ue? 
could you try to ping the UE from Open5GS docker container?
```
docker exec -it open5gs_5gc ping 10.45.1.2
```

**Comment by oliverxsch** [comment]
> could you print routing tables on both gnb and ue? could you try to ping the UE from Open5GS docker container?
> 
> ```
> docker exec -it open5gs_5gc ping 10.45.1.2
> ```


Okay. Here are the routing tables for UE and gNB:
![gnbrouting](https://github.com/srsran/srsRAN_Project/assets/29520143/a20071f0-0053-4d8c-9eb1-cc3ed86c16cb)
![ue routing](https://github.com/srsran/srsRAN_Project/assets/29520143/398cb376-4528-4397-a5cc-cec0695c51d5)


And this is what happens if i use your command on the gnb to ping the UE:
![gnbpinguedocker](https://github.com/srsran/srsRAN_Project/assets/29520143/38bb86f0-fda0-44dc-a0de-b0d6fb4497a3)

**Comment by pgawlowicz** [comment]
could you make screenshots of console traces from gnb and ue?

**Comment by oliverxsch** [comment]
Now your command is working somehow.
But the iperfs commands provided in the tutorial do not work.
Thanks anyway!
I believe the tutorial got changed (to include the CN per docker) but the ping commands and iperf commands did not change?
How would i need to adjust the iperf command ?

**Comment by pgawlowicz** [comment]
If the routes are configured correctly, then the commands provided in the tutorial should work.

**Comment by oliverxsch** [comment]
Oh, i just found my problem.
I uses the command:
Next add default route for the UE (...) on the wrong machine xD

Thanks for your help

**Comment by pgawlowicz** [comment]
iperf server on gnb:
```
iperf3 -s -i 1
```

iperf client on srsUE:
```
iperf3 -c 10.53.1.1 -i 1 -t 60 -u -b 10M
```

So in your case the UE has no idea how to reach iperf server, as the default route is going somewhere else. 
You can start the client inside open5gs docker and then run `iperf3 -c 10.45.1.1 -i 1 -t 60 -u -b 10M`
