### ISSUE TITLE
over the air setup - GNB is not pinging the UE

### ISSUE THREAD

**Issue by Mohammed24699** [srsran/srsRAN_Project#489]
## Issue Description ##
I am trying to connect the UE and GNB (over the air setup). The UE can ping the GNB (10.45.1.1), but, the GNB is not pinging the UE. 

## Setup Details ##
computer 1 (UE) - intel xeon(R) w-2255 cpu @ 3.70 GHZ * 20
computer 2 (gnb) - 11 th gen intel core -19 11900k @ 3.50 GHZ * 16
 
We installed the latest UE( 23_11 )in one system and GNB in another system and connected the USRP (b210) to each PC. USRP's are connected with SMA cables attaching 20 dB attenuators, and the experiment is conducted in a low-latency kernel.

## Expected Behavior ##
According to the documentation (https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html), after the UE gives the IP address (10.45.1.2), we need to ping the UE and GNB each other.

## Actual Behaviour ##
There is no problem pinging GNB with UE. But GNB is not pinging the UE.

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue, e.g. RF setup, application config files]

## Additional Information ##
I'm performing the kernel in a low-latency kernel with the official config files (I'm attaching them below); take a look at the UE and GNB log files too.

[gnb.log.log](https://github.com/srsran/srsRAN_Project/files/14380292/gnb.log.log)

**Comment by pgawlowicz** [comment]
Hi, Did you configure the routing correctly?

**Comment by pgawlowicz** [comment]
what about the default route at ue?

**Comment by Mohammed24699** [comment]
![PXL_20240223_231219160](https://github.com/srsran/srsRAN_Project/assets/158986403/3c736732-7dd1-4ce3-9f14-6b70bb8bcfad)

**Comment by pgawlowicz** [comment]
you need to add the default gw:

```
sudo ip route add default via 10.45.1.1 dev tun_srsue
```

**Comment by Mohammed24699** [comment]
i ran this on UE, still GNB does not
![ping GNB](https://github.com/srsran/srsRAN_Project/assets/158986403/18d23c87-64e5-4965-92bd-5713c40f858e)
![tun_srsue](https://github.com/srsran/srsRAN_Project/assets/158986403/b73471dd-901b-4f0d-8aae-07b801810282)
 ping UE

**Comment by pgawlowicz** [comment]
the route on gnb is wrong, it should be 
```
10.45.0.0       10.53.1.2       255.255.0.0     UG    0      0        0 br-....
```

and you have:
```
10.45.0.0       10.53.1.2       255.255.255.0     UG    0      0        0 br-....
```

so you do not have a route for address 10.45.1.2

**Comment by Mohammed24699** [comment]
udo route change -net 10.45.0.0 netmask 255.255.0.0 dev br-6341da468396
Usage: route [-nNvee] [-FC] [<AF>]           List kernel routing tables
       route [-v] [-FC] {add|del|flush} ...  Modify routing table for AF.

       route {-h|--help} [<AF>]              Detailed usage syntax for specified AF.
       route {-V|--version}                  Display version/author and exit.

        -v, --verbose            be verbose
        -n, --numeric            don't resolve names
        -e, --extend             display other/more information
        -F, --fib                display Forwarding Information Base (default)
        -C, --cache              display routing cache instead of FIB

  <AF>=Use -4, -6, '-A <af>' or '--<af>'; default: inet
  List of possible address families (which support routing):
    inet (DARPA Internet) inet6 (IPv6) ax25 (AMPR AX.25) 
    netrom (AMPR NET/ROM) ipx (Novell IPX) ddp (Appletalk DDP) 
    x25 (CCITT X.25)

**Comment by Mohammed24699** [comment]
![gnb](https://github.com/srsran/srsRAN_Project/assets/158986403/d6229b92-2256-4ffd-80ae-96c69af66568)
![ue](https://github.com/srsran/srsRAN_Project/assets/158986403/3befd6f4-328f-4335-86cb-69509a1a5f68)

Still, the downlink doesn't ping.

**Comment by pgawlowicz** [comment]
The default route at srsue goes over eno1 but should go over tun_srsue

**Comment by Mohammed24699** [comment]
![ue](https://github.com/srsran/srsRAN_Project/assets/158986403/b8b23b9b-9e64-4530-8a02-175f99ad80f3)
changed it to default, still same problem

**Comment by pgawlowicz** [comment]
Does the ping from UE to core work? How do you ping from the core?

**Comment by Mohammed24699** [comment]
![Screenshot from 2024-02-25 17-30-23](https://github.com/srsran/srsRAN_Project/assets/158986403/fa071b85-41bc-427e-a3a1-b31f5062cefc)


![Screenshot from 2024-02-25 17-30-38](https://github.com/srsran/srsRAN_Project/assets/158986403/8e8ad360-22f0-48a1-b794-49f70d1e0b07)


1. Ping from UE to core works
2. I'm pinging UE from the docker container.

**Comment by pgawlowicz** [comment]
could you try to ping the UE from Open5GS docker container:
```
docker exec -it open5gs_5gc ping 10.45.1.2
```

**Comment by Mohammed24699** [comment]
![image](https://github.com/srsran/srsRAN_Project/assets/158986403/85b5c0cb-a48f-4268-b817-654350dd967d)

**Comment by Mohammed24699** [comment]
Hello, do you have any idea how I can make my UE more stable? Sometimes it gives the IP address, sometimes it doesn't.
I'm using the official config files. Do I need to make any changes to TX and RX gains?
![Screenshot from 2024-03-01 15-10-43](https://github.com/srsran/srsRAN_Project/assets/158986403/0516c8b6-0796-4146-abc1-61fe3d7a6aeb)
![Screenshot from 2024-03-01 15-10-54](https://github.com/srsran/srsRAN_Project/assets/158986403/f4b4b9d4-3cf1-4cf1-855a-85d1b1a62864)

**Comment by pgawlowicz** [comment]
Do you use external clock (or gpsdo clock) for your b210s?

**Comment by Mohammed24699** [comment]
yes we use CDA 2990 octo clock

**Comment by pgawlowicz** [comment]
could you provide the console trace from both gnb and srsUE when the UE is connected and sending a ping? you need to press `t` in both consoles.

**Comment by Mohammed24699** [comment]
![gnb trace 1](https://github.com/srsran/srsRAN_Project/assets/158986403/784edfa7-bdb9-485d-96e4-76284995dc95)
![gnb trace 2](https://github.com/srsran/srsRAN_Project/assets/158986403/29939a34-6912-45c7-ba14-a3f4b49ef4d9)
![ue trace 1](https://github.com/srsran/srsRAN_Project/assets/158986403/3425a621-b03d-48a5-bd92-f3a7284e2813)
![ue trace 2](https://github.com/srsran/srsRAN_Project/assets/158986403/deff24fb-da22-4358-84f4-02c92ebdd61f)

**Comment by pgawlowicz** [comment]
did you try tuning rx/tx gains on both gnb and srsUE?  I would start with reducing TX gain of gnb a (by 5-10db). Could you make a screenshort of the CPU load at srsUE host PC? eg. from `htop`

**Comment by pgawlowicz** [comment]
@Mohammed24699 did you solve the issue?

**Comment by Mohammed24699** [comment]
As you suggested, we tried tuning the tx and rx gains in the config files of both gNB and UE. Now that the UE provides the IP, it's quite stable. We're currently conducting an iperf3 test at 10 m/s, and we've had the UE stable for about 23 min. Thanks for the help.

**Comment by pgawlowicz** [comment]
Great! thanks for your feedback!

**Comment by Mohammed24699** [comment]
I am just wondering that can we connect 2 srs UEs to 1gNB(open 5gs) ??

**Comment by Mohammed24699** [comment]
I am just wondering that can we connect 2 srs UEs to 1gNB(open 5gs) ?? **over the air setup**

**Comment by Mohammed24699** [comment]
https://github.com/srsran/srsRAN_Project/issues/327

currently i am looking into this, i guess it will help. if you have any information related to this please let me know.

**Comment by pgawlowicz** [comment]
sure, you can connect 2 srsUEs, just need to assign different USIM parameters to each and also add them to Open5GS database. You can take the configs from here https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#multi-ue-emulation and change the RF section to use USRP.

**Comment by Mohammed24699** [comment]
i created a new issue here https://github.com/srsran/srsRAN_Project/issues/532.

**Comment by Mohammed24699** [comment]
Hello,

We are using two different GPS clocks by replacing the OctoClock. I have a question regarding the configuration: Do we need to change anything in the clock and sync section of the gNB and UE settings? Additionally, while connecting to the USRP B210, we are currently connecting the GPS clocks to the "REF IN" port. Is this correct, or should we be using the "GPS ANT" port instead?

Thanks,

**Comment by pgawlowicz** [comment]
You need to use "REF IN" port and use "external" clock source. The "GPS ANT" port is only or the internal GPSDO module of b210 (if installed).

**Comment by Mohammed24699** [comment]
That makes sense. thanks a lot.

**Comment by Mohammed24699** [comment]
Hello,

We have collected the IQ samples of srsRAN gNB and UE during their communication in various scenarios and are using the WaveJudge software to analyze the 5G metrics. However, we are unable to see all the messages in the software. To access the complete set of messages, we need the values of K_SSB, KOffset for PSS, PBCH, and SSS in the gNB configuration.

Any guidance or information you could provide on these values would be greatly appreciated.

Thank you for your assistance.


<img width="1280" alt="schedule" src="https://github.com/user-attachments/assets/1da897b9-1c9a-4610-b17e-a1469cac9865">

**Comment by pgawlowicz** [comment]
The question is not related to the original issue in this thread, which is closed. Please start a new thread. Please use the Discussion section.

**Comment by Mohammed24699** [comment]
Thanks for the recommendation.
