### ISSUE TITLE
Connecting modified srsRAN 21.10 (which is used by OAIC) to Grafana Dashboard

### ISSUE THREAD

**Issue by 1noufjaafar** [srsran/srsRAN_Project#494]
## Issue Description ##
I have installed srsRan 21.10 which is released by OAIC and I want to connect it to grafana dashboard to display the results, but I couldn't find any resources on how to apply this. 

Could you please advice?

Thanks

**Comment by pgawlowicz** [comment]
Hi, it is not possible OAIC uses our srsRAN_4G as a base, that is not integrated with the Grafana Dashboard. 
The integration is available only in srsRAN_Project (this repo).
