### ISSUE TITLE
O-RAN cannot connect with the xApp

### ISSUE THREAD

**Issue by panitsasi** [srsran/srsRAN_Project#495]
## Issue Description ##
O-RAN NearRT-RIC and xApp

I followed all the steps but the expected output is not same as yours. 

## Setup Details ##
I run the core network by following these commands: 
cd ./srsRAN_Project/docker
docker compose up --build 5gc
![PXL_20240304_211724493](https://github.com/srsran/srsRAN_Project/assets/70574362/57510b0d-93fd-4c64-b2b6-aab04aa91aba)

I run the NEAR RT-RIC with ./flexric/build/examples/ric/nearRT-RIC
and the output is looking the same
![PXL_20240304_212014268](https://github.com/srsran/srsRAN_Project/assets/70574362/97aca6c1-91f7-4c1e-9d6c-c6c19c83564d)

Then i run the gNB and the output look like this: 
![PXL_20240304_211911545 MP](https://github.com/srsran/srsRAN_Project/assets/70574362/36a4e488-4125-474b-81b3-a9126d248ed3)
The output of the NEAR-RT-RIC after starting the gNB is: 
![PXL_20240304_211830133](https://github.com/srsran/srsRAN_Project/assets/70574362/0b2804a7-4a71-417b-b32c-b6ff90f96041)

Then i start the UE and the output is: 

When i try to ping from UE to the core i am taking this error: 
![PXL_20240304_212540214](https://github.com/srsran/srsRAN_Project/assets/70574362/7551123e-489f-432c-bcba-051690e38599)

When i run the default xApp i am taking these errors (the return values are 0): 

![PXL_20240304_212632122](https://github.com/srsran/srsRAN_Project/assets/70574362/2775c37d-5e58-4730-88f3-16dee519f445)

Can you help me debugging with these issues ?

**Comment by yagoda** [comment]
Hi, you are missing a picture of the UE, did it attach well? have you set the network namespace in the ue.conf?

**Comment by panitsasi** [comment]
The picture with the UE: 

![PXL_20240305_143216802](https://github.com/srsran/srsRAN_Project/assets/70574362/5e7c3661-e18f-44b5-b83c-b0f1accfe1d5)

Yes, i have set it.

**Comment by pgawlowicz** [comment]
could you print routing table on your srsUE host? `route -n`

**Comment by panitsasi** [comment]
When i execute this command : 
sudo ip netns exec ue1 ping -i 0.1 10.45.1.1
the output is correct. After executing the following commands : 
sudo ip ro add 10.45.0.0/16 via 10.53.1.2
route -n
The output that i get is: 

![Screenshot from 2024-03-06 16-04-13](https://github.com/srsran/srsRAN_Project/assets/70574362/2bb4ae12-7853-4ffc-affd-691fdeaeabb6)

**Comment by pgawlowicz** [comment]
it seems that you have two versions of Open5gs on the machine, i.e., dockerized version and one installed from source, right?

Check this section: https://docs.srsran.com/projects/project/en/latest/tutorials/source/flexric/source/index.html#nd-open5gs-instance-installed-manually

**Comment by panitsasi** [comment]
Yes that's true. Instead of removing the dockerized version is there any way to run the 5G core network manually (if yes the commands are sudo systemctl start open5gs-hssd etc ...?) If i initiate the core network manually will i face the same errors ?

**Comment by pgawlowicz** [comment]
Of course, you can run the Open5gs manually. For this purpose, please follow this tutorial: https://open5gs.org/open5gs/docs/guide/01-quickstart/

You will also need to update the default Open5GS configs, to match the gNB config (or vice versa). You can find some hints here: https://docs.srsran.com/projects/project/en/latest/tutorials/source/cotsUE/source/index.html#id1

**Comment by pgawlowicz** [comment]
@panitsasi any update on this issue?
