### ISSUE TITLE
Cannot connect Over-the-air Setup

### ISSUE THREAD

**Issue by panitsasi** [srsran/srsRAN_Project#496]
Do you know why this error is popping up when i try to create the RF using a SDR (USRP B210)? 
![PXL_20240304_215121398](https://github.com/srsran/srsRAN_Project/assets/70574362/caddf6a2-b189-4775-b225-5a12d538a482)

**Comment by pgawlowicz** [comment]
the external clock cannot be locked. If you are using GPSDO you need to put the antenna outside

**Comment by pgawlowicz** [comment]
Then you should change the gnb config to use internal clock and time source. Note that the clock inside b200 is not very good and there might be issues when trying to connect a UE to the gnb, when running with b210 without external clock.

**Comment by panitsasi** [comment]
I changed the gnb and ue configuration files and here is the output. 

The core network is running

![PXL_20240305_141737653](https://github.com/srsran/srsRAN_Project/assets/70574362/ef38a516-5cd3-43ff-9a26-14a5472c2340)

The gnb integrated with the USRP is running

![PXL_20240305_141747910](https://github.com/srsran/srsRAN_Project/assets/70574362/7ccebba9-2c2e-43c5-b862-5520356f894e)

The configuration file of the gnb is this: 
![PXL_20240305_141907954](https://github.com/srsran/srsRAN_Project/assets/70574362/524b6cc0-4c89-432a-b459-32aed639a929)

While i try to connect a UE: 

![PXL_20240305_141759775](https://github.com/srsran/srsRAN_Project/assets/70574362/2a74c76f-0224-44a2-bc60-e7626beeebc5)


Where the configuration file is: 

![PXL_20240305_141918244](https://github.com/srsran/srsRAN_Project/assets/70574362/8d731686-63a5-4451-af45-30f48560dfa4)


The UE cannot connect to the gNB. Is this happening because i do not use an external clock?

**Comment by pgawlowicz** [comment]
could you run `uhd_find_devices` on the srsUE host PC?

**Comment by panitsasi** [comment]
Yes, I can. 

![Screenshot from 2024-03-06 16-07-09](https://github.com/srsran/srsRAN_Project/assets/70574362/814b72db-414e-4b54-a224-fe5c8d3dc1dd)

**Comment by robertfalkenberg** [comment]
If you run both, gNB and UE, on the same computer, you will also need two USRPs: one for gNB and one for UE.
(However, we recommend to run on separate computers)

**Comment by pgawlowicz** [comment]
@panitsasi any update on this issue?
