### ISSUE TITLE
Generate Downlink traffic

### ISSUE THREAD

**Issue by mas-oliveira** [srsran/srsRAN_Project#497]
## Issue Description ##
While trying to generate downlink traffic between gNB and UE the grafana UI doesn't indicate any changes in the downlink bitrate.

## Setup Details ##
https://docs.srsran.com/projects/project/en/latest/tutorials/source/flexric/source/index.html
https://docs.srsran.com/projects/project/en/latest/user_manuals/source/grafana_gui.html
I just followed everything that is here, I have everything running locally and grafana and 5gc with docker-composer

## Expected Behavior ##
A relevant downlink bitrate.

## Actual Behaviour ##
![Screenshot from 2024-03-05 12-47-15](https://github.com/srsran/srsRAN_Project/assets/62846180/da0403f2-fc32-4f64-a902-60cd5bbb45ee)
![Screenshot from 2024-03-05 12-48-16](https://github.com/srsran/srsRAN_Project/assets/62846180/40723daa-f23f-493f-a76f-4582fa919dad)
It looks like that I'm generating some data, when I try to direct connect to the core IP: 10.53.1.1 I have the following error
marco@marco-NUC7i7BNH:~/srsRAN_4G/build/srsue/src$ sudo ip netns exec ue1 iperf3 -c 10.53.1.1 -i 1 -t 60 -u -b 10M
iperf3: error - unable to send control message: Bad file descriptor

This is my routing table on the ue1 namespace
marco@marco-NUC7i7BNH:~/srsRAN_4G/build/srsue/src$ sudo ip netns exec ue1 route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.45.1.1       0.0.0.0         UG    0      0        0 tun_srsue
10.45.1.0       0.0.0.0         255.255.255.0   U     0      0        0 tun_srsue

And this is my routing table locally
marco@marco-NUC7i7BNH:~/srsRAN_4G/build/srsue/src$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.3.10.1       0.0.0.0         UG    600    0        0 wlp58s0
10.45.0.0       10.53.1.2       255.255.0.0     UG    0      0        0 br-26141c6f72a5
10.53.1.0       0.0.0.0         255.255.255.0   U     0      0        0 br-26141c6f72a5

Regards,
Marco

**Comment by pgawlowicz** [comment]
This traffic goes directly from your host ("Internet") to Ope5gs Docker container (core network),  without passing the (emulated) wireless link. 

1. If you start the iperf server inside the Open5gs container, the client should use:
```
sudo ip netns exec ue1 iperf3 -c 10.45.1.1 -i 1 -t 60 -u -b 10M
```

2. If you start the iperf server on your local host, the client should use:
```
sudo ip netns exec ue1 iperf3 -c 10.53.1.1 -i 1 -t 60 -u -b 10M
```
In this case, the routing from host to UEs over Open5gs container (you have it already):
```
sudo ip ro add 10.45.0.0/16 via 10.53.1.2
```

**Comment by mas-oliveira** [comment]
But when I start the iperf3 server inside the Open5gs container the traffic generated will be at uplink (running this on the local host: sudo ip netns exec ue1 iperf3 -c 10.45.1.1 -i 1 -t 60 -u -b 10M) 

![image](https://github.com/srsran/srsRAN_Project/assets/62846180/816c5748-6d67-4b6f-9f6c-f5abec26cddf)

There is not a way to make the iperf to generate downlink traffic?
