### ISSUE TITLE
Error: Buffer pool is empty

### ISSUE THREAD

**Issue by uptools** [srsran/srsRAN_Project#509]
## Issue Description ##
  A few seconds after srsenb we get the following errors (repeatedly):
  **Error - buffer pool is empty**
  
  ## Setup Details ##
  srsepc is running on another computer
  srsenb is running on a 32 bit arm/neon with 2 cores and 1gb ram, and it is correctly initializing the Soapy driver and connecting to sdr with only 1 port. srsenb is configured for only 6 prb's.
  srsenb is compiled in "Release" version
  
  We found that the error comes when srsenb is not deallocating and returning buffers fast enough to the buffer pool.
  We tried recompiling with SRSRAN_MAX_PORTS set to 1 to decrease mem usage, but the same error occurs.
  
  Is this caused by slow processing? or by not having enough memory? Or srsenb cannot run on arm32/neon ?

**Comment by pgawlowicz** [comment]
do you work with the srsENB from the srsRAN-4G project?
If yes, you might try to reduce `nof_prealloc_ues` in the enb.conf file. 
https://github.com/srsran/srsRAN_4G/blob/master/srsenb/enb.conf.example#L451

How many UEs do you want to serve? what is the bandwidth?

**Comment by uptools** [comment]
We worked it from srsENB_4G project.
We tried reducing nof_prealloc_ues from 8 to 2. and the same error arises.
We also tried reducing nof_phy_threads from 3 to 1 and the error stays the same.

The bandwidth is only 180KHz x 6 = 1080KHz (as we are using 6 prb's).

**Comment by pgawlowicz** [comment]
could you check the memory load? with htop?

**Comment by uptools** [comment]
The "buffer pool is empty" error starts when the srsenb allocation reaches approximately 410MB, even though there is still available mem.

![htop1](https://github.com/srsran/srsRAN_Project/assets/18288874/929db730-8057-43be-9601-c76033044496)
![htop 2](https://github.com/srsran/srsRAN_Project/assets/18288874/e6e57084-1951-4dd6-8bc4-4a3a3ccda325)

**Comment by pgawlowicz** [comment]
@frankist could you comment here?

**Comment by pgawlowicz** [comment]
@uptools any update on this issue?
