### ISSUE TITLE
compute_pdcch_code_rate  error(lib\scheduler\support\pdcch_aggregation_level_calculator.cpp)

### ISSUE THREAD

**Issue by lpg-delete** [srsran/srsRAN_Project#512]
## Issue Description ##
static double compute_pdcch_code_rate(unsigned nof_dci_bits, aggregation_level lvl)
{
  static const unsigned pdcch_crc_bits            = 24U;
  static const unsigned nof_bits_per_symbols_qpsk = 2U;
  return ((double)nof_dci_bits + pdcch_crc_bits) /
         **(double)(pdcch_constants::NOF_REG_PER_CCE * NRE * nof_bits_per_symbols_qpsk * to_nof_cces(lvl));**
}
The pdcch dmrs re needs to be removed.

## Expected Behavior ##
static double compute_pdcch_code_rate(unsigned nof_dci_bits, aggregation_level lvl)
{
  static const unsigned pdcch_crc_bits            = 24U;
  static const unsigned nof_bits_per_symbols_qpsk = 2U;
  return ((double)nof_dci_bits + pdcch_crc_bits) /
         **(double) (pdcch_constants::NOF_BITS_PER_CCE * to_nof_cces(lvl)));**
}

**Comment by herlesupreeth** [comment]
Hey @lpg-delete , thanks for letting us know. The fix will be available in the next release.
