### ISSUE TITLE
 Enable Reporting from Neighbor gNBs

### ISSUE THREAD

**Issue by RabihND** [srsran/srsRAN_Project#536]
### Description
I am conducting research involving scenarios with one UE and multiple gNBs in the srsRAN project. Currently, the logging code supports metrics retrieval only from the serving gNB for a UE. I am interested in exploring the possibility of modifying the code to enable the neighbor gNB to also retrieve metrics for the UE.
### Requested Guidance
I am seeking guidance on how to modify the srsRAN code to enable reporting from neighbor gNBs for scenarios involving one UE and multiple gNBs. Specifically, I am interested in modifying the gNB process to achieve this goal. Any pointers or suggestions on how to approach this modification would be greatly appreciated.

### Research Goal
My research aims to retrieve metrics such as RSRP, RSRQ, channel impulse response, etc., simultaneously from two gNBs located at different locations to the same UE.

**Comment by pgawlowicz** [comment]
hi @RabihND, it is not an issue, please move to the discussions section.
