### ISSUE TITLE
srsGNB ERROR: Failed to create SCTP gateway. #1

### ISSUE THREAD

**Issue by rsjamwal** [srsran/srsRAN_Project#552]
## Issue Description ##
Not able to connect srsGNB to free5gc Core deployed on k8 cluster

## Setup Details ##
k8 running on Ubuntu 20.04.6 LTS
kernel version: 5.4.0-162-generic
CONTAINER-RUNTIME: containerd://1.7.13
K8 version: v1.28.8

root@k8-master:~/cu-du# k logs -n 5g srsran-project-cudu-chart-68f4f6c99c-l8l42

The PRACH detector will not meet the performance requirements with the configuration {Format 0, ZCZ 0, SCS 1.25kHz, Rx ports 1}.

--== srsRAN gNB (commit 55c984b55) ==--

Failed to bind SCTP socket to 192.168.5.4:0. Success
srsGNB ERROR: Failed to create SCTP gateway.

Any idea what is going on ?

## Expected Behavior ##
srsRAN gNB  get connected with 5g Core

## Actual Behaviour ##
srsRAN gNB  get connected with 5g Core

![Screenshot_1](https://github.com/srsran/srsRAN_Project/assets/57722567/d372148b-79dd-4709-84ac-e7689e9d9db2)

**Comment by pgawlowicz** [comment]
could you share your configs?
