### ISSUE TITLE
run SrsRan with SrsUE on buildroot

### ISSUE THREAD

**Issue by shirinebadi** [srsran/srsRAN_Project#556]
Hi!
I'm trying to run SrsRan project connected to SrsUE as explained [here](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html) on qemu v8 via buildroot. As you know buildroot is very lightweight and needs so many packages to be installed manually. So, I want to know if it is even possible to run srsRan on buildroot?

**Comment by pgawlowicz** [comment]
this is not an issue, please start a new discussion thread.
