### ISSUE TITLE
Intra-eNB & S1 Handover

### ISSUE THREAD

**Issue by Mohammed24699** [srsran/srsRAN_Project#557]
## Setup Details ##
with the help of this https://docs.srsran.com/projects/4g/en/hoverxref_test/app_notes/source/handover/source/index.html documentation we followed everything.

## Expected Behavior ##
![Screenshot from 2024-04-16 21-31-14](https://github.com/srsran/srsRAN_Project/assets/158986403/7c706027-6934-47a0-b498-db99048136bc)

## Actual Behaviour ##
![Screenshot from 2024-04-16 21-32-45](https://github.com/srsran/srsRAN_Project/assets/158986403/75783a07-ea86-4db2-94f7-7d554f7dd176)

## Steps to reproduce the problem ##
By seeing the error can someone please tell me what the problem is ??

## Additional Information ##
Attaching enb.conf and rr.conf files.

[enb conf. txt](https://github.com/srsran/srsRAN_Project/files/15004814/enb.conf.txt)
[rr conf.txt](https://github.com/srsran/srsRAN_Project/files/15004816/rr.conf.txt)

**Comment by pgawlowicz** [comment]
you need to put your configs to `/root/.config/srsran/` or start with `sudo srsenb ./enb.conf`

**Comment by Mohammed24699** [comment]
![Screenshot from 2024-04-17 11-45-37](https://github.com/srsran/srsRAN_Project/assets/158986403/1fb13f92-aadf-464c-8286-5216deb576fb)

**Comment by pgawlowicz** [comment]
`sudo srsue ./ue.conf --rat......`

**Comment by Mohammed24699** [comment]
![Screenshot from 2024-04-17 12-12-50](https://github.com/srsran/srsRAN_Project/assets/158986403/cf9feb01-5025-4e93-80e6-d6e242423b4d)

Do I need to change anything in the ue config file ??
![Screenshot from 2024-04-17 12-15-52](https://github.com/srsran/srsRAN_Project/assets/158986403/8b957699-b6e3-41ff-ab6c-72ea1e387923)

**Comment by Mohammed24699** [comment]
I make the line 27 as comment. I think it worked. Let me know if I am doing it in the right way.

**Comment by pgawlowicz** [comment]
There was a change in the config structure. 

For the ZMQ-based setup, it does not matter, you can comment out this parameter. 

But if you want to run over usrp, you need to set it with `rat.eutra.dl_earfcn` (check here : https://github.com/srsran/srsRAN_4G/blob/master/srsue/src/main.cc#L130), so that the TX/RX freq are set correctly.

**Comment by Mohammed24699** [comment]
I want to use usrp in future.
I checked that config files of rnb, rr, enb and they are same as the documentation. I am still getting the error. How can I solve it.
![image](https://github.com/srsran/srsRAN_Project/assets/158986403/6ad79231-13fc-478b-a870-ed3cc2c53112)

**Comment by pgawlowicz** [comment]
Did you comment out the dl_earfcn line in the config file?

**Comment by Mohammed24699** [comment]
It worked when I comment out the dl_earfcn line.

**Comment by Mohammed24699** [comment]
I can do the intra handover without any issue.

**Comment by pgawlowicz** [comment]
We will update the configs in the tutorial

**Comment by Mohammed24699** [comment]
Hi, I'm trying s1 handover now and I'm facing issues. Let me tell you the step by step process what i did so that you can correct me where i went wrong.

1. Changed the tac value to 7 in mme.yaml file of open 5gc. 
![Screenshot from 2024-04-24 16-42-28](https://github.com/srsran/srsRAN_Project/assets/158986403/bf624c42-1339-41cd-8436-996c4fd6fa9d)

2. Added subscriber to the network 
![Screenshot from 2024-04-24 16-44-14](https://github.com/srsran/srsRAN_Project/assets/158986403/870bc547-95f7-4bbd-91e0-76f384bbfac2)

3. added usim credentials to the ue config file 
![Screenshot from 2024-04-24 16-48-04](https://github.com/srsran/srsRAN_Project/assets/158986403/4e95c121-cf85-449a-86ce-8e0ea53a9b46)
![Screenshot from 2024-04-24 16-47-44](https://github.com/srsran/srsRAN_Project/assets/158986403/658a872b-0c4e-4cf9-ab0f-4f10ba9095bb)
4. changed mme address in enb config file. 
![Screenshot from 2024-04-24 16-52-54](https://github.com/srsran/srsRAN_Project/assets/158986403/f88495dd-d87e-4e98-a6e9-486e0c8e6554)
5. changed rr1 and rr2 config files according to the documentation.
6. Attached the bash scripts to the config files of enb1, enb2 and UE
7. Initiated eNB. But got errors 
![Screenshot from 2024-04-24 16-58-59](https://github.com/srsran/srsRAN_Project/assets/158986403/f71fafe3-033a-4ba3-837a-66991658568d)

Attaching the config files here
[enb.txt](https://github.com/srsran/srsRAN_Project/files/15101421/enb.txt)
[enb1.txt](https://github.com/srsran/srsRAN_Project/files/15101422/enb1.txt)
[enb2.txt](https://github.com/srsran/srsRAN_Project/files/15101424/enb2.txt)
[rr1.txt](https://github.com/srsran/srsRAN_Project/files/15101426/rr1.txt)
[rr2.txt](https://github.com/srsran/srsRAN_Project/files/15101427/rr2.txt)

**Comment by pgawlowicz** [comment]
you should remove (or comment out) this part in your configs:
```
LOG_ARGS="--log.all_level=debug"

PORT_ARGS="tx_port=tcp://*:2101,rx_port=tcp://localhost:2100"
ZMQ_ARGS="--rf.device_name=zmq --rf.device_args=\"${PORT_ARGS},id=enb,base_srate=23.04e6\""

OTHER_ARGS="--enb_files.rr_config=rr1.conf"

sudo srsenb enb.conf ${LOG_ARGS} ${ZMQ_ARGS} ${OTHER_ARGS} $@
```

**Comment by Mohammed24699** [comment]
I couldn't able to open two eNB's in the same time. I tried changng the port numbers in the eNB config files but it showing this error.
![Screenshot from 2024-04-25 16-03-42](https://github.com/srsran/srsRAN_Project/assets/158986403/5428201e-3c67-4bbf-9572-eadd57c53f8b)


but the eNB1 is started.
![Screenshot from 2024-04-25 16-00-33](https://github.com/srsran/srsRAN_Project/assets/158986403/178dd387-6046-4126-a95e-6ec37aac40b4)

**Comment by Mohammed24699** [comment]
here I'm attaching the config files
[enb1.txt](https://github.com/srsran/srsRAN_Project/files/15121966/enb1.txt)
[enb2.txt](https://github.com/srsran/srsRAN_Project/files/15121967/enb2.txt)

**Comment by pgawlowicz** [comment]
you cannot use the same zmq ports in the two enb, and there is no sib anr rr configs in your working directory.

**Comment by Mohammed24699** [comment]
what should i do to use another zmq port to the second enb ??

**Comment by Mohammed24699** [comment]
I figured it out that we need to run the bash file first. Now, UE is not connecting to rrc.
![Screenshot from 2024-04-25 19-18-12](https://github.com/srsran/srsRAN_Project/assets/158986403/45fc2625-c6e0-4b15-9918-d289de5c93f6)
![Screenshot from 2024-04-25 19-19-36](https://github.com/srsran/srsRAN_Project/assets/158986403/d3cc776d-953a-44ad-b858-d6378e97f97c)
![Screenshot from 2024-04-25 19-20-43](https://github.com/srsran/srsRAN_Project/assets/158986403/e3b5df9a-3fe2-4b02-b8f4-f408221df1a2)

**Comment by pgawlowicz** [comment]
could you share open5gs config and logs?

**Comment by Mohammed24699** [comment]
[config.tar.gz](https://github.com/srsran/srsRAN_Project/files/15143528/config.tar.gz)
[log.tar.gz](https://github.com/srsran/srsRAN_Project/files/15143529/log.tar.gz)

please have a look

**Comment by pgawlowicz** [comment]
in MME logs you have:
```
04/23 14:51:15.334: [mme] INFO: [Added] Number of eNBs is now 1 (../src/mme/mme-context.c:2829)
04/23 14:51:15.334: [mme] INFO: eNB-S1[127.0.1.1] max_num_of_ostreams : 30 (../src/mme/mme-sm.c:150)
04/23 14:51:15.335: [mme] WARNING: S1-Setup failure: (../src/mme/s1ap-handler.c:234)
04/23 14:51:15.335: [mme] WARNING:     Cannot find Served TAI. Check 'mme.tai' configuration (../src/mme/s1ap-handler.c:235)
04/23 14:51:15.336: [mme] INFO: eNB-S1[127.0.1.1] connection refused!!! (../src/mme/mme-sm.c:166)
04/23 14:51:15.336: [mme] INFO: [Removed] Number of eNBs is now 0 (../src/mme/mme-context.c:2863)
```

So there is TAI mismatch between enb and open5gs configs.

**Comment by Mohammed24699** [comment]
hello,
we are doing s1 handover in another computer but we are facing some issues.

![Screenshot from 2024-06-07 18-06-21](https://github.com/srsran/srsRAN_Project/assets/158986403/17628956-bbef-4f7c-86aa-e017d2a269b0)

"epc.conf" file is also in the same directory.

your help will be appriciated. Thanks.

**Comment by Mohammed24699** [comment]
attaching the file epc config file here : 
[epc.txt](https://github.com/user-attachments/files/15755393/epc.txt)

**Comment by pgawlowicz** [comment]
hmm, can you try with an absolute path to the config file?

**Comment by Mohammed24699** [comment]
while I'm initiating the enb's , I got the error saying "S1 Setup Failure. Cause: misc - unknown-PLMN"
Here are the screenshots
![Screenshot from 2024-06-20 12-14-15](https://github.com/srsran/srsRAN_Project/assets/158986403/74ffc383-3005-45c4-8094-486213876c45)
![Screenshot from 2024-06-20 12-14-35](https://github.com/srsran/srsRAN_Project/assets/158986403/2902749a-9d8d-42e0-a05f-1ebdd8df1c23)

And I also crosschecked the PLMN in the ue config file and the localhost:9999, it's the same 90170

**Comment by pgawlowicz** [comment]
It seems that the PLMN used by enb and EPC is different.

**Comment by Mohammed24699** [comment]
[mme.txt](https://github.com/user-attachments/files/15917703/mme.txt)
[enb.txt](https://github.com/user-attachments/files/15917704/enb.txt)
I changed them in mme and gnb config file manually. Do i need to change ny where else?

**Comment by pgawlowicz** [comment]
`tac` parameter is also in `rr.conf` file in `cell_list` section.

**Comment by Mohammed24699** [comment]
Hello,

Howcan we do s1 handover in 5G. where can i find the confile file of gnb for s1 handover.

**Comment by Mohammed24699** [comment]
Hello,
How can we do s1 handover in 5G. where can i find the configuration file of gnb for s1 handover.
