### ISSUE TITLE
S1 handover

### ISSUE THREAD

**Issue by Mohammed24699** [srsran/srsRAN_Project#579]
can you please have a look and let me know where i went wrong.

https://github.com/srsran/srsRAN_Project/issues/557#issuecomment-2075957029

**Comment by pgawlowicz** [comment]
done

**Comment by Mohammed24699** [comment]
hello, i was doing the iperf3 test in both uplink and downlink with 5 Mb/sec and i observed a 50% packet loss. is that normal ?? if not how can i improve the performance. Thanks in advance.

![IPERF](https://github.com/user-attachments/assets/86917bf9-34e8-4310-b96d-570b473be4d2)
