### ISSUE TITLE
Error with SCTP Socket on ARM64 Build 

### ISSUE THREAD

**Issue by theundyingphoenix** [srsran/srsRAN_Project#58]
## Question ##
1. Is there a procedure to build srsRAN_Project source code for ARM64?
2. Does the srsRAN_Project's "gnb" use the sctp.ko file instead of the .so files?
    i. What is the cause of this issue?

## Issue Description ##
When running srsRAN_Project "gnb" executable, the following error is produced:
"Failed to create SCTP socket: {}. Hint: Please ensure 'sctp' kernel module is available on the system."

## Setup Details ##
1. Connect Xilinx ARM64 board to laptop (for access to the board via SSH).
4. SSH into the board and run the "gnb" executable with the TDD default configuration in srsRAN_Project's "configs" directory.
5. Error is output.

## Expected Behavior ##
A session starting on the USRP b205-mini and showing the output of a correct setup with the RF device.

## Actual Behaviour ##
"gnb" program outputs the following:
"Failed to create SCTP socket: {}. Hint: Please ensure 'sctp' kernel module is available on the system."

## Steps to reproduce the problem ##
/path/to/srsRAN_Project/apps/gnb/gnb -c /path/to/srsRAN_Project/configs/gnb_rf_b200_tdd_n78_20mhz.yml

**Comment by andrepuschmann** [comment]
This is a not an srsRAN issue but something that your board support package should cater for. Have you checked the SCTP kernel module is loaded or the module is built into the kernel as the error message indicates?

**Comment by theundyingphoenix** [comment]
I checked and it is not present on my board's kernel. Does this mean my board's support package build needs to build the sctp.ko file and be loaded using "modprobe" or "insmod" prior to running "gnb" executable?

**Comment by theundyingphoenix** [comment]
@jao-tm for an ARM64, not yet. However, I'm in the process of using buildroot framework to do so.

**Comment by jao-tm** [comment]
OK, I'm trying to build on a Raspberry Pi as I saw on Twitter that @andrepuschmann did that

**Comment by robertfalkenberg** [comment]
Don't forget to also install
```
sudo apt-get install linux-modules-extra-raspi
```
to get the SCTP kernel module.

**Comment by jao-tm** [comment]
Great, will try that. Thanks!

**Comment by shirinebadi** [comment]
hi @theundyingphoenix. I'm also trying to run srsran project on buildroot. Could you make any progress?
