### ISSUE TITLE
Error while installing libzmq

### ISSUE THREAD

**Issue by panitsasi** [srsran/srsRAN_Project#585]
while i was trying to download the libzmq following these commands:
 git clone https://github.com/zeromq/libzmq.git
cd libzmq
./autogen.sh
./configure
make
this issue came up (while executing the command make): 
![image](https://github.com/srsran/srsRAN_Project/assets/70574362/432c1de1-40ed-4808-82ba-c77545502b95)

Do you have an idea, what is the issue here ?

**Comment by pgawlowicz** [comment]
did you try to install with `sudo apt-get install libzmq3-dev` ?

**Comment by panitsasi** [comment]
Yes, i followed these instructions: 
![image](https://github.com/srsran/srsRAN_Project/assets/70574362/9f858a66-2809-44f6-a473-6da8ad157ce0)
and the issue persists.

**Comment by pgawlowicz** [comment]
which OS do you use?

**Comment by panitsasi** [comment]
Ubuntu 22.04.1 LTS

**Comment by panitsasi** [comment]
no, i tried to re install the package, but again i had the same issue.

**Comment by pgawlowicz** [comment]
could you check if you can install in a docker container?

1. Start docker container with ubuntu 22.04:
```
docker run -it ubuntu:22.04 /bin/bash
```
2. Then inside the container install zmq:
```
apt update
apt-get install libzmq3-dev
```

**Comment by panitsasi** [comment]
Yes,  i can install in a docker container, but do you know why is this happening ? I had installed in the past, but as i remember i deleted it. Is this is a reason to consider ?

**Comment by panitsasi** [comment]
Okay, I reinstall all the packages from the beginning and now everything works fine.

**Comment by abcd11abcd** [comment]
im also facing the same issue. How did you resolve? i tried removing libzmq3-dev and installing again. Still im facing the same problem. You resolved it by using docker container?

**Comment by panitsasi** [comment]
Hello, i removed all the installed libraries (and the dependencies) and then it worked.

**Comment by burnbrigther** [comment]
> Hello, i removed all the installed libraries (and the dependencies) and then it worked.
Which libraries did you have to remove?  I continue to struggle with this.  Thanks
