### ISSUE TITLE
ORAN cannot connect a UE

### ISSUE THREAD

**Issue by panitsasi** [srsran/srsRAN_Project#594]
## Issue Description ##
I have two issues while trying to connect a UE to the ORAN environment. 
Firstly, i think i have an issue while trying to start the core network using docker. This is the error messages that i take: 
![image](https://github.com/srsran/srsRAN_Project/assets/70574362/c02fbbbe-9898-4953-ad42-9336ffe296da)

I wonder if this happens maybe because the core network is running (manually) in the same port ? How can i check if the core network is running/ how can stop/start it manually without docker? 

Secondly, i changed the gNB configuration file. The AMF address was set to 127.0.0.5 as i did it when deploying a 5G network with simulated UE. Do i need to change it ? 

Finally, can i connect a COTS UE to this experiment and collect data using the E2SM-KPM service model?

**Comment by pgawlowicz** [comment]
if you want to use the dockerized version of Open5gs, please follow this tutorial: https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html
