### ISSUE TITLE
UE Fales to attach to the 5G Network

### ISSUE THREAD

**Issue by Moussa-Guemdani** [srsran/srsRAN_Project#612]
## Issue Description ##
Hello,
I have built the End-To-End 5G Network following the tutorial ""https://docs.srsran.com/projects/project/en/latest/tutorials/source/cotsUE/source/index.html"", but I'm still unable to attach the UE.

## Setup Details ##
# Hardware: - RF:USRPx310.
                    - Ubuntu 24.04.04.
                    - Computer: Dell i7 OptiPlex 7060.
                    - UE: OnePlus8Pro (supports n78 SA).
                    - sysmoISIM-SJA2
# Configs:
                    - amf:
                        - addr: 127.0.0.5                                             
                        - bind_addr: 127.0.0.1                                    

                    - ru_sdr:
                        - device_driver: uhd                                            
                        - device_args: type=x300                                        
                        - clock: internal                                           
                        - sync: default                                                       
                        - srate: 23.04
                        - tx_gain: 23
                        - rx_gain: 20
                    - cell_cfg:
                        - dl_arfcn: 627340
                        - #627340
                        - band: 78
                        - channel_bandwidth_MHz: 20
                        - common_scs: 30
                        - plmn: "20870"
                        - tac: 1
                        - pci: 1 

- 5G core: open5Gs        

## Actual Behaviour ##
![image](https://github.com/srsran/srsRAN_Project/assets/61354367/008e764c-4f06-42c9-8fbb-98b9e0cf95b0)
![image](https://github.com/srsran/srsRAN_Project/assets/61354367/16a0ce2d-2062-4b8f-a9f5-daa6a3d40336)

**Comment by pgawlowicz** [comment]
did you run this script on the gnb PC? https://github.com/srsran/srsRAN_Project/blob/main/scripts/srsran_performance

Also, could you share the details of the PC? (cpu, ram?)

**Comment by Moussa-Guemdani** [comment]
Hello,
I have ran the script, but stil the same issue,

12 x CPU: 
             - cpu family	: 6
             - model		: 158
             - model name	: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
             - stepping	: 10
             - microcode	: 0xf4
             - cpu MHz		: 800.039
             - cache size	: 12288 KB
             - physical id	: 0
             - siblings	: 12
             
RAM(MB): 
                            total        used       free             shared      buff/cache     available
      Mem:            15Gi       5,1Gi       6,6Gi           269Mi          3,7Gi            9,7Gi
       Swap:          2,0Gi          0B       2,0Gi

**Comment by pgawlowicz** [comment]
could you share the configs you use?

**Comment by Moussa-Guemdani** [comment]
Here you are:
![image](https://github.com/srsran/srsRAN_Project/assets/61354367/43f154f4-d0f2-43a5-af74-bceee7301db3)

**Comment by pgawlowicz** [comment]
could you check whether this works? 
https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#usrp-x300-x310

**Comment by Moussa-Guemdani** [comment]
These are the results after the changes
![image](https://github.com/srsran/srsRAN_Project/assets/61354367/83012a15-a527-4973-850e-ea2411859629)

Configs: 
![image](https://github.com/srsran/srsRAN_Project/assets/61354367/558619c0-33cd-4942-9a37-261547af4765)

**Comment by pgawlowicz** [comment]
how is the x310 connected to the gnb PC?

**Comment by Moussa-Guemdani** [comment]
It is connected using the 10 Gigabit Ethernet  via SFP cable
![image](https://github.com/srsran/srsRAN_Project/assets/61354367/996f90bb-0836-4c7a-9711-64e9bb5c4b16)

**Comment by Moussa-Guemdani** [comment]
Hello, When I Try the use another version of uhd, and  run the gnb, I asks me to download another version of uhd that is compatible with srsRAN_Project, Then when I do this and follow the steps, still have the same issue

![image](https://github.com/srsran/srsRAN_Project/assets/61354367/130522ee-a5ed-4768-a675-7408214c3499)

**Comment by Moussa-Guemdani** [comment]
![image](https://github.com/srsran/srsRAN_Project/assets/61354367/1d4495d3-2aa0-49de-8de0-0f41dc7c1b56)

**Comment by pgawlowicz** [comment]
Could you try uhd-4.3 or higher?

**Comment by Moussa-Guemdani** [comment]
Hello, after successfully using the project for several days, now the Ue Connects normally, but there is an exclamation mark on the network, and there is no internet access!

I have checked the nat and forwarding rules, 

![image](https://github.com/srsran/srsRAN_Project/assets/61354367/545f6112-c416-4cdc-b1ae-52f5ed1d7663)

**Comment by Moussa-Guemdani** [comment]
> You may try these
> 
> ```
> 
> sudo sysctl -w net.ipv4.ip_forward=1
> sudo iptables -t nat -A POSTROUTING -s 10.45.0.0/16 ! -o ogstun -j MASQUERADE
> sudo iptables -I INPUT -i ogstun -j ACCEPT
> sudo ip ro add 10.45.0.0/16 via 10.53.1.2
> ```

HEllo,

I have tried, but the issue is not solved

**Comment by pgawlowicz** [comment]
@Moussa-Guemdani do you run open5gs in docker or manually installed?

**Comment by Moussa-Guemdani** [comment]
@pgawlowicz  I am running open5gsmanually installed

**Comment by pgawlowicz** [comment]
did you follow this tutorial? https://docs.srsran.com/projects/project/en/latest/tutorials/source/cotsUE/source/index.html

Did you configure APN in your phone? Please check the troubleshooting section.

**Comment by Moussa-Guemdani** [comment]
Yes, i did, also with the Access Point.

It worked for some time, after re-build, then Same issue.

**Comment by pgawlowicz** [comment]
could you try this one:
```
sudo sysctl -w net.ipv4.ip_forward=1
sudo sysctl -w net.ipv4.conf.all.forwarding=1
sudo sysctl -w net.ipv6.conf.all.forwarding=1
sudo iptables -t nat -A POSTROUTING -o IFNAME_CONNECTED_TO_INTERNET -j MASQUERADE
sudo iptables -t nat -A POSTROUTING -s 10.45.0.0/16 ! -o ogstun -j MASQUERADE
sudo iptables -P FORWARD ACCEPT
sudo ip ro add 10.45.0.0/16 via 10.53.1.2
```

**Comment by pgawlowicz** [comment]
@Moussa-Guemdani any update on this issue?

**Comment by Moussa-Guemdani** [comment]
Hello,
It works very fine fine
Thank you for your help.
