### ISSUE TITLE
Issue when connecting 2 RUs, UE is attaching to only one RU

### ISSUE THREAD

**Issue by vvdn5gtest** [srsran/srsRAN_Project#627]
## Issue Description ##
We have tried connecting 2 RUs, but the UE is attaching only with one o-RU.

## Setup Details ##
The block diagram is as follows:
![Setup_Diagram drawio](https://github.com/srsran/srsRAN_Project/assets/170701529/8bfa4857-e2f3-4f82-a641-b47002b500f0)

The config is given below:
[gnb_ru_ran_vvdn_lpru_tdd_n78_100mhz_4x4_multiple_ru.zip](https://github.com/srsran/srsRAN_Project/files/15429576/gnb_ru_ran_vvdn_lpru_tdd_n78_100mhz_4x4_multiple_ru.zip)

**Comment by ismagom** [comment]
Can try commeting out/removing this section? 
```
cu_cp:
  max_nof_dus: 1                          # Optional UINT. Maximum number of DU connections that the CU-CP may accept.
  max_nof_cu_ups: 1   
```

**Comment by vvdn5gtest** [comment]
Hi @ismagom 

We have tried that too by changing 
`cu_cp:
  max_nof_dus: 2                         # Optional UINT. Maximum number of DU connections that the CU-CP may accept.
  max_nof_cu_ups: 2 `

**Comment by ismagom** [comment]
Can you send gnb logs? 

Do you see CU-plane messages arriving all on time at both RUs?
