### ISSUE TITLE
srsGNB crashes after receiving a fuzzed measurement report

### ISSUE THREAD

**Issue by lbm98** [srsran/srsRAN_Project#633]
## Issue Description ##
srsGNB crashes when receiving a fuzzed measurement report

## Setup Details ##
Can be reproduced by sending the fuzzed message from the srsRAN_4G UE over ZeroMQ to the srsGNB,
but it is much simpler to edit the unittest in
https://github.com/srsran/srsRAN_Project/blob/f3ed07a5a6f04245a57ca667194e1a3bf9684149/tests/unittests/rrc/rrc_ue_meas_report_test.cpp#L50
and replace the `meas_report_pdu` with the one below

```c++
std::vector<uint8_t> data {0x01,0xe2,0x02,0xdd,0x00,0x5d,0x5e,0xaf,0xe0,0x51,0x07,0x20,0x04,0x03,0xe4,0x82,0x07,0x00,0x00,0x02,0x00,0x02,0xbd,0x60,0x6c,0x78,0x0a,0xd5,0x2f,0x70,0x70,0xfb,0xa3,0xc0,0xc1,0xb9,0xbf,0x01,0x43,0xe0,0x01,0x66,0x07,0x08,0xcf,0x92,0x81,0xc0,0x40,0x00,0x60,0x00,0x01,0x00,0x81,0x05,0x25,0xb9,0xb4,0xad,0x44,0x06,0xa0,0xd3,0x0f,0x4a,0x6f,0x10,0x20,0xc0,0xfc,0x00,0xfb,0x85,0xcd,0x8e,0x00,0x00};
srsran::byte_buffer meas_report_pdu = srsran::byte_buffer::create(data).value();
```

## Expected Behavior ##
The bad measurement report is handled gracefully.

## Actual Behaviour ##
The srsGNB crashes with the following message
```
srsGNB FATAL ERROR: Invalid meas result neigh cells type = 2.
Aborted (core dumped)
```

## Steps to reproduce the problem ##
Covered in setup details.

## Additional Information ##
Because the GNB crashes, this is a security vulnerability.

**Comment by herlesupreeth** [comment]
@lbm98 Thank you very much for pointing this out. The fix will be rolled out in upcoming release.
