### ISSUE TITLE
GNB Crash After E2 RICSubscriptionResponse When There are No UEs Connected

### ISSUE THREAD

**Issue by Esawi** [srsran/srsRAN_Project#644]
## Issue Description ##
- When subscribing to any KPM (e.g. RRU.PrbTotDl), if there was a UE connected to the GNB everything would be normal, but if there were no UEs connected to the GNB it will crash right after the RICSubscriptionRequestResponse.

```
gnb  | ==== gNodeB started ===
gnb  | Type <t> to view trace
gnb  | Stack trace (most recent call last) in thread 19:
gnb  | #12   Object "", at 0xffffffffffffffff, in 
gnb  | #11   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fcf4ed1184f, in 
gnb  | #10   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fcf4ec7fac2, in 
gnb  | #9    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7fcf4eff7252, in 
gnb  | #8    Object "/usr/local/bin/gnb", at 0x55590e1e931e, in 
gnb  | #7    Object "/usr/local/bin/gnb", at 0x55590e26e452, in 
gnb  | #6    Object "/usr/local/bin/gnb", at 0x55590e20bb4f, in 
gnb  | #5    Object "/usr/local/bin/gnb", at 0x55590e229f19, in 
gnb  | #4    Object "/usr/local/bin/gnb", at 0x55590e12e79d, in 
gnb  | #3    Object "/usr/local/bin/gnb", at 0x55590e12d121, in 
gnb  | #2    Object "/usr/local/bin/gnb", at 0x55590e1054dd, in 
gnb  | #1    Object "/usr/local/bin/gnb", at 0x55590e114cd0, in 
gnb  | #0    Object "/usr/local/bin/gnb", at 0x55590e1131f2, in 
gnb  | Segmentation fault (Address not mapped to object [0x10])
gnb  | watf? exit
gnb exited with code 1
```
  

## Setup Details ##
srsran: main branch commit f3ed07a (21052024)

Logs, Configs for the crash (No UE was connected to the cell before the Subscription)
[run01_with_crash.zip](https://github.com/user-attachments/files/15514381/run01_with_crash.zip)

Logs, Configs for the normal behavior (There was a UE Connected to the cell before the subscription)
[run02_normal_behavior_with_UEs_connected.zip](https://github.com/user-attachments/files/15514438/run02_normal_behavior_with_UEs_connected.zip)

## Steps to reproduce the problem ##
- Start Cell.
- (before connecting any UE) Subscribe to RRU.PrbTotDl KPM.

**Comment by yagoda** [comment]
Hi Esawi,

**Comment by abcd11abcd** [comment]
go to /lib/e2/e2sm/e2sm_kpm/e2sm_kpm_report_service_impl.cpp. Then modify the granul_period_present from true to false. Try recompiling the project.

 bool e2sm_kpm_report_service_style1::collect_measurements()
 {
   // Set the granularity period.
 ric_ind_message.granul_period_present = false;
//ric_ind_message.granul_period         = granul_period;
 
   // Fill indication msg.
   std::vector<meas_record_item_c> meas_records_items;
}

let me know if this works

**Comment by pgawlowicz** [comment]
@Esawi thanks for pointing this out. The issue will be fixed in the next release.
