### ISSUE TITLE
gNB Handover using two USRP?

### ISSUE THREAD

**Issue by BGarcs** [srsran/srsRAN_Project#654]
Hi everyone, I have been reading the gNB Handover tutorial and I wanted to ask if it is possible to implement this functionality using two USRP b210 instead of one x310 (or similar USRP). Has anyone tried this or know if it is possible to do it?

Thanks in advance

**Comment by pgawlowicz** [comment]
Hi, unfortunately it is not supported, and not planned to be supported soon.

**Comment by pgawlowicz** [comment]
Actually, it will be supported once we support CU/DU split. Specifically, each DU will be running as an independent process and will connect to its own USRP.

**Comment by fllay** [comment]
Is it support now?

**Comment by pgawlowicz** [comment]
yes, it should be possible, just ran two DUs, each with own usrp, most probably you will need to both usrps to a common ref clock.

**Comment by Jonas-Penailillo** [comment]
Has anyone tried it?

**Comment by fllay** [comment]
yes, it works just fine for forcing handover however, for measuring handover it is not complete yet as discussed here [https://github.com/srsran/srsRAN_Project/discussions/715](url)

**Comment by frankist** [comment]
>yes, it works just fine for forcing handover however, for measuring handover it is not complete yet as discussed here [https://github.com/srsran/srsRAN_Project/discussions/715](https://github.com/srsran/srsRAN_Project/issues/url)

Wrong link?

The common ref clock is important for the RRC measurements to work well. If the two USRPs are not well synchronized, CFO can make the neighbor cell signal look very weak.

**Comment by stavrosdim** [comment]
Can anyone provide a tutorial or maybe the yml files used for this? I am trying to complete this using 2 B210s with srsRAN gNB 24.04, but have not had any luck making the UE report the neighboring cell measurements.

Thanks in advance.
