### ISSUE TITLE
Downlink doesn't work

### ISSUE THREAD

**Issue by shirinebadi** [srsran/srsRAN_Project#656]
## Issue Description ##
Hi. I'm trying to setup srsRAN with srsUE and using dockerized 5G core. Although I'm able to ping 10.145.1.1

 but downlink doesn't work. I'm running UE on machine 1 and RAN and 5GC on machine 2. I can't find tun_srs on UE machine. 
Attached gnb and ue config files.
[ue.txt](https://github.com/user-attachments/files/15594587/ue.txt)
[gnb1.txt](https://github.com/user-attachments/files/15594589/gnb1.txt)

**Comment by pgawlowicz** [comment]
please follow this tutorial: https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html

could you share your logs?
