### ISSUE TITLE
Integration of custom L1 with srsRAN

### ISSUE THREAD

**Issue by abcd11abcd** [srsran/srsRAN_Project#663]
I want to use srsRAN project without phy layer. In the place of srsRAN's phy layer, I want to use a custom L1 layer (this L1 also uses similar shared memory approach as FAPI between MAC and PHY). In this regard, I want to know how to compile srsRAN without phy layer and use my custom L1. Kindly help me how to proceed with this.
If I'm able to compile this project till MAC layer, then I will try to integrate my L1 to this project and test. Any leads on doing this are welcome.

I want to know whether srsRAN support 3rd party PHY layers and FAPI interfaces? Please help me.

**Comment by ismagom** [comment]
This is not an issue. You already opened a discussion post. Thanks
