### ISSUE TITLE
CSI decode error problem

### ISSUE THREAD

**Issue by Sticcolet** [srsran/srsRAN_Project#664]
## Issue Description ##
I am trying to connect three Huawei phones to one USRPX310. When I first tried to connect, the phone successfully connected to the 5G network and obtained the assigned IP address. However, after several slots communicated, the MAC layer suddenly reported that it could not decode CSI and disconnect. The error message is: [MAC] [W] [219.1] ue=0: RLF detected Cause: 100 confidential undecoded CSIs. Then wait for a few minutes or even tens of minutes before the phone can reconnect to the network. At this time, it is highly likely that long-term stable communication can occur, and the above process is unlikely to be repeated.

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
RU: USRPX310
GNB: [srsRAN Project 24.04]
UE: HUAWEI P40
the GNB.log file 
[gnb.log.zip](https://github.com/user-attachments/files/15784049/gnb.log.zip)
is that I connected to three mobile phones in sequence. I tried to connect to the next phone only after the current phone was stably connected.

**Comment by herlesupreeth** [comment]
Thanks for the logs @Sticcolet . I see the following in the log

> 2024-06-11T06:21:04.921789 [SCHED   ] [I] [    19.5] Slot decisions pci=1 t=9us (1 PDSCH, 0 PUSCHs): DL: ue=0 c-rnti=0x4601 rb=[0..1) h_id=0 ss_id=2 k1=4 newtx=true rv=0 tbs=17
> 2024-06-11T06:21:04.921795 [RLC     ] [I] du=1 ue=0 DRB1 DL: TX status PDU. pdu_len=3 grant_len=3
> 2024-06-11T06:21:04.921795 [MAC     ] [I] [    19.5] DL PDU: ue=0 rnti=0x4601 size=17: SDU: lcid=4 nof_sdus=1 total_size=5
> 2024-06-11T06:21:04.921819 [PHY     ] [I] [    19.5] PDCCH: rnti=0x4601 ss_id=2 format=1_0 cce=0 al=2 t=8.4us
> 2024-06-11T06:21:04.921831 [PHY     ] [I] [    19.5] PDSCH: rnti=0x4601 h_id=0 k1=4 prb=[0, 1) symb=[2, 14) mod=16QAM rv=0 tbs=17 t=19.5us
> 2024-06-11T06:21:04.930744 [PHY     ] [I] [    19.9] PUCCH: rnti=0x4601 format=1 prb1=0 prb2=na symb=[0, 14) cs=0 occ=0 ack=2 t=16.7us
> 2024-06-11T06:21:04.930765 [PHY     ] [I] [    19.9] RX_SYMBOL: sector=0 offset=16310112 size=8736
> 2024-06-11T06:21:04.931753 [PHY     ] [I] [    20.0] PUCCH: rnti=0x4601 format=1 prb1=51 prb2=na symb=[0, 14) cs=0 occ=1 sr=no t=14.1us
> 2024-06-11T06:21:04.931775 [PHY     ] [I] [    20.0] RX_SYMBOL: sector=0 offset=16318848 size=8736
> 2024-06-11T06:21:04.931778 [SCHED   ] [I] [    20.5] Slot decisions pci=1 t=12us (1 PDSCH, 0 PUSCHs): DL: ue=0 c-rnti=0x4601 rb=[0..1) h_id=0 ss_id=2 k1=4 newtx=false rv=2 tbs=17
> 2024-06-11T06:21:04.931792 [PHY     ] [I] [    20.5] PDCCH: rnti=0x4601 ss_id=2 format=1_0 cce=0 al=2 t=4.5us
> 2024-06-11T06:21:04.931808 [PHY     ] [I] [    20.5] PDSCH: rnti=0x4601 h_id=0 k1=4 prb=[0, 1) symb=[2, 14) mod=16QAM rv=2 tbs=17 t=19.0us
> 2024-06-11T06:21:04.937761 [PHY     ] [I] [    20.6] PUCCH: rnti=0x4601 format=2 prb=[50, 51) prb2=na symb=[10, 12) csi1=2222 t=19.7us
> 2024-06-11T06:21:04.937778 [PHY     ] [I] [    20.6] RX_SYMBOL: sector=0 offset=16327584 size=8736

From the above point onwards it looks like phone just stopped listening to gNB. If you could also attach f1ap, mac and ngap pcap it would help us know where the issue is.

> From the above point onwards it looks like phone just stopped listening to gNB.

btw, this can happen if phone is expecting an IMS connection for voice and if the phone doesnt find it phone just gets disconnected from network (i have seen this behavior in Pixel 6a)

**Comment by Sticcolet** [comment]
> Thanks for the logs @Sticcolet . I see the following in the log
> 
> > 2024-06-11T06:21:04.921789 [SCHED   ] [I] [    19.5] Slot decisions pci=1 t=9us (1 PDSCH, 0 PUSCHs): DL: ue=0 c-rnti=0x4601 rb=[0..1) h_id=0 ss_id=2 k1=4 newtx=true rv=0 tbs=17
> > 2024-06-11T06:21:04.921795 [RLC     ] [I] du=1 ue=0 DRB1 DL: TX status PDU. pdu_len=3 grant_len=3
> > 2024-06-11T06:21:04.921795 [MAC     ] [I] [    19.5] DL PDU: ue=0 rnti=0x4601 size=17: SDU: lcid=4 nof_sdus=1 total_size=5
> > 2024-06-11T06:21:04.921819 [PHY     ] [I] [    19.5] PDCCH: rnti=0x4601 ss_id=2 format=1_0 cce=0 al=2 t=8.4us
> > 2024-06-11T06:21:04.921831 [PHY     ] [I] [    19.5] PDSCH: rnti=0x4601 h_id=0 k1=4 prb=[0, 1) symb=[2, 14) mod=16QAM rv=0 tbs=17 t=19.5us
> > 2024-06-11T06:21:04.930744 [PHY     ] [I] [    19.9] PUCCH: rnti=0x4601 format=1 prb1=0 prb2=na symb=[0, 14) cs=0 occ=0 ack=2 t=16.7us
> > 2024-06-11T06:21:04.930765 [PHY     ] [I] [    19.9] RX_SYMBOL: sector=0 offset=16310112 size=8736
> > 2024-06-11T06:21:04.931753 [PHY     ] [I] [    20.0] PUCCH: rnti=0x4601 format=1 prb1=51 prb2=na symb=[0, 14) cs=0 occ=1 sr=no t=14.1us
> > 2024-06-11T06:21:04.931775 [PHY     ] [I] [    20.0] RX_SYMBOL: sector=0 offset=16318848 size=8736
> > 2024-06-11T06:21:04.931778 [SCHED   ] [I] [    20.5] Slot decisions pci=1 t=12us (1 PDSCH, 0 PUSCHs): DL: ue=0 c-rnti=0x4601 rb=[0..1) h_id=0 ss_id=2 k1=4 newtx=false rv=2 tbs=17
> > 2024-06-11T06:21:04.931792 [PHY     ] [I] [    20.5] PDCCH: rnti=0x4601 ss_id=2 format=1_0 cce=0 al=2 t=4.5us
> > 2024-06-11T06:21:04.931808 [PHY     ] [I] [    20.5] PDSCH: rnti=0x4601 h_id=0 k1=4 prb=[0, 1) symb=[2, 14) mod=16QAM rv=2 tbs=17 t=19.0us
> > 2024-06-11T06:21:04.937761 [PHY     ] [I] [    20.6] PUCCH: rnti=0x4601 format=2 prb=[50, 51) prb2=na symb=[10, 12) csi1=2222 t=19.7us
> > 2024-06-11T06:21:04.937778 [PHY     ] [I] [    20.6] RX_SYMBOL: sector=0 offset=16327584 size=8736
> 
> From the above point onwards it looks like phone just stopped listening to gNB. If you could also attach f1ap, mac and ngap pcap it would help us know where the issue is.
> 
> > From the above point onwards it looks like phone just stopped listening to gNB.
> 
> btw, this can happen if phone is expecting an IMS connection for voice and if the phone doesnt find it phone just gets disconnected from network (i have seen this behavior in Pixel 6a)

Thank you for your reply. This is a new log file.
[gnb.zip](https://github.com/user-attachments/files/15784640/gnb.zip)
I don't think it's because the phone stopped listening to GNB or IMS
. If that's the case, then the behavior of stable access in the future should not occur, or is this a special access mechanism? By the way, I would like to ask how to generate traffic load for GNB using iperf3 on a mobile phone? I can ping GNB's IP but cannot connect to IPerf.

**Comment by herlesupreeth** [comment]
![image](https://github.com/srsran/srsRAN_Project/assets/4115839/c7a7132a-2b48-4ed7-bc8e-23c74653d074)

Here you can see phone is attempting to connect to ims DNN . This repeats again in packet 32 of gnb_ngap.pcap and eventually UE completely disconnects

> By the way, I would like to ask how to generate traffic load for GNB using iperf3 on a mobile phone?

You can run iperf3 on the UDP by binding to ogstun interface and on the UE side use any iperf3 app you can find on playstore
