### ISSUE TITLE
srsUE cannot connect to srsGNB with USRP B210 and BladeRF

### ISSUE THREAD

**Issue by breakthrough55** [srsran/srsRAN_Project#679]
hello，everyone. 
I really need some help.

## Issue Description ##
I'm trying to connect srsue to the gnb using USRP B210, but there is something wrong and I don't know the reason.

I've followed the steps in the [tutorial](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#srsran-gnb-with-srsue). I have built open5gs, srsRAN_Project and srsRAN_4G from sources. Each of them seems to work fine and apparently the gNB and open5gs connect with each other. However, the srsUE seems to fail in connecting.

## Setup Details ##

Operation System: Ubuntu 22.04
Hardware: 1.USRP B210  2.BladeRF

GNB：[gnb_rf_b210_fdd_srsUE.txt](https://github.com/user-attachments/files/15883952/gnb_rf_b210_fdd_srsUE.txt)
UE：[ue_rf.txt](https://github.com/user-attachments/files/15883958/ue_rf.txt)

## Expected Behavior ##
I just want to let the srsUE connect to the GNB successfully, but it doesn't

## Actual Behaviour ##
[What happens instead e.g. error message]
![Screenshot from 2024-06-18 17-20-58](https://github.com/srsran/srsRAN_Project/assets/117147527/5d8576cf-cea8-4e63-a18a-7ece481653ce)
After attaching UE, no connection was established with GNB. I checked the log of UE: 2023-07-11T11:12:40.601533 [PHY-SA] [E] [3910] SYNC: detected out-of-sync... skipping slot ... Ok with the signal quality if you see this error

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]
[gnb.log](https://github.com/user-attachments/files/15884012/gnb.log)

[ue.log](https://github.com/user-attachments/files/15884013/ue.log)

**Comment by pgawlowicz** [comment]
could you check CPU load on the host running srsUE?
