### ISSUE TITLE
Number of symbols is 0 in O-RAN Fronthaul C-Plane for PRACH

### ISSUE THREAD

**Issue by terry-hasegawa** [srsran/srsRAN_Project#686]
## Issue Description ##
When using Long Preamble, the number of symbols included in the O-RAN Fronthaul C-Plane for PRACH is 0.
The number of symbols is defined by O-RAN WG4 CUS as follows:
![image](https://github.com/srsran/srsRAN_Project/assets/126004237/4b4a2b6e-b97b-4cef-a42b-731372515cbf)

However, when using Long Preamble Format 0, the number of symbols is 0.
![image](https://github.com/srsran/srsRAN_Project/assets/126004237/7a50b5ac-03d4-4273-8cca-b5ccf03af039)

## Setup Details ##
Set up srs gNB with Long Preamble Format.

## Expected Behavior ##
An appropriate number of symbols is set in the Fronthaul packet.

## Actual Behaviour ##
The Fronthaul C-Plane for PRACH has number of symbols set to 0.

## Steps to reproduce the problem ##
Set up srs gNB with Long Preamble Format.

## Additional Information ##
For Short Preamble, the number of symbols is set in lib\ran\prach\prach_preamble_information.cpp::get_prach_preamble_short_info(). 
However, for Long Preamble, the number of symbols is not set in lib\ran\prach\prach_preamble_information.cpp::get_prach_preamble_long_info().

get_prach_preamble_long_info()
![image](https://github.com/srsran/srsRAN_Project/assets/126004237/6f33ca77-5c63-425e-bf0c-76bb9b33d086)

get_prach_preamble_short_info()
![image](https://github.com/srsran/srsRAN_Project/assets/126004237/b9935e7e-28f2-4c4e-950a-1a27e64f29fa)

**Comment by andrepuschmann** [comment]
The issue should solved in current `main`. Could you retest and check please?

**Comment by terry-hasegawa** [comment]
Hi @andrepuschmann, This issue was also reproduced on the main branch. Please check.

**Comment by andrepuschmann** [comment]
I just double checked with current main and the config @wei-lou posted and I confirm that it works. See here:
![image](https://github.com/srsran/srsRAN_Project/assets/525775/cbf0d544-aa64-41c1-9308-0f8a8bd33fa3)

I guess you are using an older version.

**Comment by wei-lou** [comment]
Hi @andrepuschmann ,

This is the link I pulled the latest 24.04 load and then compiled. Is this the right link for the latest load or there are some other links? Thanks,

https://github.com/srsran/srsRAN_Project/archive/refs/tags/release_24_04.tar.gz

![image](https://github.com/srsran/srsRAN_Project/assets/137309708/74b1364d-d5da-4d38-9082-c0332ff0bb8b)

**Comment by andrepuschmann** [comment]
The release is from April 22nd. You need to git clone the repo and use the main branch to get the latest code. We only do tagged releases every 6 months.

**Comment by wei-lou** [comment]
> The release is from April 22nd. You need to git clone the repo and use the main branch to get the latest code. We only do tagged releases every 6 months.



> The release is from April 22nd. You need to git clone the repo and use the main branch to get the latest code. We only do tagged releases every 6 months.

Got it, thanks for the clarification

**Comment by terry-hasegawa** [comment]
@andrepuschmann Did git pull, now the numsymbol is 1. Thank you.
![image](https://github.com/srsran/srsRAN_Project/assets/126004237/d19462df-ba06-490f-b975-c1d3340b8fc0)
