### ISSUE TITLE
ue_container is not show when i use metrics_udp_receiver.py

### ISSUE THREAD

**Issue by RogerLin88124** [srsran/srsRAN_Project#711]
## Issue Description ##
I would like to retrieve some data from the gNB to observe its performance. Currently, I use the Grafana GUI to monitor some information, such as MCS, Bitrate, and CQI. I also found a script from this website (https://docs.srsran.com/projects/project/en/latest/_downloads/eae5e40786526dbf087e915f974056d8/metrics_udp_receiver.py) that can collect data through a port and convert it into a JSON file. However, it shows an "unreachable" error as in the attached picture, and only the cell_metrics data is available without ue_container.

Additionally, I want to retrieve two more metrics: TX symbols and PHY TBs. I have seen similar data in the gnb.log, but it is difficult to extract from the log, and there might be time synchronization issues if I need to combine it with data like MCS retrieved from other sources. Is there any way to retrieve the above-mentioned data from another source? Thank you very much. The most important issue is why I can't receive ue_container when I switch from Grafana to using udp_receiver.py.

I hope someone can help me with this. Thank you very much.

## Setup Details ##
Received JSON: {'timestamp': 1720337866.92, 'rlc_metrics': [{'drb': {'du_id': 0, 'ue_id': 0, 'drb_id': 1, 'tx': {'num_sdus': 0, 'num_sdu_bytes': 0, 'num_dropped_sdus': 0, 'num_discarded_sdus': 0, 'num_discard_failures': 0, 'num_pdus': 0, 'num_pdu_bytes': 0}, 'rx': {'num_sdus': 0, 'num_sdu_bytes': 0, 'num_pdus': 0, 'num_pdu_bytes': 0, 'num_lost_pdus': 0, 'num_malformed_pdus': 0}}}]}
Received JSON: {'timestamp': 1720337866.92, 'rlc_metrics': [{'drb': {'du_id': 0, 'ue_id': 1, 'drb_id': 1, 'tx': {'num_sdus': 0, 'num_sdu_bytes': 0, 'num_dropped_sdus': 0, 'num_discarded_sdus': 0, 'num_discard_failures': 0, 'num_pdus': 0, 'num_pdu_bytes': 0}, 'rx': {'num_sdus': 0, 'num_sdu_bytes': 0, 'num_pdus': 0, 'num_pdu_bytes': 0, 'num_lost_pdus': 0, 'num_malformed_pdus': 0}}}]}
Received JSON: {'timestamp': 1720337867.47, 'rlc_metrics': [{'drb': {'du_id': 0, 'ue_id': 2, 'drb_id': 1, 'tx': {'num_sdus': 0, 'num_sdu_bytes': 0, 'num_dropped_sdus': 0, 'num_discarded_sdus': 0, 'num_discard_failures': 0, 'num_pdus': 0, 'num_pdu_bytes': 0}, 'rx': {'num_sdus': 0, 'num_sdu_bytes': 0, 'num_pdus': 0, 'num_pdu_bytes': 0, 'num_lost_pdus': 0, 'num_malformed_pdus': 0}}}]}
Received data is not in JSON format: {
  "timestamp": 1720337867.763,
  "cell_metrics": {
    "error_indication_count": 0,
    "average_latency": 23,
    "latency_histogram": [
      {
        "latency_bin": {
          "latency_bin_start_usec": 0,
          "latency_bin_count": 941
        }
      },
      {
        "latency_bin": {
          "latency_bin_start_usec": 50,
          "latency_bin_count": 25
        }
      },
      {
        "latency_bin": {
          "latency_bin_start_usec": 100,
          "latency_bin_count": 12
        }
      },
      {
        "latency_bin": {
          "latency_bin_start_usec": 150,
          "latency_bin_count": 5
        }
      },
      {
        "latency_bin": {
          "latency_bin_start_usec": 200,
          "latency_bin_count": 2
        }
      },
      {
        "latency_bin": {
          "latency_bin_start_usec": 250,
          "latency_bin_count": 4
        }
      },
      {
        "latency_bin": {
          "latency_bin_start_usec": 300,
          "latency_bin_count": 4
        }
      },
 
Received JSON: {'timestamp': 1720337868.2710001, 'rlc_metrics': [{'drb': {'du_id': 0, 'ue_id': 1, 'drb_id': 1, 'tx': {'num_sdus': 0, 'num_sdu_bytes': 0, 'num_dropped_sdus': 0, 'num_discarded_sdus': 0, 'num_discard_failures': 0, 'num_pdus': 0, 'num_pdu_bytes': 0}, 'rx': {'num_sdus': 0, 'num_sdu_bytes': 0, 'num_pdus': 0, 'num_pdu_bytes': 0, 'num_lost_pdus': 0, 'num_malformed_pdus': 0}}}]}
Received JSON: {'timestamp': 1720337868.2710001, 'rlc_metrics': [{'drb': {'du_id': 0, 'ue_id': 0, 'drb_id': 1, 'tx': {'num_sdus': 0, 'num_sdu_bytes': 0, 'num_dropped_sdus': 0, 'num_discarded_sdus': 0, 'num_discard_failures': 0, 'num_pdus': 0, 'num_pdu_bytes': 0}, 'rx': {'num_sdus': 0, 'num_sdu_bytes': 0, 'num_pdus': 0, 'num_pdu_bytes': 0, 'num_lost_pdus': 0, 'num_malformed_pdus': 0}}}]}
^CReceived data saved to gnb_metrics.json. Exiting...

## Actual Behaviour ##
![image](https://github.com/srsran/srsRAN_Project/assets/71495182/4e36a688-2fb2-4c31-b20b-2ab082f99e09)

## File ##
[metrics_udp_receiver.txt](https://github.com/user-attachments/files/16118478/metrics_udp_receiver.txt)
[gnb_zmq.txt](https://github.com/user-attachments/files/16118479/gnb_zmq.txt)

**Comment by pgawlowicz** [comment]
could you check here: https://github.com/srsran/srsRAN_Project/discussions/722#discussioncomment-10043261
