### ISSUE TITLE
srsRAN ERROR: Failed to connect DU to CU-CP

### ISSUE THREAD

**Issue by Moussa-Guemdani** [srsran/srsRAN_Project#723]
## Issue Description ##
After setting up and running the CU, the DU fails to connect to CU-CP 
(CU/DU split deployment)

## Setup Details ##
Followed the tutorial in "https://docs.srsran.com/projects/project/en/latest/tutorials/source/cu_du_split/source/index.html#"

--> deployment of the CU and the DU on the same machine

## Actual Behaviour ##
![Screenshot from 2024-07-10 16-21-21](https://github.com/srsran/srsRAN_Project/assets/61354367/23c97302-c825-438f-95ee-ac9b14ab642b)

![image](https://github.com/srsran/srsRAN_Project/assets/61354367/973d32a3-08a6-4aaf-a28c-2156dce5cc5a)

**Comment by pgawlowicz** [comment]
Hi @Moussa-Guemdani, this discussion seems to be related could you check it?
https://github.com/srsran/srsRAN_Project/discussions/707

**Comment by pgawlowicz** [comment]
did you create a new virtual interface with the requested IP address?

**Comment by Moussa-Guemdani** [comment]
No, I haven't created a virtual interface for the address 127.0.10.1 or any other address, Could please explain further?

**Comment by pgawlowicz** [comment]
you can try:

sudo ip addr add 127.0.10.1/8 dev lo
sudo ip addr add 127.0.10.2/8 dev lo
ip addr show lo

**Comment by Moussa-Guemdani** [comment]
Yse,
Still having the same issue
![image](https://github.com/user-attachments/assets/5b73a620-971a-4fe2-b09c-69de02099e5c)

**Comment by Moussa-Guemdani** [comment]
Hello @pgawlowicz ,

I have rebuilt and used the minimal configuration with different IP addresses, the "amf: bind_addr:" and the "cu_cp: bind_addr:", and it works very well,

[CU_TEST.txt](https://github.com/user-attachments/files/16195692/CU_TEST.txt)[DU_TEST.txt](https://github.com/user-attachments/files/16195702/DU_TEST.txt)

I will close this issue,
Thank you for your help.

**Comment by Moussa-Guemdani** [comment]
Hello @pgawlowicz ,

I have rebuilt and used the minimal configuration with different IP addresses, the "amf: bind_addr:" and the "cu_cp: bind_addr:", and it works very well,

[CU_TEST.txt](https://github.com/user-attachments/files/16195692/CU_TEST.txt)[DU_TEST.txt](https://github.com/user-attachments/files/16195702/DU_TEST.txt)

I will close this issue,
Thank you for your help.
