### ISSUE TITLE
Cannot see the spectrum of the transmitted signal after the gnb operated

### ISSUE THREAD

**Issue by Franxx199807** [srsran/srsRAN_Project#746]
![测试截屏](https://github.com/user-attachments/assets/5400e2dd-fd8c-4dbf-82d9-d73eeba1094d)

After the program ran, I could not search for the operator on my mobile phone, so I observed the spectrum of the transmitted signal and found that the signal spectrum was always in a peak state, and the correct spectrum image should be like the green signal in the figure, with a whole band bandwidth. I am a novice, do not know what causes, to the  Net friend for advice

**Comment by andrepuschmann** [comment]
If no users are attached and no downlink traffic is running you only have very sporadic transmission for SSB+SIB1. Unless you're using a real-time spectrum analyzer (like Gr-fosphor) you simply don't see the transmission and the spectrum seems empty.
