### ISSUE TITLE
having troubles connecting 3 UEs to the open5gc

### ISSUE THREAD

**Issue by henokbfg** [srsran/srsRAN_Project#747]
## Issue Description ##
when i execute the flowgraph, I get this on the 5gc console

open5gs_5gc  | 07/29 07:48:12.299: [amf] INFO: InitialUEMessage (../src/amf/ngap-handler.c:401)
open5gs_5gc  | 07/29 07:48:12.299: [amf] INFO: [Added] Number of gNB-UEs is now 1 (../src/amf/context.c:2550)
open5gs_5gc  | 07/29 07:48:12.299: [amf] INFO:     RAN_UE_NGAP_ID[0] AMF_UE_NGAP_ID[1] TAC[7] CellID[0x66c000] (../src/amf/ngap-handler.c:562)
open5gs_5gc  | 07/29 07:48:12.299: [amf] INFO: [suci-0-001-01-0000-0-0-0123456790] Unknown UE by SUCI (../src/amf/context.c:1835)
open5gs_5gc  | 07/29 07:48:12.299: [amf] INFO: [Added] Number of AMF-UEs is now 1 (../src/amf/context.c:1616)
open5gs_5gc  | 07/29 07:48:12.299: [gmm] INFO: Registration request (../src/amf/gmm-sm.c:1165)
open5gs_5gc  | 07/29 07:48:12.299: [gmm] INFO: [suci-0-001-01-0000-0-0-0123456790]    SUCI (../src/amf/gmm-handler.c:166)
open5gs_5gc  | 07/29 07:48:12.383: [amf] INFO: InitialUEMessage (../src/amf/ngap-handler.c:401)
open5gs_5gc  | 07/29 07:48:12.383: [amf] INFO: [Added] Number of gNB-UEs is now 2 (../src/amf/context.c:2550)
open5gs_5gc  | 07/29 07:48:12.383: [amf] INFO:     RAN_UE_NGAP_ID[1] AMF_UE_NGAP_ID[2] TAC[7] CellID[0x66c000] (../src/amf/ngap-handler.c:562)
open5gs_5gc  | 07/29 07:48:12.383: [amf] INFO: [suci-0-001-01-0000-0-0-0123456780] Unknown UE by SUCI (../src/amf/context.c:1835)
open5gs_5gc  | 07/29 07:48:12.383: [amf] INFO: [Added] Number of AMF-UEs is now 2 (../src/amf/context.c:1616)
open5gs_5gc  | 07/29 07:48:12.383: [gmm] INFO: Registration request (../src/amf/gmm-sm.c:1165)
open5gs_5gc  | 07/29 07:48:12.383: [gmm] INFO: [suci-0-001-01-0000-0-0-0123456780]    SUCI (../src/amf/gmm-handler.c:166)
open5gs_5gc  | 07/29 07:48:12.729: [gmm] INFO: [imsi-001010123456790] Registration complete (../src/amf/gmm-sm.c:2146)
open5gs_5gc  | 07/29 07:48:12.729: [amf] INFO: [imsi-001010123456790] Configuration update command (../src/amf/nas-path.c:612)
open5gs_5gc  | 07/29 07:48:12.729: [gmm] INFO:     UTC [2024-07-29T07:48:12] Timezone[0]/DST[0] (../src/amf/gmm-build.c:559)
open5gs_5gc  | 07/29 07:48:12.729: [gmm] INFO:     LOCAL [2024-07-29T07:48:12] Timezone[0]/DST[0] (../src/amf/gmm-build.c:564)
open5gs_5gc  | 07/29 07:48:12.729: [amf] INFO: [Added] Number of AMF-Sessions is now 1 (../src/amf/context.c:2571)
open5gs_5gc  | 07/29 07:48:12.729: [gmm] INFO: UE SUPI[imsi-001010123456790] DNN[srsapn] S_NSSAI[SST:1 SD:0xffffff] smContextRef [NULL] (../src/amf/gmm-handler.c:1241)
open5gs_5gc  | 07/29 07:48:12.729: [gmm] INFO: No SMF Instance (../src/amf/gmm-handler.c:1278)
open5gs_5gc  | 07/29 07:48:12.731: [sbi] WARNING: [SMF] (NRF-discover) NF has already been added [ac77cdce-4d7e-41ef-885b-1f4e73e34f45:1] (../lib/sbi/nnrf-handler.c:1057)
open5gs_5gc  | 07/29 07:48:12.731: [sbi] WARNING: NF EndPoint(addr) updated [127.0.0.4:80] (../lib/sbi/context.c:2174)
open5gs_5gc  | 07/29 07:48:12.731: [sbi] WARNING: NF EndPoint(addr) updated [127.0.0.4:7777] (../lib/sbi/context.c:1917)
open5gs_5gc  | 07/29 07:48:12.731: [sbi] INFO: [SMF] (NF-discover) NF Profile updated [ac77cdce-4d7e-41ef-885b-1f4e73e34f45:1] (../lib/sbi/nnrf-handler.c:1095)
open5gs_5gc  | 07/29 07:48:12.731: [smf] INFO: [Added] Number of SMF-UEs is now 1 (../src/smf/context.c:1019)
open5gs_5gc  | 07/29 07:48:12.731: [smf] INFO: [Added] Number of SMF-Sessions is now 1 (../src/smf/context.c:3068)
open5gs_5gc  | 07/29 07:48:12.733: [sbi] INFO: [SMF] (SCP-discover) NF registered [ac77cdce-4d7e-41ef-885b-1f4e73e34f45:1] (../lib/sbi/path.c:211)
open5gs_5gc  | 07/29 07:48:12.736: [smf] ERROR: No UPFs are PFCP associated that are suited to RR (../src/smf/context.c:1167)
open5gs_5gc  | 07/29 07:48:12.736: [smf] ERROR: [imsi-001010123456790:1] No associated UPF (../src/smf/npcf-handler.c:442)
open5gs_5gc  | 07/29 07:48:12.736: [smf] ERROR: smf_npcf_smpolicycontrol_handle_create() failed (../src/smf/gsm-sm.c:528)
open5gs_5gc  | 07/29 07:48:12.737: [amf] ERROR: [1:0] PDU session establishment reject (../src/amf/namf-handler.c:482)
open5gs_5gc  | 07/29 07:48:12.737: [amf] WARNING: [suci-0-001-01-0000-0-0-0123456790] DL NAS transport (../src/amf/nas-path.c:1014)
open5gs_5gc  | 07/29 07:48:12.737: [amf] INFO: [Removed] Number of AMF-Sessions is now 0 (../src/amf/context.c:2578)
open5gs_5gc  | 07/29 07:48:12.737: [smf] INFO: Removed Session: UE IMSI:[imsi-001010123456790] DNN:[srsapn:1] IPv4:[10.45.1.4] IPv6:[] (../src/smf/context.c:1672)
open5gs_5gc  | 07/29 07:48:12.737: [smf] INFO: [Removed] Number of SMF-Sessions is now 0 (../src/smf/context.c:3076)
open5gs_5gc  | 07/29 07:48:12.737: [smf] INFO: [Removed] Number of SMF-UEs is now 0 (../src/smf/context.c:1080)
open5gs_5gc  | 07/29 07:48:12.858: [gmm] INFO: [imsi-001010123456790] No GUTI allocated (../src/amf/gmm-sm.c:1443)
open5gs_5gc  | 07/29 07:48:13.060: [gmm] INFO: [imsi-001010123456780] Registration complete (../src/amf/gmm-sm.c:2146)
open5gs_5gc  | 07/29 07:48:13.060: [amf] INFO: [imsi-001010123456780] Configuration update command (../src/amf/nas-path.c:612)
open5gs_5gc  | 07/29 07:48:13.060: [gmm] INFO:     UTC [2024-07-29T07:48:13] Timezone[0]/DST[0] (../src/amf/gmm-build.c:559)
open5gs_5gc  | 07/29 07:48:13.060: [gmm] INFO:     LOCAL [2024-07-29T07:48:13] Timezone[0]/DST[0] (../src/amf/gmm-build.c:564)
open5gs_5gc  | 07/29 07:48:13.061: [amf] INFO: [Added] Number of AMF-Sessions is now 1 (../src/amf/context.c:2571)
open5gs_5gc  | 07/29 07:48:13.061: [gmm] INFO: UE SUPI[imsi-001010123456780] DNN[srsapn] S_NSSAI[SST:1 SD:0xffffff] smContextRef [NULL] (../src/amf/gmm-handler.c:1241)
open5gs_5gc  | 07/29 07:48:13.061: [gmm] INFO: SMF Instance [ac77cdce-4d7e-41ef-885b-1f4e73e34f45] (../src/amf/gmm-handler.c:1280)
open5gs_5gc  | 07/29 07:48:13.061: [amf] INFO: InitialUEMessage (../src/amf/ngap-handler.c:401)
open5gs_5gc  | 07/29 07:48:13.061: [amf] INFO: [Added] Number of gNB-UEs is now 3 (../src/amf/context.c:2550)
open5gs_5gc  | 07/29 07:48:13.061: [amf] INFO:     RAN_UE_NGAP_ID[2] AMF_UE_NGAP_ID[3] TAC[7] CellID[0x66c000] (../src/amf/ngap-handler.c:562)
open5gs_5gc  | 07/29 07:48:13.061: [amf] INFO: [suci-0-001-01-0000-0-0-0123456791] Unknown UE by SUCI (../src/amf/context.c:1835)
open5gs_5gc  | 07/29 07:48:13.061: [amf] INFO: [Added] Number of AMF-UEs is now 3 (../src/amf/context.c:1616)
open5gs_5gc  | 07/29 07:48:13.061: [gmm] INFO: Registration request (../src/amf/gmm-sm.c:1165)
open5gs_5gc  | 07/29 07:48:13.061: [gmm] INFO: [suci-0-001-01-0000-0-0-0123456791]    SUCI (../src/amf/gmm-handler.c:166)
open5gs_5gc  | 07/29 07:48:13.061: [smf] INFO: [Added] Number of SMF-UEs is now 1 (../src/smf/context.c:1019)
open5gs_5gc  | 07/29 07:48:13.061: [smf] INFO: [Added] Number of SMF-Sessions is now 1 (../src/smf/context.c:3068)
open5gs_5gc  | 07/29 07:48:13.066: [smf] ERROR: No UPFs are PFCP associated that are suited to RR (../src/smf/context.c:1167)
open5gs_5gc  | 07/29 07:48:13.066: [smf] ERROR: [imsi-001010123456780:1] No associated UPF (../src/smf/npcf-handler.c:442)
open5gs_5gc  | 07/29 07:48:13.066: [smf] ERROR: smf_npcf_smpolicycontrol_handle_create() failed (../src/smf/gsm-sm.c:528)
open5gs_5gc  | 07/29 07:48:13.066: [amf] ERROR: [1:0] PDU session establishment reject (../src/amf/namf-handler.c:482)
open5gs_5gc  | 07/29 07:48:13.066: [amf] WARNING: [suci-0-001-01-0000-0-0-0123456780] DL NAS transport (../src/amf/nas-path.c:1014)
open5gs_5gc  | 07/29 07:48:13.066: [amf] INFO: [Removed] Number of AMF-Sessions is now 0 (../src/amf/context.c:2578)
open5gs_5gc  | 07/29 07:48:13.067: [smf] INFO: Removed Session: UE IMSI:[imsi-001010123456780] DNN:[srsapn:1] IPv4:[10.45.1.2] IPv6:[] (../src/smf/context.c:1672)
open5gs_5gc  | 07/29 07:48:13.067: [smf] INFO: [Removed] Number of SMF-Sessions is now 0 (../src/smf/context.c:3076)
open5gs_5gc  | 07/29 07:48:13.067: [smf] INFO: [Removed] Number of SMF-UEs is now 0 (../src/smf/context.c:1080)
open5gs_5gc  | 07/29 07:48:13.183: [gmm] INFO: [imsi-001010123456780] No GUTI allocated (../src/amf/gmm-sm.c:1443)
open5gs_5gc  | 07/29 07:48:13.872: [gmm] INFO: [imsi-001010123456791] Registration complete (../src/amf/gmm-sm.c:2146)
open5gs_5gc  | 07/29 07:48:13.872: [amf] INFO: [imsi-001010123456791] Configuration update command (../src/amf/nas-path.c:612)
open5gs_5gc  | 07/29 07:48:13.872: [gmm] INFO:     UTC [2024-07-29T07:48:13] Timezone[0]/DST[0] (../src/amf/gmm-build.c:559)
open5gs_5gc  | 07/29 07:48:13.872: [gmm] INFO:     LOCAL [2024-07-29T07:48:13] Timezone[0]/DST[0] (../src/amf/gmm-build.c:564)
open5gs_5gc  | 07/29 07:48:13.872: [amf] INFO: [Added] Number of AMF-Sessions is now 1 (../src/amf/context.c:2571)
open5gs_5gc  | 07/29 07:48:13.872: [gmm] INFO: UE SUPI[imsi-001010123456791] DNN[srsapn] S_NSSAI[SST:1 SD:0xffffff] smContextRef [NULL] (../src/amf/gmm-handler.c:1241)
open5gs_5gc  | 07/29 07:48:13.872: [gmm] INFO: SMF Instance [ac77cdce-4d7e-41ef-885b-1f4e73e34f45] (../src/amf/gmm-handler.c:1280)
open5gs_5gc  | 07/29 07:48:13.873: [smf] INFO: [Added] Number of SMF-UEs is now 1 (../src/smf/context.c:1019)
open5gs_5gc  | 07/29 07:48:13.873: [smf] INFO: [Added] Number of SMF-Sessions is now 1 (../src/smf/context.c:3068)
open5gs_5gc  | 07/29 07:48:13.877: [smf] ERROR: No UPFs are PFCP associated that are suited to RR (../src/smf/context.c:1167)
open5gs_5gc  | 07/29 07:48:13.877: [smf] ERROR: [imsi-001010123456791:1] No associated UPF (../src/smf/npcf-handler.c:442)
open5gs_5gc  | 07/29 07:48:13.877: [smf] ERROR: smf_npcf_smpolicycontrol_handle_create() failed (../src/smf/gsm-sm.c:528)
open5gs_5gc  | 07/29 07:48:13.878: [amf] ERROR: [1:0] PDU session establishment reject (../src/amf/namf-handler.c:482)
open5gs_5gc  | 07/29 07:48:13.878: [amf] WARNING: [suci-0-001-01-0000-0-0-0123456791] DL NAS transport (../src/amf/nas-path.c:1014)
open5gs_5gc  | 07/29 07:48:13.878: [amf] INFO: [Removed] Number of AMF-Sessions is now 0 (../src/amf/context.c:2578)
open5gs_5gc  | 07/29 07:48:13.878: [smf] INFO: Removed Session: UE IMSI:[imsi-001010123456791] DNN:[srsapn:1] IPv4:[10.45.1.5] IPv6:[] (../src/smf/context.c:1672)
open5gs_5gc  | 07/29 07:48:13.878: [smf] INFO: [Removed] Number of SMF-Sessions is now 0 (../src/smf/context.c:3076)
open5gs_5gc  | 07/29 07:48:13.878: [smf] INFO: [Removed] Number of SMF-UEs is now 0 (../src/smf/context.c:1080)
open5gs_5gc  | 07/29 07:48:13.987: [gmm] INFO: [imsi-001010123456791] No GUTI allocated (../src/amf/gmm-sm.c:1443)
open5gs_5gc  | 07/29 07:48:19.204: [pfcp] WARNING: [10] LOCAL  No Reponse. Give up! for step 1 type 5 peer [127.0.0.7]:8805 (../lib/pfcp/xact.c:606)
open5gs_5gc  | 07/29 07:48:22.701: [smf] WARNING: Retry association with peer [127.0.0.7]:8805 failed (../src/smf/pfcp-sm.c:110)
open5gs_5gc  | 07/29 07:48:24.911: [amf] INFO: UE Context Release [Action:2] (../src/amf/ngap-handler.c:1698)
open5gs_5gc  | 07/29 07:48:24.911: [amf] INFO:     RAN_UE_NGAP_ID[0] AMF_UE_NGAP_ID[1] (../src/amf/ngap-handler.c:1699)
open5gs_5gc  | 07/29 07:48:24.911: [amf] INFO:     SUCI[suci-0-001-01-0000-0-0-0123456790] (../src/amf/ngap-handler.c:1702)
open5gs_5gc  | 07/29 07:48:24.911: [amf] INFO: [Removed] Number of gNB-UEs is now 2 (../src/amf/context.c:2557)
open5gs_5gc  | 07/29 07:48:25.112: [amf] INFO: UE Context Release [Action:2] (../src/amf/ngap-handler.c:1698)
open5gs_5gc  | 07/29 07:48:25.112: [amf] INFO:     RAN_UE_NGAP_ID[1] AMF_UE_NGAP_ID[2] (../src/amf/ngap-handler.c:1699)
open5gs_5gc  | 07/29 07:48:25.112: [amf] INFO:     SUCI[suci-0-001-01-0000-0-0-0123456780] (../src/amf/ngap-handler.c:1702)
open5gs_5gc  | 07/29 07:48:25.112: [amf] INFO: [Removed] Number of gNB-UEs is now 1 (../src/amf/context.c:2557)
open5gs_5gc  | 07/29 07:48:25.723: [amf] INFO: UE Context Release [Action:2] (../src/amf/ngap-handler.c:1698)
open5gs_5gc  | 07/29 07:48:25.723: [amf] INFO:     RAN_UE_NGAP_ID[2] AMF_UE_NGAP_ID[3] (../src/amf/ngap-handler.c:1699)
open5gs_5gc  | 07/29 07:48:25.723: [amf] INFO:     SUCI[suci-0-001-01-0000-0-0-0123456791] (../src/amf/ngap-handler.c:1702)
open5gs_5gc  | 07/29 07:48:25.723: [amf] INFO: [Removed] Number of gNB-UEs is now 0 (../src/amf/context.c:2557)

AND THIS ON ALL 3 UEs CONSOLE

ctive RF plugins: libsrsran_rf_zmq.so
Inactive RF plugins: 
Reading configuration file ./ue1_zmq.conf...

Built in Release mode using commit ec29b0c1f on branch master.

Opening 1 channels in RF device=zmq with args=tx_port=tcp://127.0.0.1:2101,rx_port=tcp://127.0.0.1:2100,base_srate=11.52e6
Supported RF device list: zmq file
CHx base_srate=11.52e6
Current sample rate is 1.92 MHz with a base rate of 11.52 MHz (x6 decimation)
CH0 rx_port=tcp://127.0.0.1:2100
CH0 tx_port=tcp://127.0.0.1:2101
Current sample rate is 11.52 MHz with a base rate of 11.52 MHz (x1 decimation)
Current sample rate is 11.52 MHz with a base rate of 11.52 MHz (x1 decimation)
Waiting PHY to initialize ... done!
Attaching UE...
Random Access Transmission: prach_occasion=0, preamble_index=37, ra-rnti=0x39, tti=174
Random Access Complete.     c-rnti=0x4602, ta=0
RRC Connected
PDU Session Establishment Reject with cause: Network failure
Received RRC Release

**Comment by andrepuschmann** [comment]
Seems the 5GC is not correctly running. UPF are not running and/or not configured correctly. It's not a srsRAN issue.

**Comment by henokbfg** [comment]
the setup works with 1 UE. so I don't understand why the 5GC is not running correctly with 3 UEs when it does so with 1 UE. What can I do?

**Comment by pgawlowicz** [comment]
@henokbfg did you add UE subscriber data into open5gs user database?
