### ISSUE TITLE
Quectel UE can not ping to Core

### ISSUE THREAD

**Issue by dhiaboujebha** [srsran/srsRAN_Project#751]
## Issue Description ##
I am using Quectel RM-500Q as an UE in my setup. The SIM-Card is already configered. The device gets attached to the Open5GS Core and gets an ip address. The problem is that i can only ping from Core -> UE using "ping -I ogstun 10.45.0.x" (without precising the interface in the host machine i am not able to ping anymore). 

![quectel](https://github.com/user-attachments/assets/79056a6a-4d7b-4add-909b-8858a139231c)

Trying to ping from UE->Core was always not successful: (no response found!).

![wireshark](https://github.com/user-attachments/assets/c80a1cd1-ee6f-47b1-a64c-eb601f0caf8b)

I have already set the ip_forwarding  to 1 in all machines. Using the command "sudo ./Quectel-CM the device gets connected and the routing commands are also run automatically. 

UE:
![routing](https://github.com/user-attachments/assets/25229ff3-6c7d-4dec-b9aa-b3ffb368834f)

Core:
![image](https://github.com/user-attachments/assets/7a095de4-e582-40f6-b89d-9f052e570343)

Any idea how to solve this?

**Comment by pgawlowicz** [comment]
did you setup ip forwarding on the machine running open5gs?
