### ISSUE TITLE
Installing srsRAN on Kubuntu 24.04

### ISSUE THREAD

**Issue by Burgerchops1** [srsran/srsRAN_Project#752]
## Issue Description ##
Kubuntu 24.04 package manager failing to find the package. As per the instructions I have tried to install the package via:
sudo add-apt-repository ppa:softwareradiosystems/srsran-project
sudo apt-get update
sudo apt-get install srsran-project -y
this failed as it cannot pull the repository from the ppa software radio systems. then failed to pull it and then failed to compile the package.

## Setup Details ##
A Kubuntu setup running 24.04. RF frontend is a Ettus Research N320 SDR. Managed over the SFP+ 1gb port. 

## Expected Behavior ##
Download the package and compile successfully and configure with the yaml file. 

## Actual Behaviour ##
It fails to pull the ppa repo and says it cannot be found. Then cannot locate package srsRAN through the apt package manager. 

## Steps to reproduce the problem ##
Try installing srsRAN on Kubuntu 24.04 following the guide to the letter and see the errors.

**Comment by BurmazDaniel** [comment]
Try and build srsran-project from soruce using make. It should work if you install the necessary packages. Kubuntu is a flavor of Ubuntu so I do not see any problems with using it.
