### ISSUE TITLE
Uplink is not implemented in Resource Control RC (Only downlink works)

### ISSUE THREAD

**Issue by aithamid** [srsran/srsRAN_Project#763]
## Expected Behavior ##
- Both downlink and uplink have to decrease or increase after a RC request.

## Actual Behaviour ##
- Only the downlink is affected to RC

## Steps to reproduce the problem ##
- Connect 2 smartphone 
- Reduce the resource allocation of one UE  via an xApp (I used [`ORAN SC RIC`](https://github.com/srsran/oran-sc-ric/) with `sudo docker compose exec python_xapp_runner ./simple_rc_xapp.py --ue_id=1 --e2_node_id=gnbd_001_001_00000213_0`

## Additional Information ##

I noticied in the file `lib/du_manager/procedures/du_ue_ric_configuration_procedure.cpp` of srsran project the downlink is implemented with the `res_alloc_cfg.pdsch_grant_size_limits` but there is no `res_alloc_cfg.pusch_grant_size_limits` for uplink. 

So I added just after `res_alloc_cfg.pdsch_grant_size_limits` : 
```cpp
  res_alloc_cfg.pusch_grant_size_limits = {
      req.rrm_policy_group.has_value() ? (req.rrm_policy_group.value().min_prb_policy_ratio.has_value()
                                              ? req.rrm_policy_group.value().min_prb_policy_ratio.value()
                                              : 0)
                                       : 0,
      req.rrm_policy_group.has_value() ? (req.rrm_policy_group.value().max_prb_policy_ratio.has_value()
                                              ? req.rrm_policy_group.value().max_prb_policy_ratio.value()
                                              : MAX_NOF_PRBS)
                                       : MAX_NOF_PRBS};
```
I rebuilt the project and it worked !!! 

-----

This is the example when I limit the resources of 1 UE (MAX PRB = 5)

Before RC :
![image](https://github.com/user-attachments/assets/8b35b88c-cd71-4222-87fa-23e8d9fba81c)
After RC :
![image](https://github.com/user-attachments/assets/7f982624-4e87-4d7f-baea-cea8822d819d)

**Comment by pgawlowicz** [comment]
Currently, supported only in DL.
