### ISSUE TITLE
Synchronization issues on DU side using kubernetes setup

### ISSUE THREAD

**Issue by lhms1234** [srsran/srsRAN_Project#770]
## Issue Description ##
- UE can't connect to the network because the synchronization is periodically lost
- RU packet error counter increasing
- When gNB runs on bare metal, the setup works as expected. But when the gNB runs in kubernetes, the synchronization issue occurs
- Both linuxptp methods works in bare metal: linuxptp on bare metal and on kubernetes

## Setup Details ##
- Server
  - 5GC: Open5GS in kubernetes
  - CU / DU: srsRAN (commit 4cf7513e9fe988449aadedce3278063de761a4ac) container in kubernetes
  - HW configuration:
    - Processor: Intel(R) Xeon(R) Gold 6348 CPU @ 2.60GHz
    - RAM: 256 GB
    - Kernel: 5.15.0-1037-realtime
    - OS: Ubuntu server 22.04.4 LTS
- RU: Foxconn RPQN 7801E (v3.1.12q.551)
- UE: Amarisoft UE (version 2022-03-19)
- Switch Falcon-RX/812/G xHaul & PTP Grandmaster
![image](https://github.com/user-attachments/assets/e405f7cb-4853-42c5-bc9c-7fc280036f7e)

- RF
  - BW: 50 MHz (133 PRBs)
  - SCS: 30 KHz
  - Band: n77 (TDD)
  - Frequency: centered in 3825 MHz
  - MIMO 4x4

- srsRAN helm version: 7e19cef73b2f0c9b38f324bb61a9379c8a50f94a

## Expected Behavior ##
Amarisoft UE should connect to the network.

## Actual Behaviour ##
Amarisoft UE loses the synchronization.

## Steps to reproduce the problem ##
Considering that the k8s cluster was alteready installed using kubespray and the recommended optimizations was done (realtime kernel enabling, O-FH MTU configured to 9000, etc - except by the DPDK usage), the [tutorial](https://docs.srsran.com/projects/project/en/latest/tutorials/source/k8s/source/index.html) was followed.

## Additional Information ##
Sample of the warning messages from O-FH: [gnb_ofh_sample.log](https://github.com/user-attachments/files/16600974/gnb_ofh_sample.log)
RU log: [ru.log](https://github.com/user-attachments/files/16600978/ru.log)
Amarisoft UE log: [ue-export.log.zip](https://github.com/user-attachments/files/16600980/ue-export.log.zip)
srsRAN gNB values file: [values.yaml.txt](https://github.com/user-attachments/files/16600987/values.yaml.txt)
Wireshark capture (NGAP, E2AP): [host_capture.pcap.txt](https://github.com/user-attachments/files/16601009/host_capture.pcap.txt)
Pods: [pods.log](https://github.com/user-attachments/files/16601021/pods.log)

**Comment by pgawlowicz** [comment]
@lhms1234 any updates on this issue?
