### ISSUE TITLE
FlexRIC Core Dump Error When Connecting Multiple gNBs

### ISSUE THREAD

**Issue by aliasadi2001** [srsran/srsRAN_Project#781]
Hello Everyone,

I recently attempted to connect multiple gNBs to the Open5GS core and FlexRIC, following the guidance from [this discussion](https://github.com/srsran/srsRAN_Project/discussions/561). However, when I connected the second gNB, I encountered the following error:

![Screenshot from 2024-08-21 14-41-38](https://github.com/user-attachments/assets/1e6b201c-f906-43e1-903d-f458ff517359)

Despite the error, the gNBs and Open5GS continue to run without crashing.
![Screenshot from 2024-08-21 14-45-49](https://github.com/user-attachments/assets/52af3f8c-6c5f-46ed-b80a-755fbd5adaff)

![Screenshot from 2024-08-21 14-49-12](https://github.com/user-attachments/assets/1a66b255-5b32-41fb-8781-d33c2b7c0612)

Could anyone assist in resolving this issue?

Thank you!

**Comment by pgawlowicz** [comment]
You need to set different gnb id for the second gnb.

**Comment by aliasadi2001** [comment]
Thank you
