### ISSUE TITLE
UE log increase backend queue size

### ISSUE THREAD

**Issue by hududed** [srsran/srsRAN_Project#791]
I have a simple virtual ZMQ setup between srsGNB and srsUE, I get the error for the UE:
```
PDU Session Establishment successful. IP: 10.45.0.2
RRC NR reconfiguration successful.
srsLog error - The backend queue size is about to reach its maximum capacity of 8192 elements, new log entries will get discarded.
Consider increasing the queue capacity.
```

how do I increase the size to get the full log?

**Comment by pgawlowicz** [comment]
https://github.com/srsran/srsRAN_4G/blob/ec29b0c1ff79cebcbe66caa6d6b90778261c42b8/lib/include/srsran/srslog/detail/support/backend_capacity.h#L27

**Comment by hududed** [comment]
Thank you!
