### ISSUE TITLE
Is it possible to connect a UE to a gNodeB without knowing its ARFCN?

### ISSUE THREAD

**Issue by Carcalmoa** [srsran/srsRAN_Project#819]
## Issue Description ##
My UE only finds the gNodeB if I configure the same ARFCN. So I need to know in advance the ARFCN configured in the gNodeB to be able to connect to it.

Is it possible to get information from the UE about all the base stations present in a specific frequency range, or even in a whole band, and then connect to the gNB that provides the best conditions?

## Setup Details ##
[gnb_config.txt](https://github.com/user-attachments/files/17026914/gnb_config.txt)
[ue_config.txt](https://github.com/user-attachments/files/17026915/ue_config.txt)

## Expected Behavior ##
The UE performs the cell search and finds the gNodeB.

## Actual Behaviour ##
My UE only finds the gNodeB if I configure the same ARFCN.

**Comment by pgawlowicz** [comment]
Hi, currently, the cell search procedure in srsUE is executed only using the provided ARFCN.
