### ISSUE TITLE
When 5G is used as gnb and 4G is used as ue, the two cannot be connected. Is an external clock necessary? If no external clock is needed, how to modify the configuration file? Look forward to your reply. Thank you

### ISSUE THREAD

**Issue by lcl-7** [srsran/srsRAN_Project#82]
## Issue Description ##
[Describe the issue in detail]

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by robertfalkenberg** [comment]
The gNB in srsRAN_Project is 5G-SA only, which means that only UE with 5G-SA capabilities can attach to that gNB. A 4G-only UE will not.

**Comment by lcl-7** [comment]
According to https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html's Over - the - air Setup part of the image, It's true that srsUE uses 4G, so why can't it connect?Is an external clock necessary?

**Comment by robertfalkenberg** [comment]
See https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#introduction

> srsRAN Project is a 5G CU/DU solution and does not include a UE application. However, [srsRAN 4G](https://github.com/srsran/srsRAN_4G) does include a prototype 5G UE (srsUE) which can be used for testing. This application note shows how to create an end-to-end fully open-source 5G network with srsUE, the srsRAN Project gNodeB and Open5GS 5G core network.

**Comment by lcl-7** [comment]
So do we need an external clock or not? If not, how should the configuration file be modified?

**Comment by robertfalkenberg** [comment]
It is not strictly required.
To test without external clock, just replace/omit the lines that state to use external clock, e.g.:

`gnb.yaml`
```
...
  clock:                                                        # Specify the clock source used by the RF.
  sync:                                                         # Specify the sync source used by the RF.
...
```

`ue.conf`
```
...
device_name = uhd
time_adv_nsamples = 300
...
```
