### ISSUE TITLE
 CU/DU Split Deployment

### ISSUE THREAD

**Issue by smartsaski** [srsran/srsRAN_Project#823]
## Issue Description ##
I am currently in the process of deploying the three splits of the srsRAN project and have a couple of questions that I would appreciate your guidance on:

    CU/DU Split Deployment:
    I have successfully deployed the CU/DU split at a local level. However, I am considering using separate servers for the CU and DU, . Does srsRAN support this deployment ?
    
    Split 7.2x Deployment:
    I am utilizing the Benetel RAN550 for the split 7.2x. Do I need a PTP-capable router for this setup, or would a standard router suffice if I integrate it with an external Grandmaster?

Thank you in advance for your assistance. I look forward to your expert advice.

**Comment by pgawlowicz** [comment]
This is not an issue. Please move to Discussions.
