### ISSUE TITLE
Is an external clock necessary? 

### ISSUE THREAD

**Issue by lcl-7** [srsran/srsRAN_Project#83]
## Issue Description ##
When 5G is used as gnb and 4G is used as ue, the two cannot be connected. Is an external clock necessary? If no external clock is needed, how to modify the configuration file? Look forward to your reply. Thank you

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by robertfalkenberg** [comment]
The gNB in srsRAN_Project is 5G-SA only, which means that only UE with 5G-SA capabilities can attach to that gNB. A 4G-only UE will not.
