### ISSUE TITLE
n2: failed to connect to amf on 10.53.1.2:38412. error="connection timed out" timeout=1361ms

### ISSUE THREAD

**Issue by Guo-arch1017** [srsran/srsRAN_Project#831]
operating system Ubuntu24.04
Usrp x310
I use docker compose -f docker/docker-compose.yml up
This is my profile
[docker.zip](https://github.com/user-attachments/files/17142592/docker.zip)

--== srsRAN gNB (commit ) ==--

n2: failed to connect to amf on 10.53.1.2:38412. error="connection timed out" timeout=1361ms

**Comment by pgawlowicz** [comment]
Please do not open the same topics in the issue and discussion sections.
