### ISSUE TITLE
srsUE can't initialize due to a rfnoc_graph failure

### ISSUE THREAD

**Issue by juanluisas** [srsran/srsRAN_Project#833]
## Issue Description ##
I'm trying to execute the srsRAN gNB with srsUE tutorial using my usrp x410 as srsUE. This is the error:

Active RF plugins: libsrsran_rf_uhd.so
Inactive RF plugins:
Reading configuration file ue_rf.conf...

Built in Release mode using commit ec29b0c1f on branch master.

Opening 1 channels in RF device=uhd with args=default
Supported RF device list: UHD file
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args:
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [MPMD] Initializing 1 device(s) in parallel with args: mgmt_addr=192.168.11.2,type=x4xx,product=x410,serial=32FE96C,fpga=X4_200,claimed=False,addr=192.168.11.2
[INFO] [MPM.PeriphManager] init() called with device args `fpga=X4_200,mgmt_addr=192.168.11.2,product=x410,clock_source=internal,time_source=internal'.
[ERROR] [RFNOC::GRAPH] IO Error during GSM initialization. EnvironmentError: IOError: recv error on socket: Connection refused
[ERROR] [RFNOC::GRAPH] Caught exception while initializing graph: EnvironmentError: IOError: recv error on socket: Connection refused
/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:932: uhd_init failed, freeing...
[ERROR] [UHD RF] RuntimeError: Failure to create rfnoc_graph.
Error initializing radio.

## Setup Details ##
USRP x410 is connected via SFP (I have connectivity with the device).
I'm using ubuntu 22.04 LTS
I used srsUE config file published in the tutorial.

## Expected Behavior ##
It shouldn't have any error and run the configuration of srsUE file with any problems.

## Actual Behaviour ##
It shows the error message mentioned before.

## Steps to reproduce the problem ##
I run the command `sudo srsue ue_rf.conf `
Also if I run the command `sudo uhd_usrp_probe` appears the same error message.

## Additional Information ##
The ue.log file has the next information:

2024-09-26T11:54:04.480133 [UE     ] [I] Using binary srsue with arguments: ue_rf.conf
2024-09-26T11:54:04.538161 [UE     ] [W] Number of cpu is greater than supported. CPU metrics will be disabled.
2024-09-26T11:54:04.538194 [UE     ] [I] Built in Release mode using commit ec29b0c1f on branch master.
2024-09-26T11:54:04.602087 [RF     ] [I] Configuring physical DL channel 0 with band-pass filter (0.0, 0.0)
2024-09-26T11:54:04.602088 [RF     ] [I] Configuring physical UL channel 0 with band-pass filter (0.0, 0.0)
2024-09-26T11:54:10.894822 [RF     ] [E] Error opening RF device
2024-09-26T11:54:10.894823 [RF     ] [E] Error opening RF device 0

**Comment by andrepuschmann** [comment]
It's likely a mismatch between UHD builds and runtime libraries. Have a look at the issue archive in the srsRAN 4G issue
