### ISSUE TITLE
connect srsRAN to commerical core

### ISSUE THREAD

**Issue by faratell** [srsran/srsRAN_Project#838]
Hi.
I use srsRAN 4G with the B210 and Open5GS to create an open-source network, and it works well. Is it possible to use a commercial core (not an open-source core) alongside srsRAN 4G to create a 4G network?

**Comment by pgawlowicz** [comment]
yes, it is possible, srsRAN 4G supports standard-compliant S1AP interface.

**Comment by faratell** [comment]
thanks
