### ISSUE TITLE
TRS symbol location problem(apps\units\flexible_du\du_high\du_high_config_translators.cpp)(fill_csi_resources)

### ISSUE THREAD

**Issue by lpg-delete** [srsran/srsRAN_Project#841]
## Issue Description ##
fill_csi_resources
  // [Implementation-defined] The default CSI symbols are in symbols 4 and 8, the DM-RS for PDSCH might collide in
  // symbol index 8 when the number of DM-RS additional positions is 3.
  if (uint_to_dmrs_additional_positions(cell_cfg.pdsch_cfg.dmrs_add_pos) == dmrs_additional_positions::pos3) {
    csi_params.csi_ofdm_symbol_index            = 9;
    csi_params.tracking_csi_ofdm_symbol_indexes = {4, 9, 4, 9};
  }
The trs symbol is deterministic, and {4,9} is not configured on the protocol.

**38.214
Each CSI-RS resource, defined in Clause 7.4.1.5.3 of [4, TS 38.211], is configured by the higher layer parameter NZP-CSI-RS-Resource with the following restrictions:
-	the time-domain locations of the two CSI-RS resources in a slot, or of the four CSI-RS resources in two consecutive slots (which are the same across two consecutive slots), as defined by higher layer parameter CSI-RS-resourceMapping, is given by one of
l {4 8 },{5 9},{6 10}  for frequency range 1 and frequency range 2,**

I'm not sure if I can configure it to {4 9}

## Expected Behavior ##
The trs symbol position should not be {4 9}

**Comment by herlesupreeth** [comment]
@lpg-delete Thank you for pointing it out. @xavierarteaga its related to recent changes when using DM-RS additional positions 3, we should use {6, 10} for `tracking_csi_ofdm_symbol_indexes`
