### ISSUE TITLE
A simple question about IP configuration

### ISSUE THREAD

**Issue by Sticcolet** [srsran/srsRAN_Project#851]
## Issue Description ##
I have a simple question. Is' bind_addr 'actually the port that srsgnb listens on in the configuration file? I ran AMF in the Docker container of the host and set the AMF's addr in the configuration file to the container's IP. However, I found that although the SCTP connection on port 38412 of the AMF IP in the CLI works, when I set the bind_addr in the configuration file to the host address, such as 127.0.0.1, the srsgnb program cannot connect to AMF and can only be used if it is set to 0.0.0.0. Why is this?

## Additional Information ##
I'm sorry, the previous issue was published without any editing due to accidental contact

**Comment by ismagom** [comment]
Please use discussion post for questions. This is not an issue.
