### ISSUE TITLE
gnb does not read the file yaml

### ISSUE THREAD

**Issue by mireianogue** [srsran/srsRAN_Project#856]
## Issue Description ##
I am trying to connect the srsRANProject to the 5G Core (open5gs), but it seems like they are not communicating between them. The error that I get is that 

[not readable_2](https://github.com/user-attachments/assets/8290f871-4cf3-4ac5-9ba3-01fe843b2ecd)

Moreover, If i look to the AMF logs i don't see the following message:
![image](https://github.com/user-attachments/assets/fd5ad71f-eddc-4722-a98c-78496a02bf33)
 
## Setup Details ##
I have the 5GCore (open5gs) installend in one PC and the srsRANProject installend in another PC. 

## Expected Behavior ##
I expect at least to see the message at AMF logs:
![image](https://github.com/user-attachments/assets/c3201493-7b35-4fb2-9d86-c3346eff4a65)

and 
![image](https://github.com/user-attachments/assets/16d7528e-6b04-4684-888a-df90570b9d50)
*This is an example

## Actual Behaviour ##
The actual behaviour that I'm having is:
![not readable_2](https://github.com/user-attachments/assets/d47e7fe9-bfae-4291-8cb7-e402adea6322)
![image](https://github.com/user-attachments/assets/2ac888aa-d002-43eb-b5a5-1d4f880082f2)
![image](https://github.com/user-attachments/assets/3550dc02-a5f2-43ad-9570-561691a1d974)

## Steps to reproduce the problem ##
1.Maybe i have a problem with docker files. 
2.How to configure both

## Additional Information ##
I have modified and setup the AMF, NRF & UPF yaml files of open5gs and config file of the gnb modifiying the bind address, tac, mcc & mnc. 

### gnb config file
amf:
  addr: 127.0.1.100                                               
  bind_addr: 127.0.0.1                                        

ru_sdr:
  device_driver: uhd                                              
  device_args: type=b200,num_recv_frames=64,num_send_frames=64    
  srate: 23.04                                                    
  otw_format: sc12  
  tx_gain: 80                                                     
  rx_gain: 40                                                     

cell_cfg:
  dl_arfcn: 632628                                           
  band: 78                                                       
  channel_bandwidth_MHz: 20                                      
  common_scs: 30                                                 
  plmn: "00101"                                                  
  tac: 7                                                         
  pci: 1                                                         

log:
  filename: /tmp/gnb.log                                         
  all_level: warning                                             

pcap:
  mac_enable: false                                        
  mac_filename: /tmp/gnb_mac.pcap                          
  ngap_enable: false                                       
  ngap_filename: /tmp/gnb_ngap.pcap                        

### amf file (open5gs)
logger:
  file:
    path: /var/log/open5gs/amf.log
  #level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  #The number of UE can be increased depending on memory size.
    #peer: 64

amf:
  sbi:
    server:
      - address: 127.0.0.5
        port: 7777
    client:
      #nrf:
       #- uri: http://127.0.0.10:7777
      scp:
        - uri: http://127.0.0.200:7777
  ngap:
    server:
      - address: 127.0.1.100
  metrics:
    server:
      - address: 127.0.0.5
        port: 9090
  guami:
    - plmn_id:
        mcc: 001
        mnc: 01
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: 001
        mnc: 01
      tac: 7
  plmn_support:
    - plmn_id:
        mcc: 001
        mnc: 01
      s_nssai:
        - sst: 1
  security:
    integrity_order : [ NIA2, NIA1, NIA0 ]
    ciphering_order : [ NEA0, NEA1, NEA2 ]
  network_name:
    full: Open5GS
    short: Next
  amf_name: open5gs-amf0
  time:
     #t3502:
        #value: 720   # 12 minutes * 60 = 720 seconds
    t3512:
      value: 540    # 9 minutes * 60 = 540 seconds

### nrf file (open5gs)
ogger:
  file:
    path: /var/log/open5gs/nrf.log
 #level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  #The number of UE can be increased depending on memory size.
#peer: 64

nrf:
  serving:  #5G roaming requires PLMN in NRF
    - plmn_id:
        mcc: 001
        mnc: 01
  sbi:
    server:
      - address: 127.0.0.10
        port: 7777
### upf file (open5gs)
ogger:
  file:
    path: /var/log/open5gs/upf.log
#level: info   #fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  #The number of UE can be increased depending on memory size.
#peer: 64

upf:
  pfcp:
    server:
      - address: 127.0.0.7
    client:
#smf:     #UPF PFCP Client try to associate SMF PFCP Server
#- address: 127.0.0.4
  gtpu:
    server:
      - address: 127.0.1.100
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
    - subnet: 2001:db8:cafe::/48
      gateway: 2001:db8:cafe::1
  metrics:
    server:
      - address: 127.0.0.7
        port: 9090

**Comment by pgawlowicz** [comment]
Please follow one of our tutorials, for example: https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html
