### ISSUE TITLE
Running gNB ZMQ config file | INI was not able to parse amf.++ file

### ISSUE THREAD

**Issue by womper25** [srsran/srsRAN_Project#858]
## Issue Description ##
Running the gNB using the gnb_zmq.yaml configuration file from the [documentation](https://docs.srsran.com/projects/project/en/latest/_downloads/a7c34dbfee2b765503a81edd2f02ec22/gnb_zmq.yaml) outputs the error shown below:

![gnb_zmq_Issue](https://github.com/user-attachments/assets/cd472526-f8a4-47c4-b0fc-195f0e4241e8)

## Setup Details ##
VM: Proxmox
Memory: 16 GB
Cores: 8
Hard Disk: 50 GB
Processor: host
OS: Ubuntu 22.04.5 Desktop
BIOS: Default (SeaBIOS)

I am trying to run the srsRAN gNB with srsUE using ZMQ from the tutorial in the [documentation](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#overview).

## Expected Behavior ##
After inputting the command `sudo ./gnb -c gnb_zmq.yaml` , it should output the following lines:

![gnb_zmq_working](https://github.com/user-attachments/assets/e2267fa0-5d84-4051-8bf7-ec446580f82d)

This shows that the gNB is waiting for a core network for it to connect.

## Actual Behaviour ##
For some reason, it always shows the INI cannot parse the amf in the configuration file:

![gnb_zmq_Issue](https://github.com/user-attachments/assets/1bf93b31-9c15-4e5f-80d2-411c5adf0208)
 

## Steps to reproduce the problem ##
The problem appears when trying to install srsRAN_Project (install from source with ZMQ enabled) on a fresh VM (both in Proxmox and VirtualBox).

## Additional Information ##
- I have not change any of the parameters inside the gnb_zmq.yaml configuration file.
- I made sure that ZeroMQ has been found when doing the cmake../ command. 
- I have copied the gnb binary file from `/srsRAN_Project/build/apps/gnb` to `/usr/bin/gnb`
- Aside from the actual documentation, I also followed this [tutorial](https://github.com/devopsjourney23/my-srsproject-demo)

**Comment by HaoxinSEU** [comment]
My two cents:
AMF section is now under cu_cp in the configuration file, you can check examples under the folder `./configs/`

**Comment by pgawlowicz** [comment]
indeed, there was a change in the config structure. We are updating the docs.

**Comment by womper25** [comment]
> indeed, there was a change in the config structure. We are updating the docs.

Hello thank you for your feedback. With that, should we just wait for the documentation update? Or is there a fix we can do?

**Comment by womper25** [comment]
Hello thank you for your feedback. With that, should we just wait for the documentation update? Or is there a fix we can do?

**Comment by pgawlowicz** [comment]
just update your config as done here: https://github.com/srsran/srsRAN_Project/blob/main/configs/gnb_rf_b210_fdd_srsUE.yml#L8-L19

**Comment by womper25** [comment]
> just update your config as done here: https://github.com/srsran/srsRAN_Project/blob/main/configs/gnb_rf_b210_fdd_srsUE.yml#L8-L19

I tried placing the amf IP addresses within the cu-cp header [and pasted some of the info from the b210 config file] and it works now. Thank you so much!

**Comment by zhaofeidudu** [comment]
> > just update your config as done here: https://github.com/srsran/srsRAN_Project/blob/main/configs/gnb_rf_b210_fdd_srsUE.yml#L8-L19
> 
> I tried placing the amf IP addresses within the cu-cp header [and pasted some of the info from the b210 config file] and it works now. Thank you so much!

**Comment by zhaofeidudu** [comment]
> > just update your config as done here: https://github.com/srsran/srsRAN_Project/blob/main/configs/gnb_rf_b210_fdd_srsUE.yml#L8-L19
> 
> I tried placing the amf IP addresses within the cu-cp header [and pasted some of the info from the b210 config file] and it works now. Thank you so much!

how to do this，i also have this problem，thank you

**Comment by pgawlowicz** [comment]
Please adapt your `amf` config to be now under `cu_cp` as in the example config linked above.

**Comment by zhaofeidudu** [comment]
> Please adapt your `amf` config to be now under `cu_cp` as in the example config linked above.

Thank you for your answer. I have changed gnb_zmq.yml in /srsRAN Project/build/apps/gnb,and amf.yml in ~/srsRAN Project/apps/gnb.But the problem still exists, my work is srsRAN gNB for 5G NTN
<img width="1105" alt="微信图片_20241021154350" src="https://github.com/user-attachments/assets/0a0c7830-6e6a-44be-b4b5-b0293935b2d9">
<img width="740" alt="微信图片_20241021154356" src="https://github.com/user-attachments/assets/99b3bdef-526a-47ac-b32b-a8806abe3820">
<img width="1100" alt="微信图片_20241021154359" src="https://github.com/user-attachments/assets/596fa5f8-f3e6-4b40-9859-9b719afbe17d">

**Comment by pgawlowicz** [comment]
Please pull the newest Project version.

**Comment by zhaofeidudu** [comment]
> Please pull the newest Project version.

i already use the latest version

**Comment by pgawlowicz** [comment]
the newest commit is `9d5dd74`

**Comment by zhaofeidudu** [comment]
> the newest commit is `9d5dd74`

i dont know how to change my commit to 9d5dd74,my commit is 51e44a642. is there a way to change it ?thanks a lot

**Comment by pgawlowicz** [comment]
git pull

**Comment by 27-Parth** [comment]
even after pulling the latest version, it is not working, please help me out.
