### ISSUE TITLE
Does nr_cell_search_rf work for band 28?

### ISSUE THREAD

**Issue by Carcalmoa** [srsran/srsRAN_Project#861]
## Issue Description ##
I would like to scan band 28 using nr_cell_search_rf.

## Expected Behavior ##
Get an output similar to cell_search:

![Captura desde 2024-10-10 14-13-20](https://github.com/user-attachments/assets/1b6da10b-d23e-4b66-b28a-09871aed59d3)

## Actual Behaviour ##
![image](https://github.com/user-attachments/assets/959c1d32-61a6-4e45-b9e5-575ff541df70)

## Steps to reproduce the problem ##
./nr_cell_search_rf --bands 28 --rf.device_name uhd --rf.device_args "type=b200, serial=xxxx" --rf.log_level info --log_level info --rf.rx_gain 50 

## Additional Information ##
I don't understand why the central frequency is initialized to 0. I also tried to put it as a parameter and to use the value 780.5MHz as the downlink frequency range for band 28, which goes from 758 MHz to 803 MHz. I have checked that the SSB frequencies calculated for this band are correct following TS38.104 Table 5.4.3.1-1. Could someone help me? I would also be grateful if someone could suggest other ways of scanning this band using software. Thank you all!

![image](https://github.com/user-attachments/assets/9ff2a4ad-2c4c-4ecd-bbee-38fc0a0a1142)

**Comment by pgawlowicz** [comment]
The question is related to the srsRAN-4G Project. Please move it to the correct github repository.
