### ISSUE TITLE
iperf in srsue not able to connect to open5gs with udp traffic

### ISSUE THREAD

**Issue by joelrenjith** [srsran/srsRAN_Project#864]
### System details ###
  - Ubuntu 20.04 LTS
  - GCP Virtual Machine
  
  
## Setup Details ##
  - I am trying to do the srsue zermq setup given in this link : [srsRAN gNB with srsUE](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html)
  - srsRAN_4G [Version 23.04] installation done according to [srsran4g Installation Guide](https://docs.srsran.com/projects/4g/en/latest/general/source/1_installation.html)
  - srsRAN_Project [Version 24.04] installation done according to [srsProject Installation Guide](https://docs.srsran.com/projects/project/en/latest/user_manuals/source/installation.html) using **Clone and Build**.
  - ZeroMQ setup using [srsRAN 4G with ZMQ Virtual Radios](https://docs.srsran.com/projects/4g/en/next/app_notes/source/zeromq/source/index.html) and [Build srsRAN_Project 5G RAN with ZeroMQ
](https://github.com/s5uishida/build_srsran_5g_zmq)

## Expected Behavior ##
  - I have a setup that connects a UE to a RAN and the RAN to the Core using zeromq as shown in this link: [ZeroMQ-based Setup](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#zeromq-based-setup)
  - I am able to connect the srsue to open5gs
![image](https://github.com/user-attachments/assets/b2de55e5-3da6-45bd-8ddb-641905e56150)

  - Setup testing results for everything other than iperf
![image](https://github.com/user-attachments/assets/bd2364e2-b95a-445c-837e-12470b97ffe8)

## Actual Behaviour ##
  -For Iperf Testing, I setup a server on the core container:     
![image](https://github.com/user-attachments/assets/af7624dc-94b5-4ead-a28d-4d834ea17321)

  - When I try running the command for iperf client on the host machine, this comes up
![image](https://github.com/user-attachments/assets/9397f2d6-7738-441b-8b50-e3977e0386c9)

  - So I changed the IP Address and it works for tcp:
![image](https://github.com/user-attachments/assets/76ad5b9e-2042-4948-a834-2b57b79f4a78)

  - But for UDP this is the error:
![image](https://github.com/user-attachments/assets/792a9e61-bafe-4fed-a428-65aa5ba3c434)

## Steps to reproduce the problem ##
   - Follow the steps mentioned in zeromq setup of [ZeroMQ-based Setup](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#zeromq-based-setup)
   - i ran  `make ` command again for srsran_4g and srsran_project to include zeromq
   
## Additional Information ##
  - I tried fixing the issue by doing this but it didnt work.
![image](https://github.com/user-attachments/assets/88c9e546-b467-4e19-97ac-d6ad669f01dd)

  
  
  
Any help that's provided would be greatly appreciated. Thanks in advance

**Comment by pgawlowicz** [comment]
could your share your gnb and srsue logs? is it possible to ping core from UE?

**Comment by joelrenjith** [comment]
Yes ping in the uplink direction works from the UE:
![image](https://github.com/user-attachments/assets/eba2db71-3d91-4cb1-8840-0c55e22c3fd2)
![image](https://github.com/user-attachments/assets/ad2d9516-ca9c-4d90-b8e8-4f9f4d968e5e)


Here are the gnb and ue logs:
[gnb.log](https://github.com/user-attachments/files/17375066/gnb.log)
[ue.log](https://github.com/user-attachments/files/17375068/ue.log)

**Comment by joelrenjith** [comment]
> could you share your gnb and srsue logs? is it possible to ping core from UE?

Hey @pgawlowicz ,
Yes ping in the uplink direction works from the UE:
![image](https://github.com/user-attachments/assets/2f0b0e85-53b0-4656-86dd-776b45cb6b55)
![image](https://github.com/user-attachments/assets/0944d088-6511-48b1-8fc1-cf82def229a2)

Here are the gnb and ue logs:
[ue.log](https://github.com/user-attachments/files/17375079/ue.log)
[gnb.log](https://github.com/user-attachments/files/17375080/gnb.log)

**Comment by joelrenjith** [comment]
@pgawlowicz  I have added an update to the reply to your question regarding pinging the core. I have edited the previous message but its basically this:
![image](https://github.com/user-attachments/assets/fd782203-2a68-4e0e-baf4-edd41866b11b)

**Comment by joelrenjith** [comment]
ohh ohkay thanks a lot!
