### ISSUE TITLE
Sample configuration for use in private 5G for a NPN on a dedicated private licensed band.

### ISSUE THREAD

**Issue by ohault** [srsran/srsRAN_Project#873]
Hello,

Does it possible to know how to configure srsRAN to be used on a dedicated private band licensed by local regulator ?

e.g.
Frequency : 4010 MHz
Bandwidth : 20 MHz : https://fccid.io/Emissions-Designator/20M0D7W

This would result to a 5G NR ARFCN of 667333, but this value would not be accepted by the current version of srsRAN.

How should we go about doing things properly?

**Comment by pgawlowicz** [comment]
could you share your gnb config?

**Comment by ohault** [comment]
Hi, @pgawlowicz, we should be able to share it tomorrow.
