### ISSUE TITLE
How to Modify RRC Algorithm ?

### ISSUE THREAD

**Issue by Kong-TaeHyeon** [srsran/srsRAN_Project#878]
## Issue Description ##
Default Setting : EEA0  
So, I modified rrc_ue.cc and build that.
But, I counted Below Error.  
![image](https://github.com/user-attachments/assets/62351466-7ad7-4a99-8bdc-fcf9c8f7d38f)

 

## Setup Details ##
I modified rrc_ue.cc (srsenb/src/stack/rrc)
![image](https://github.com/user-attachments/assets/f69652a3-9a15-42df-8ecf-249d4cca1492)

**Comment by pgawlowicz** [comment]
Please change the order of this list:`cu_cp.security.nea_pref_list` in gnb config. 
Check here: https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html
