### ISSUE TITLE
 F1 Setup failed. Cause: CU-CP responded with F1 Setup Failure

### ISSUE THREAD

**Issue by smartsaski** [srsran/srsRAN_Project#882]
## Issue Description ##
I ran srsCU on a different host machine than the srsRAN DU, When I try to run the DU It shows an error mesage

![image](https://github.com/user-attachments/assets/83c5ff7f-c72c-40a8-b9b4-c1ebaaf366b2)

## Additional Information ##
# Configuration:
# CU:
`gnb_id: 441
gnb_id_bit_length: 32
ran_node_name: cu_cp_01

amf:
  addr: 127.0.0.5
  bind_addr: 127.0.0.2

cu_cp:
  inactivity_timer: 7200
  plmns: "00101"
  tacs: "1"

  f1ap:
    bind_addr: 192.168.1.40

cu_up:
  nru:
    bind_addr: 192.168.1.40
    udp_max_rx_msgs: 256`

# DU:
`gnb_id: 411
gnb_id_bit_length: 32
#gnb_du_id: 0

f1ap:
  cu_cp_addr:  192.168.1.40
  bind_addr: 192.168.1.41

nru:
  bind_addr: 192.168.1.41

ru_sdr:
  device_driver: uhd
  device_args: type=x300,num_recv_frames=64,num_send_frames=64
  srate: 92.16
  tx_gain: 30
  rx_gain: 15

cell_cfg:
  dl_arfcn: 663264
  band: 77
  channel_bandwidth_MHz: 80
  common_scs: 30
  plmn: "00101"
  tac: 1
  pci: 1
  

log:
  filename: /tmp/du.log
  all_level: warning

pcap:
  mac_enable: true
  mac_filename: /tmp/du_mac.pcap
  f1ap_enable: true
  f1ap_filename: /tmp/du_f1ap.pcap
  f1u_enable: true
  f1u_filename: /tmp/du_f1u.pcap`

## Logs ##
2024-10-21T09:25:50.602570 [CONFIG  ] [I] Input configuration (only non-default values): 
gnb_id: 411
gnb_id_bit_length: 32
log:
  filename: /tmp/du.log
  all_level: info
  f1ap_level: info
  f1u_level: info
  du_level: info
f1ap:
  cu_cp_addr: 192.168.1.40
  bind_addr: 192.168.1.41
nru:
  bind_addr: 192.168.1.41
pcap:
  f1ap_filename: /tmp/du_f1ap.pcap
  f1ap_enable: true
  f1u_filename: /tmp/du_f1u.pcap
  f1u_enable: true
  mac_filename: /tmp/du_mac.pcap
  mac_enable: true
cell_cfg:
  pci: 1
  dl_arfcn: 663264
  band: 77
  common_scs: 1
  channel_bandwidth_MHz: 80
  plmn: 00101
  tac: 1
ru_sdr:
  srate: 92.16
  device_driver: uhd
  device_args: type=x300,num_recv_frames=64,num_send_frames=64
  tx_gain: 30
  rx_gain: 15
2024-10-21T09:25:51.569235 [DU      ] [I] Built in Release mode using commit 4cf7513e9 on branch main
2024-10-21T09:25:51.578085 [ALL     ] [I] Task worker "phy_prach#0" started...
2024-10-21T09:25:51.578154 [ALL     ] [I] Task worker "ru_stats_worker" started...
2024-10-21T09:25:51.578191 [ALL     ] [I] Task worker "radio" started...
2024-10-21T09:25:51.578229 [ALL     ] [I] Task worker "lower_phy_dl#0" started...
2024-10-21T09:25:51.578483 [ALL     ] [I] Task worker "lower_phy_ul#0" started...
2024-10-21T09:25:51.578787 [SCTP-GW ] [I] F1-C: Bind to 192.168.1.41:0 was successful
2024-10-21T09:25:51.579358 [GTPU    ] [I] GTP-U demux. warn_on_drop=true
2024-10-21T09:25:51.579362 [UDP-GW  ] [I] UDP GW configured. rx_max_mmsg=256
2024-10-21T09:25:51.581901 [IO-EPOLL] [I] fd=10: Registered file descriptor successfully
2024-10-21T09:25:51.582861 [GNB     ] [I] SSB derived parameters for cell: 1, band: 77, dl_arfcn:663264, crbs: 217 scs:30kHz, ssb_scs:30kHz:
	 - SSB offset pointA:28 
	 - k_SSB:12 
	 - SSB arfcn:661248 
	 - Coreset index:11 
	 - Searchspace index:0
2024-10-21T09:25:51.583250 [GNB     ] [I] SSB derived parameters for cell: 1, band: 77, dl_arfcn:663264, crbs: 217 scs:30kHz, ssb_scs:30kHz:
	 - SSB offset pointA:28 
	 - k_SSB:12 
	 - SSB arfcn:661248 
	 - Coreset index:11 
	 - Searchspace index:0
2024-10-21T09:25:51.583587 [GNB     ] [I] SSB derived parameters for cell: 1, band: 77, dl_arfcn:663264, crbs: 217 scs:30kHz, ssb_scs:30kHz:
	 - SSB offset pointA:28 
	 - k_SSB:12 
	 - SSB arfcn:661248 
	 - Coreset index:11 
	 - Searchspace index:0
2024-10-21T09:25:51.660748 [DU      ] [I] DU created successfully
2024-10-21T09:25:51.660752 [DU      ] [I] DU wrapper created successfully
2024-10-21T09:25:53.987011 [IO-EPOLL] [I] fd=0: Registered file descriptor successfully
2024-10-21T09:25:53.987013 [DU      ] [I] Starting DU...
2024-10-21T09:25:53.987014 [DU      ] [I] Starting DU-High...
2024-10-21T09:25:53.987015 [DU-MNG  ] [I] DU manager starting...
2024-10-21T09:25:53.987381 [IO-EPOLL] [I] fd=9: Registered file descriptor successfully
2024-10-21T09:25:53.987383 [SCTP-GW ] [I] F1-C: SCTP connection to CU-CP on 192.168.1.40:38471 was established
2024-10-21T09:25:53.987389 [DU-F1   ] [I] F1-C: TNL connection to CU-CP on 192.168.1.40:38471 accepted
2024-10-21T09:25:53.987542 [DU-MNG  ] [I] SIB1 cell=0: {
  "cellSelectionInfo": {
    "q-RxLevMin": -70,
    "q-QualMin": -20
  },
  "cellAccessRelatedInfo": {
    "plmn-IdentityInfoList": [
      {
        "plmn-IdentityList": [
          {
            "mcc": [
              0,
              0,
              1
            ],
            "mnc": [
              0,
              1
            ]
          }
        ],
        "trackingAreaCode": "000000000000000000000001",
        "cellIdentity": "000000000000000000000001100110110000",
        "cellReservedForOperatorUse": "notReserved"
      }
    ]
  },
  "connEstFailureControl": {
    "connEstFailCount": "n1",
    "connEstFailOffsetValidity": "s30",
    "connEstFailOffset": 1
  },
  "servingCellConfigCommon": {
    "downlinkConfigCommon": {
      "frequencyInfoDL": {
        "frequencyBandList": [
          {
            "freqBandIndicatorNR": 77
          }
        ],
        "offsetToPointA": 28,
        "scs-SpecificCarrierList": [
          {
            "offsetToCarrier": 0,
            "subcarrierSpacing": "kHz30",
            "carrierBandwidth": 217,
            "txDirectCurrentLocation": 1302
          }
        ]
      },
      "initialDownlinkBWP": {
        "genericParameters": {
          "locationAndBandwidth": 16499,
          "subcarrierSpacing": "kHz30"
        },
        "pdcch-ConfigCommon": {
          {
            "commonSearchSpaceList": [
              {
                "searchSpaceId": 1,
                "controlResourceSetId": 0,
                "monitoringSlotPeriodicityAndOffset": {
                },
                "monitoringSymbolsWithinSlot": "10000000000000",
                "nrofCandidates": {
                  "aggregationLevel1": "n0",
                  "aggregationLevel2": "n0",
                  "aggregationLevel4": "n1",
                  "aggregationLevel8": "n0",
                  "aggregationLevel16": "n0"
                },
                "searchSpaceType": {
                  "common": {
                    "dci-Format0-0-AndFormat1-0": {
                    }
                  }
                }
              }
            ],
            "searchSpaceSIB1": 0,
            "pagingSearchSpace": 1,
            "ra-SearchSpace": 1
          }
        },
        "pdsch-ConfigCommon": {
          {
            "pdsch-TimeDomainAllocationList": [
              {
                "mappingType": "typeA",
                "startSymbolAndLength": 40
              },
              {
                "mappingType": "typeA",
                "startSymbolAndLength": 85
              }
            ]
          }
        }
      },
      "bcch-Config": {
        "modificationPeriodCoeff": "n4"
      },
      "pcch-Config": {
        "defaultPagingCycle": "rf128",
        "nAndPagingFrameOffset": {
        },
        "ns": "one"
      }
    },
    "uplinkConfigCommon": {
      "frequencyInfoUL": {
        "frequencyBandList": [
          {
            "freqBandIndicatorNR": 77
          }
        ],
        "absoluteFrequencyPointA": 660660,
        "scs-SpecificCarrierList": [
          {
            "offsetToCarrier": 0,
            "subcarrierSpacing": "kHz30",
            "carrierBandwidth": 217
          }
        ]
      },
      "initialUplinkBWP": {
        "genericParameters": {
          "locationAndBandwidth": 16499,
          "subcarrierSpacing": "kHz30"
        },
        "rach-ConfigCommon": {
          {
            "rach-ConfigGeneric": {
              "prach-ConfigurationIndex": 159,
              "msg1-FDM": "one",
              "msg1-FrequencyStart": 6,
              "zeroCorrelationZoneConfig": 0,
              "preambleReceivedTargetPower": -100,
              "preambleTransMax": "n7",
              "powerRampingStep": "dB4",
              "ra-ResponseWindow": "sl20"
            },
            "ssb-perRACH-OccasionAndCB-PreamblesPerSSB": {
              "one": "n64"
            },
            "ra-ContentionResolutionTimer": "sf64",
            "prach-RootSequenceIndex": {
              "l139": 1
            },
            "msg1-SubcarrierSpacing": "kHz30",
            "restrictedSetConfig": "unrestrictedSet"
          }
        },
        "pusch-ConfigCommon": {
          {
            "pusch-TimeDomainAllocationList": [
              {
                "k2": 4,
                "mappingType": "typeA",
                "startSymbolAndLength": 27
              },
              {
                "k2": 5,
                "mappingType": "typeA",
                "startSymbolAndLength": 27
              },
              {
                "k2": 6,
                "mappingType": "typeA",
                "startSymbolAndLength": 27
              },
              {
                "k2": 7,
                "mappingType": "typeA",
                "startSymbolAndLength": 27
              },
              {
                "k2": 11,
                "mappingType": "typeA",
                "startSymbolAndLength": 27
              }
            ],
            "msg3-DeltaPreamble": 6,
            "p0-NominalWithGrant": -76
          }
        },
        "pucch-ConfigCommon": {
          {
            "pucch-ResourceCommon": 11,
            "pucch-GroupHopping": "neither",
            "p0-nominal": -90
          }
        }
      },
      "timeAlignmentTimerCommon": "infinity"
    },
    "n-TimingAdvanceOffset": "n25600",
    "ssb-PositionsInBurst": {
      "inOneGroup": "10000000"
    },
    "ssb-PeriodicityServingCell": "ms10",
    "tdd-UL-DL-ConfigurationCommon": {
      "referenceSubcarrierSpacing": "kHz30",
      "pattern1": {
        "dl-UL-TransmissionPeriodicity": "ms5",
        "nrofDownlinkSlots": 6,
        "nrofDownlinkSymbols": 8,
        "nrofUplinkSlots": 3,
        "nrofUplinkSymbols": 0
      }
    },
    "ss-PBCH-BlockPower": -16
  },
  "ue-TimersAndConstants": {
    "t300": "ms1000",
    "t301": "ms1000",
    "t310": "ms1000",
    "n310": "n1",
    "t311": "ms3000",
    "n311": "n1",
    "t319": "ms1000"
  }
}
2024-10-21T09:25:53.987619 [DU-F1   ] [I] F1 Setup: Sending F1 Setup Request to CU-CP...
2024-10-21T09:25:53.987620 [DU-F1   ] [I] Tx PDU du=0 tid=0: F1SetupRequest
2024-10-21T09:25:53.987977 [DU-F1   ] [I] Rx PDU du=0 tid=0: F1SetupFailure`

**Comment by pgawlowicz** [comment]
@smartsaski any update on this issue?

**Comment by pgawlowicz** [comment]
Close due to a lack of activity
