### ISSUE TITLE
sudo: ./scripts/srsran_performance: command not found

### ISSUE THREAD

**Issue by zhaofeidudu** [srsran/srsRAN_Project#883]
<img width="977" alt="微信图片_20241021171821" src="https://github.com/user-attachments/assets/97842de7-264a-49dc-9339-21a8ea846cea">
<img width="726" alt="微信图片_20241021171914" src="https://github.com/user-attachments/assets/e4e58726-979d-4026-b665-2436e98e2b5b">

**Comment by LuxeZN** [comment]
In script directory and run
```
chmod +x srsran_performance
sudo ./srsran_performance
```
