### ISSUE TITLE
ProblemGEO in build NTN channel Emulator

### ISSUE THREAD

**Issue by zhaofeidudu** [srsran/srsRAN_Project#884]
when i do this :python3 ./geo ntn channel emulator.py --channel-delay-us=119720
i has problem:vmcircbuf _prefs::get :info: /root/.gnuradio/prefs/vmcircbuf default factory failed to open: bad true, fail true, eof true
<img width="801" alt="微信图片_20241021172602" src="https://github.com/user-attachments/assets/5f429353-e727-4d98-9d6c-54966471f96a">
<img width="752" alt="微信图片_20241021172604" src="https://github.com/user-attachments/assets/08248f72-28df-4d71-84e9-efce07ff6b5d">

**Comment by pgawlowicz** [comment]
does the scritpt exit?

**Comment by zhaofeidudu** [comment]
> does the scritpt exit?

it only have this information,and i can return my order column, i dont think the scritpt exit.
