### ISSUE TITLE
Is it possible to reduce the CPU consumption of the gNB?

### ISSUE THREAD

**Issue by Carcalmoa** [srsran/srsRAN_Project#894]
## Issue Description ##
I get underflows when I'm running my gNB for a couple of minutes. I think that it is caused by the CPU consumption. 

I have already tried to execute the [srsran_performance](https://github.com/srsran/srsRAN_Project/blob/main/scripts/srsran_performance) but it doesn't change a lot.

Could someone help me? Thank you very much!

## Setup Details ##
This is my gNB config file: 
[gnb_rf_77.yaml.txt](https://github.com/user-attachments/files/17488091/gnb_rf_77.yaml.txt)

## Actual Behaviour ##
![Captura desde 2024-10-23 11-02-59](https://github.com/user-attachments/assets/79a98d8f-5210-4f72-ac99-a779504560ae)

**Comment by pgawlowicz** [comment]
Does it also happen with a lower cell bandwidth?

**Comment by pgawlowicz** [comment]
@Carcalmoa any update on this issue?
