### ISSUE TITLE
INI was not able to parse ntn.ephemeris_info.++

### ISSUE THREAD

**Issue by zhaofeidudu** [srsran/srsRAN_Project#914]
<img width="510" alt="微信图片_20241106124454" src="https://github.com/user-attachments/assets/7f91e514-4e5f-443b-91dd-7e35fd75fea4">
how can i fix this problem?

**Comment by zhaofeidudu** [comment]
<img width="455" alt="geontn" src="https://github.com/user-attachments/assets/38e95ee6-3572-4008-923c-3ffceb0b28ab">
<img width="646" alt="gnbzmq" src="https://github.com/user-attachments/assets/d1b35dfc-59ac-41e4-ab8d-3648b9c3d3ce">
here is my geontn and gnbzmq

**Comment by pgawlowicz** [comment]
could you share your gnb logs?

**Comment by pgawlowicz** [comment]
it should be at `/tmp/gnb.log`
