### ISSUE TITLE
Nuand BladeRF XA4 Support

### ISSUE THREAD

**Issue by cchla1021** [srsran/srsRAN_Project#919]
## Issue Description ##
Is the srsRAN support bladeRF SDR?

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by antonioo420** [comment]
There is not, but there is a Soapy Wrapper for UHD, and Soapy is available through Soapy, so you can use it. Some months ago, I followed the steps mentioned in this thread [(https://github.com/srsran/srsRAN_Project/discussions/222)](url) and it worked.
