### ISSUE TITLE
make: *** [Makefile:141: all] Error 2

### ISSUE THREAD

**Issue by raul-parada** [srsran/srsRAN_Project#932]
[error_make.txt](https://github.com/user-attachments/files/17732225/error_make.txt)

I'm trying to setup this test https://docs.srsran.com/projects/project/en/latest/tutorials/source/cotsUE/source/index.html

The gNB is installed using the Vanilla Installation

The OS is Ubuntu 20.04.6 LTS

Attached the error when executing make -j $(nproc) also tried make.

**Comment by pgawlowicz** [comment]
We are not testing with Ubuntu 20.04 any more. 
Probably, you can still use it if you update gcc (to at least 11.4.0).

**Comment by raul-parada** [comment]
@pgawlowicz it worked with gcc 10.5.0
