### ISSUE TITLE
gnb_zmq.yaml failed to bind SCTP socket to 10.53.1.1:0. Cause: Cannot assign requested address

### ISSUE THREAD

**Issue by mcmtwjyy** [srsran/srsRAN_Project#943]
I didn't find a solution that really worked

## Issue Description ##
I follow the srsRAN_Project file requirements, using USRP B200, based on 
sudo./gnb -c gnb_zmq.yam
l directive want to be able to run.
But here's the problem
![1](https://github.com/user-attachments/assets/9f50f802-d7cc-4cea-adb5-5ad56546f13d)

Failed to bind SCTP socket to 10.53.1.1:0. Cause：Cannot assign requested address
srsRAN ERROR: Failed to create SCTP gateway client.

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by pgawlowicz** [comment]
Did you start the dockerized version of Open5GS? if not, then most probably you do not have an interface with `ip=10.53.1.1`,

**Comment by mcmtwjyy** [comment]
thank you! I will try again to verify.



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 21, 2024 19:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [srsran/srsRAN_Project] gnb_zmq.yaml failed to bind SCTP socketto 10.53.1.1:0. Cause: Cannot assign requested address (Issue #943)




 
Did you start the dockerized version of Open5GS? if not, then most probably you do not have an interface with ip=10.53.1.1,
