### ISSUE TITLE
srsUE(B200mini) in TDD wired connection with Gnb(B210)

### ISSUE THREAD

**Issue by kevsP20** [srsran/srsRAN_Project#953]
## Issue Description ##
I am testing 5G NR band n39 which is in TDD configuration. I am using USRP B210 in my gnb and USRP B200mini for srsUE. with my usual setup i am easily getting connection in FDD bands but i am stuck at one point in TDD which i am thinking there is some connection issue for TDD, as it should have same line for Rx and Tx(atleast therotically)

## Setup Details ##
i7 PC with ubuntu 22.04 LTS , srsGNB (commit 9d5dd742a) and srsUE (commit f8978a697)

## Expected Behavior ##
srsUE should get the connection to gnb

## Actual Behaviour ##
srsUE can detect the network and got successfull tuning rx and tx port (1900 Mhz in this case) and SYNC message with starting SIB1 acquisition but not able to start next procedure. here are my logs,
[gnb.log](https://github.com/user-attachments/files/17921921/gnb.log)
[ue.log](https://github.com/user-attachments/files/17921922/ue.log)

## Steps to reproduce the problem ##
- setting CPU to performance and running srsran_performance scripts
- ensuring open5gs services are up and running
- gnb
- srsUE

## Additional Information ##
seems like for TDD communication between UE and gnb, it's not happening through correct port. Maybe receiving side is somewhere else and transmitting is something else. since, FDD cell worked properly.
for visualization purpose current connection looks like:
![image](https://github.com/user-attachments/assets/4fbb5c3d-3dbf-4590-8893-5e357c907258)

Please let me know if some setting or parameters needs to be changed or am i missing out something..Thank you in advance!

**Comment by pgawlowicz** [comment]
srsUE does not support TDD: https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#limitations
