### ISSUE TITLE
UE cannot connect to the network

### ISSUE THREAD

**Issue by mireianogue** [srsran/srsRAN_Project#958]
## Issue Description ##
I have problems connecting my UE to srsRAN. 

## Setup Details ##
2 PC Lenovo IntelCore i5-10600 CPU
SIM sysmoISIM-SJA5 
CrosCall core Z5
USRP B210
2 antennas

Here are the files: (I haven't attached the gnb.log file because it doesn't contain anything)
gnb config file: 
[gnb_rf_b200_tdd_n78_10.txt](https://github.com/user-attachments/files/17938714/gnb_rf_b200_tdd_n78_10.txt)
core files: 
[nrf.txt](https://github.com/user-attachments/files/17938719/nrf.txt)
[amf.txt](https://github.com/user-attachments/files/17938723/amf.txt)
[upf.txt](https://github.com/user-attachments/files/17938732/upf.txt)

I have already programmed the SIM and the core:
![configuracio sim core](https://github.com/user-attachments/assets/1540c792-f2c4-46b0-a8e1-65134a52f0c0)
![PROGRAMR-SIM](https://github.com/user-attachments/assets/58b74f8d-89d1-4c59-9e03-09400bee6562)

## Expected Behavior ##
I expect to see trafic and the mobile phone connected to the network:
![image](https://github.com/user-attachments/assets/7f8ce787-7b8c-4b35-acd4-ad4f8bcfe892)

## Actual Behaviour ##
Actually, I have achived to see the network in app called Qualipoc:
![WhatsApp Image 2024-11-27 at 19 20 30 (3)](https://github.com/user-attachments/assets/699b4d4a-3784-4ade-a96a-f8991d56cb71)
![WhatsApp Image 2024-11-27 at 19 20 30](https://github.com/user-attachments/assets/e3e49a6e-a5de-454f-bd8a-1f9d280981ec)
![WhatsApp Image 2024-11-27 at 19 20 30 (2)](https://github.com/user-attachments/assets/6dadeb79-6490-4600-98ea-95af9d8fe179)

But in the console of gnb i see this:
![1_qualipc](https://github.com/user-attachments/assets/83fd6384-3862-4c03-99bf-dfd85529a12c)

Does anyone has the same problem?

**Comment by pgawlowicz** [comment]
could you share you gnb logs?

**Comment by mireianogue** [comment]
Here it is the gnb log file:
[gnb.log.txt.log](https://github.com/user-attachments/files/17943884/gnb.log.txt.log)

**Comment by mireianogue** [comment]
Also, i'm going to share the singalling that I'm obtaining in Qualipoc app:
![Screenshot_20241128-103913](https://github.com/user-attachments/assets/f692f5d6-5c34-4371-b6e4-f0d0f224063f)
![Screenshot_20241128-104000](https://github.com/user-attachments/assets/dec4c60e-12c4-4d7c-8019-443c6b84442e)
![Screenshot_20241128-103956](https://github.com/user-attachments/assets/6b74e477-0e51-4684-b2b0-fcbdff873069)
![Screenshot_20241128-104017](https://github.com/user-attachments/assets/23c1f543-c496-4e51-bab2-af3f1947eb0b)
![Screenshot_20241128-103946](https://github.com/user-attachments/assets/79315c8e-ec1c-4b9c-a5e6-e27cac444eb9)
![Screenshot_20241128-104028](https://github.com/user-attachments/assets/4af1baf4-a5ef-4a95-8d46-84190d67aa76)
![Screenshot_20241128-103923](https://github.com/user-attachments/assets/81828e35-d191-4ed6-a02e-1c060328fa8c)
![Screenshot_20241128-104009](https://github.com/user-attachments/assets/cf57e9dc-63ab-4dc2-81ef-51782528b4d8)
![Screenshot_20241128-103934](https://github.com/user-attachments/assets/89777b9b-8ade-40f8-b88f-0f064afca7dc)
![Screenshot_20241128-103951](https://github.com/user-attachments/assets/2bc9a580-39d7-452a-8913-33d722d6243c)

**Comment by mireianogue** [comment]
Where can I find this file?

**Comment by mireianogue** [comment]
[ngap_pcap_test.txt](https://github.com/user-attachments/files/17981354/ngap_pcap_test.txt)
[ngap_ue.txt](https://github.com/user-attachments/files/17981388/ngap_ue.txt)
[ngap.txt](https://github.com/user-attachments/files/17981385/ngap.txt)

**Comment by mireianogue** [comment]
I'm going to share also, the Amf logs:
![logss core](https://github.com/user-attachments/assets/997c3d61-87cf-455a-9155-f1bb8c7b1445)

**Comment by mireianogue** [comment]
![gnb_mac_pcap](https://github.com/user-attachments/assets/58bc4f12-5700-43ef-996e-e9ea67871c0a)
![ngap_pcap](https://github.com/user-attachments/assets/cf8545c2-e0d9-436b-966b-0b15a27421aa)

**Comment by mireianogue** [comment]
[gnb_mac.zip](https://github.com/user-attachments/files/17990607/gnb_mac.zip)
[gnb_ngap.zip](https://github.com/user-attachments/files/17990613/gnb_ngap.zip)

**Comment by pgawlowicz** [comment]
https://docs.srsran.com/projects/project/en/latest/user_manuals/source/outputs.html#pcaps

**Comment by mireianogue** [comment]
i have modified these wireshark files as shown in this link:
[gnb_mac.zip](https://github.com/user-attachments/files/17990788/gnb_mac.zip)
[gnb_ngap.zip](https://github.com/user-attachments/files/17990791/gnb_ngap.zip)

**Comment by mireianogue** [comment]
I have started again the costs UE tutorial and the mobile phone can see the network, but cannot attach. What do you mean for "NSG"?
![image](https://github.com/user-attachments/assets/fbb7608f-cb6e-4a15-8bf2-4417efbcb721)

**Comment by pgawlowicz** [comment]
i guess Network Signal Guru app.

**Comment by mireianogue** [comment]
Hello, 
I'm troubling with the same problem. But now i'm obtaining a diferent gnb_mac_pcap message:
 [gnb_mac_pcap.zip](https://github.com/user-attachments/files/18154435/gnb_mac_pcap.zip)

Do you able to tell me what's the error? Thank you in advance.

**Comment by pgawlowicz** [comment]
please share ngap.pcap

**Comment by mireianogue** [comment]
![segon intent1](https://github.com/user-attachments/assets/63860421-911a-4784-bc2d-ed28b7f46bf5)
![segon ion 2](https://github.com/user-attachments/assets/9e692179-2d20-4740-b2df-06a2f9a8c448)

**Comment by pgawlowicz** [comment]
looks like sth is wrong with the core network config.

**Comment by mireianogue** [comment]
Maybe in the subscription part?

**Comment by mireianogue** [comment]
![subs1](https://github.com/user-attachments/assets/2118de57-6cfe-4957-ab3a-6207b127c8db)
![subs2](https://github.com/user-attachments/assets/675c01e5-ae35-4c77-b304-e549bbed67c1)

**Comment by mireianogue** [comment]
I can share the core files configurations but i think that they are right:
[amf.zip](https://github.com/user-attachments/files/18154640/amf.zip)
[nrf.zip](https://github.com/user-attachments/files/18154641/nrf.zip)
[upf.zip](https://github.com/user-attachments/files/18154642/upf.zip)

**Comment by pgawlowicz** [comment]
do you use the newest version of the srsRAN project?

**Comment by mireianogue** [comment]
I installed srsRAN Project on July 2024 using the source code located https://github.com/srsran/srsran_project. 
But i have in the same both PC the srsRAN for LTE. Maybe is that a problem?

**Comment by pgawlowicz** [comment]
please update with the newest version. Do you run srsRAN LTE at the same time?

**Comment by mireianogue** [comment]
Okeis i'm going to update with the newest version. No, i haven't! I only run srsRAN_Project (5G). 
Thank you. I will notify you if i achieved to attach the UE.

**Comment by mireianogue** [comment]
Hello, 
I've achieved to attach the UE. The problem was that the OPc value was wrong by mistake. Thank you for your help! You can close this issue.
