### ISSUE TITLE
srsUE not attaching to gNB (ZMQ)

### ISSUE THREAD

**Issue by antonioo420** [srsran/srsRAN_Project#972]
## Issue Description ##
I am running srsUE, srsRAN and the dockerized version of Open5GS, just like this [tutorial](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#zeromq-based-setup). The issue is that srsUE is not attaching to the gNB, and in the Open5GS console i can see no messages from the UE.

On top of that srsUE is not creating the tun_srsue interface so i cannot add the route to the interface with this command

`sudo ip netns exec ue1 ip route add default via 10.45.1.1 dev tun_srsue`

## Setup Details ##
UE: srsUE
RAN: srsRAN
5GC: Open5GS dockerized version
OS: Ubuntu 22.04
RF: ZMQ

## Expected Behavior ##
I expect srsUE to attach to gNB.

## Actual Behaviour ##
srsUE does not attach and tun_srsue is not created

## Steps to reproduce the problem ##
The ones portrayed on this [tutorial](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#zeromq-based-setup)

## Additional Information ##
Attached are the conf files

[ue_zmq.zip](https://github.com/user-attachments/files/18024091/ue_zmq.zip)
[gnb_zmq.zip](https://github.com/user-attachments/files/18024023/gnb_zmq.zip)

![image](https://github.com/user-attachments/assets/faecd746-23a3-41ad-9a7e-c32a082e59c4)

![image](https://github.com/user-attachments/assets/dd90d292-6816-452f-a206-46444f5ba1ea)

**Comment by pgawlowicz** [comment]
srsUE uses config for 20MHz cell, while gnb uses config for 10MHz cell.

**Comment by antonioo420** [comment]
After changing gnb bandwidth to 20Mhz now it works. I have made the changes you said in #350 .

Thank you!
