### ISSUE TITLE
Failed to load RF plugin libsrsran_radio_uhd.so: libsrsran_radio_uhd.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nereajizu** [srsran/srsRAN_Project#990]
## Issue Description ##

I'm deploying an O-RAN using Open5gs and srsRAN. 
There is no problem when running  CU but it's not working when running DU. 
The UHD seems to be connected correctly: 

![image](https://github.com/user-attachments/assets/83b9d26c-2598-42e0-86a6-e5cdc987dd08)

When trying to run DU this error occurs:

--== srsRAN DU (commit e5d5b44b9) ==--

Lower PHY in quad executor mode.
Cell pci=1, bw=20 MHz, 1T1R, dl_arfcn=650000 (n78), dl_freq=3750.0 MHz, dl_ssb_arfcn=649632, ul_freq=3750.0 MHz

Failed to load RF plugin libsrsran_radio_uhd.so: libsrsran_radio_uhd.so: cannot open shared object file: No such file or directory
Factory for radio type uhd not found. Make sure to select a valid type.
srsRAN ERROR: Unable to create radio session.

**Comment by PanterasCy** [comment]
I am facing the same issue.
How did you fix that?
